### ISSUE TITLE
[CLIN-API] API Docs for Auth Service

### ISSUE THREAD

**Issue by nyanofthemoon** [Ferlab-Ste-Justine/clin-project#160]
Please write the documentation for all of the routes in the Auth Service in `clin-proxy-api`.

Documentation file is located in `src/services/api/auth/docs.json` and implemented using "redoc" following the OpenAPI format.

Example : https://redocly.github.io/redoc/
QA Link: https://clin.cr-ste-justine.xyz/api/auth/docs

**Comment by nyanofthemoon** [comment]
The barebones are set-up for this bit. Please have a look at the /docs endpoint for every service of clin-proxy-api and its associate `docs.json` file which is using OpenApi 3.0.0 specs.

**Comment by vferretti** [comment]
Barebones seems okay. Please complete docs.json files

**Comment by latch2112** [comment]
https://clin.cr-ste-justine.xyz/api/auth/docs
