### ISSUE TITLE
[CLIN-VAR] API Docs for Variant Service

### ISSUE THREAD

**Issue by nyanofthemoon** [Ferlab-Ste-Justine/clin-project#161]
Please write the documentation for all of the routes in the Variant Service in `clin-proxy-api`.

Documentation file is located in `src/services/api/variant/docs.yaml` and implemented using "redoc" following the OpenAPI format.

Example : https://redocly.github.io/redoc/
QA Link: https://clin.cr-ste-justine.xyz/api/variant/docs

**Comment by nyanofthemoon** [comment]
The barebones are set-up for this bit. Please have a look at the `/docs` endpoint for every service of clin-proxy-api and its associated `docs.json` file which is using **OpenApi 3.0.0** specs. There is only the docs.json files remaining to be filled up.

Online editor: https://editor.swagger.io
Complete example: https://redocly.github.io/redoc/openapi.yaml

**Comment by vferretti** [comment]
Barebones seems okay. Please complete docs.json files

**Comment by latch2112** [comment]
https://clin.cr-ste-justine.xyz/api/variant/docs
