### ISSUE TITLE
Recherche avec plusieurs mots retourne aucun résultat

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#195]
**Steps to reproduce:**

- Aller à la liste des patients
- Voici le numéro de RAMQ du patent Jake Morin: MORJ 8801 0492
- Copier-coller le dans la boite de recherche
- Bug: ne retourne aucun résultat
- Cela un rapport avec les espaces blancs. La recherche ne semble pas fonctionner avec plusieurs mots. Ex: chercher Jake Morin. Cela ne retourne rien
- A discuter comment on veut résoudre ce problème

**Comment by latch2112** [comment]
Investigation en cours...

**Comment by latch2112** [comment]
Investigation complète; j'ai regardé le type de requête ES que le service patient consomme...
Afin de bien me prononcer sur une ou des solutions, 
@luclemo, me fournir les specifications pour la recherche par patient svp

**Comment by luclemo** [comment]
@latch2112 on doit pouvoir chercher par les critères indiqués dans ce premier screenshot.

![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/17bd019a-0a1e-4db3-aef8-fd5dbaf9d38c)

 Le problème reporté est que lorsque l'on inclus un éspace dans notre terme de recherche (ex: `LEBH 8803 3093`) on n'obtient aucune suggestion dans le dropdown.

![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/109ed664-9f47-48f7-8077-1072142cae86)

![Pasted_Image_2020-04-03__2_09_PM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/1e917033-44e5-4423-930e-c28b0d70e054)

@vferretti peux-tu confirmé que j'ai bien saisi étant donné que tu avais initialement reporté ce bug (importé de trello)?

**Comment by vferretti** [comment]
oui c'est bien ca. Il serait bien de pouvoir retrouver un patient avec son numéro d'assurance maladie qui contient des espaces blancs ou un nom et prénom séparés par un espace si ce n'est pas trop compliqué à faire. 
Si trop compliqué, on peut laisser faire. C'est pour ca que je voulais en discuter.

**Comment by latch2112** [comment]
Aucun problème, j'ai la nouvelle structure de la requête ES qui va réponse aux deux besoins énumérés ici.

**Comment by latch2112** [comment]
So the new ES query should be like so:
`{
  "size": 5,
  "_source": [
      "id",
      "familyId",
      "specimens.id",
      "identifier.MR",
      "identifier.JHN",
      "name.family",
      "name.given",
      "studies.title"
    ],
  "query": {
    "bool": {
      "should": [
        {
          "multi_match": {
            "query": "",
            "type": "phrase_prefix",
            "fields": [
              "id",
              "name.family",
              "name.given",
              "studies.title",
              "specimens.id",
              "identifier.MR",
              "identifier.JHN",
              "studies.title"
              ]
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}`

**Comment by luclemo** [comment]
@latch2112 est-ce que la possibilité de chercher par prénom + nom tel qu'indiqué dans le message de @vferretti est supposé fonctionner? Si oui ça ne semble pas marcher. ex: tapper `hayden leb` pour obtenir `Hayden Leblanc` ne donne aucun résultat.

**Comment by latch2112** [comment]
ce cas-là n'est pas possible car `Hayden Leblanc` ne match aucun champs dans Elasticsearch;
Les prénoms et les noms de famille sont sur 2 champs distinct

**Comment by latch2112** [comment]
`Hayden` ou `Leblanc`devrait fonctionner

**Comment by luclemo** [comment]
ok parfait

**Comment by latch2112** [comment]
Si c'est un besoin, il y a moyen de créer un champs qui concatène le prénom et le nom.  
La structure du patient FHIR devrait être changé
https://github.com/cr-ste-justine/clin-FHIR/blob/master/patient_exemple_proband.json

**Comment by vferretti** [comment]
On ne peut pas changer la structure de FIHR, c'est un standard et c'est comme ca que les noms sont définits. On devrait plutôt changer l'index ES, mais c'est correct, on laisse faire. Juste s'assurer svp que ca fonctionne lorsqu'il y a un espace blanc à l’intérieur d'un même champs comme par exemple le numéro d'assurance maladie
