### ISSUE TITLE
Page de recherche de variants: Nom des requêtes dupliquées

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#196]
Créer un nouveau filtre et créer une requête: son nome est par défaut Requête 1
Dupliquer la en cliquant sur l'icône correspondante à gauche de la boite de requête
Ajouter le mot Copie devant le nom de la requête dupliquée. Exemple: "Copie Requête 1"

**Comment by denis-crsj** [comment]
La carte a été bougée dans le Icebox pour l'instant.
