### ISSUE TITLE
Recherche de patients. Ancien critère de recherche conservé

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#200]
- Rafraîchir la page de recherche de patients
- Taper Jake mais ne pas sélectionner de résultat
- Cliquer sur le X à gauche dans la boite pour effacer le texte de recherche
- Cliquer sur la boîte de recherche.
- BUG:  La suggestion pour Jake réapparaît sans qu’aucun texte de recherche ne soit saisi
![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/f0712dae-5ff2-494c-837e-2d8a4324892c)

**Comment by denis-crsj** [comment]
Bug that re-surfaced most probably due to a problem with the merging of the pull requests

**Comment by YanLabCHU** [comment]
Issue already fixed.
