### ISSUE TITLE
Éliminer une requête sans terme

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#202]
**Steps to reproduce:**

- Allez à la page de recherche de variant pour un patient donné
- Faire une requete  puis une deuxième.
- Éliminer un a un les terme de la deuxieme requete
- BUG: quand tous les termes de la requête sont éliminés, la boîte de la requête devrait disparaître au complet ainsi que toutes ces références dans des requêtes combinées.

**Comment by luclemo** [comment]
@vferretti je m'adresse à toit car c'est ton bug reporté:

Je ne suis pas certain que ceci soit un bug, mais plutôt des specs pas 100% défini.

En fait nous devons faire la différence entre toujours avoir au minimum une boite de requête affichée en tout temps (ex: on ne peut pas supprimer la toute première boite à son état "vide"), et pouvoir attacher la fonction "delete requête" sur tout _autre_ requête dans laquelle on a supprimée toutes les valeurs.

À discuter avec Paule.

**Comment by nyanofthemoon** [comment]
@luclemo What can I do to help with this ticket?

**Comment by luclemo** [comment]
@nyanofthemoon Sorry it's been a while since I imported this ticket and I can't access clin in order to reproduce the steps above and refresh my memory. I'll get back to you as soon as I can offer clarification... 😕

**Comment by nyanofthemoon** [comment]
@luclemo @vferretti No worries. This is my next ticket in line though... just let me know what you guys agree on please.

**Comment by luclemo** [comment]
@nyanofthemoon Trying to help, but still can't login to QA 🤷‍♂️

**Comment by nyanofthemoon** [comment]
@luclemo I think QA got back up recently.

**Comment by nyanofthemoon** [comment]
@luclemo wrong button... reopening issue.

**Comment by luclemo** [comment]
@nyanofthemoon Still not working on my end. Chrome standard and icognito.

**Comment by vferretti** [comment]
Je crois qu'on veut éviter les deux situations suivantes. 
![image](https://user-images.githubusercontent.com/1181124/79698337-4e427d00-8256-11ea-8384-1fd61d3a445f.png)
![image](https://user-images.githubusercontent.com/1181124/79698520-754d7e80-8257-11ea-8e40-8620f55c802c.png)

si on enlève tous les termes d'une requête, la boite de cette requête doit disparaître si elle n'est pas en première position. Mais ce n'est pas grave, on peu laisser ca comme ca pour le moment

**Comment by luclemo** [comment]
I think the question was answered, but it's not a priority so putting this in icebox for now. We can revisit later.

**Comment by denis-crsj** [comment]
Requête déplacée vers le Icebox de Notion pour l'instant.
