### ISSUE TITLE
Facet dropdown — boîte qui se déplace en haut à gauche de l'écran

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#206]
## Bug

La boite du dropdown (ex: HPO) se retrouve en haut à gauche de la page

## Steps

- Cliquer sur Génomique => HPO pour ouvrir le dropdown
- Naviguez les valeurs avec la pagination
- À un moment donné, la boîte se retrouve en haut à gauche de l’écran

NOTE: Je n’ai pas été capable d’identifier une séries d’opérations précises pour reproduire le bug, et il ne se limite pas à cette boîte seulement, mais c’est un problème fréquent.

**Comment by nyanofthemoon** [comment]
might be due to display
