### ISSUE TITLE
Filtre par défaut ne s’applique pas et c'est toujours le dernier filtre sélectionné qui est appliqué

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#207]
@luclemo commented on [Wed Mar 25 2020](https://github.com/cr-ste-justine/clin-backend/issues/9)

Le premier bug:
**Steps to reproduce:**

- Allez à la page de recherche de variant pour un patient donné
- Assurez vous d’avoir deux filtres sauvegardés dans le menu Mes Filtres
- Ouvrez en un pour filtrer la liste des variants
- Retourner à Mes filtres et cliquer sur l’étoile pour définir le deuxième filtre comme filtre par defaut
- Aller à la page liste de patients
- Choisir un patient proband au hasard et aller à sa page de recherche de variants
- **BUG**: le filtre par défaut sélectionné à l’étape précédente n’est pas appliqué par défaut

Le deuxième bug: (Apparu une fois que le premier a été réglé)

- Allez à la page de recherche de variant pour un patient donné
- Sélectionner un filtre qui n'est pas celui par défault
- Retourner dans la page de patients et sélectionner un autre patient
- **BUG**: Dans la recherche de variant pour le patient, c'est le dernier filtre séletionné qui est appliqué et non pas celui par défault.

**Comment by luclemo** [comment]
@FrancisRenaud ça ne fonctionne toujours pas pour moi— aucun filtre par défault ne s'affiche lorsque je me trouve sur la page de recherche de variants d'un patient... 🤔

**Comment by luclemo** [comment]
@FrancisRenaud toujours le même problem pour moi...aucun filtre par défault s'affiche
![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/1f1554cc-286d-49c5-9677-f354bd3dc6f2)

**Comment by denis-crsj** [comment]
Problème résolu, le filtre par défaut s'applique maintenant correctement lorsque nous quittons et revenons dans la page
