### ISSUE TITLE
Facet dropdown — tooltip container is too long

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#208]
## Problème

La boite du tooltip a une longueur fixe… 

- Lorsqu’on active le tooltip, sa boite est trop longue ce qui peut briser la mise-en-page
- Voir ce GIF: https://recordit.co/KpXFZ1fQgt

**Comment by denis-crsj** [comment]
La mise en page ne brise plus. Toutefois, il serait surement bon de revoir le design des tooltip car il sont toujours plus long et sortent de la boite ce qui crée un effet visuel bizarre. Pourra être adressé plus tard.
