### ISSUE TITLE
Connexion — afficher indication de mauvais mot de passe ou courriel

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#212]
## Problème

Lors de la connexion, l'utilisateur n'a aucune indication de mauvais mot de passe ou mauvais courriel.

## Steps

- Allez à la page connexion
- Faites une erreure de frappe pour le mot de passe
- La page “reload” sans aucune indication d’erreure

## Solution proposée

utiliser le même indicateur rouge que le champ réquis avec le texte: “mauvais mot de passe” ou "mauvaise adresse courriel"

![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/e1463b33-87d0-4a44-a45c-a63ba165f0a7)

**Comment by latch2112** [comment]
@luclemo Je pense que nous devrions afficher “mauvais mot de passe ou mauvaise adresse courriel" afin d'augmenter la sécurité et prévénir les attaques de type 'Brute Force'
Néanmoins, en ce moment, le backend retour un 500, je vais faire les changements pour retourner un 
401 au frontend pour être en mesure de bien traité l'erreur.

**Comment by latch2112** [comment]
@luclemo Présentement, on affiche les erreurs 'post-submit' sous forme de notification (par exemple dans la page de variant); il y a beaucoup de travail à faire pour changer le flow qui est implémenter partout. On travaille de façon asynchrone en ce moment ce qui rend ce genre de notification à la server-side rendered page très problématique voir incompatible.
La façon de faire idéal est d'utiliser le erreur message de antd !

Qu'est-ce que tu en penses ?

**Comment by luclemo** [comment]
@latch2112 

Pour ce qui est du rendement visuel, la solution que je propose était basé sur ce qui arrive déjà dans l'appli (l'image est un screenshot directement de clin) et je présume qu'on peux faire la même chose pour les autres erreurs...?

> Je pense que nous devrions afficher “mauvais mot de passe ou mauvaise adresse courriel"

Oui c'est bien ce que je propose dans mon message initial... mais un message pour chaque car ce sont deux erreurs différentes.

En fait, je ne m'oppose à rien tan que c'est cohérent et que les messages apparaissent aux bons endroits et que le tout suit les meilleurs pratiques quant aux erreurs de formulaires. Si c'est une erreur de mot de passe c'est une chose. Si c'est une erreur de courriel c'est autre chose. Et idéalement on offre aux users des repères visuels tel que le screenshot en question.

Si j'ai mal compris on peut s'en parler de vive voix pour sauver du temps :)

**Comment by latch2112** [comment]
@luclemo 
Ce qui arrive dans l'appli est fait de façon offline, le code qui sert à valider le formulaire est fait sur le browser (format valide de email, longueur de mot de passe, etc.) . L'authentification est fait en ligne; un appel est envoyer au proxy qui ensuite redirige l'appel à Keycloak...  Ensuite, le retour nous indique seulement si les credentials sont valides, donc, je ne peux pas dire si c'est le mot de passe ou si c'est le courriel qui est erronné; et de toute façon comme j'avais mentionné avec les quotes, tous site sécure qui se respecte ne dirons jamais lequel est bon et lequel est mauvais pour prévenir les attaques...
Dans le cas échéant, je dois écrire un service de validation de courriel pour être en mesure de valider un ou l'autre des informations.  

Nous avons développé une application moderne qui utilise le principe de notification; si on écrit dans le formulaire on est pu consistant avec les autres notifications...

**Comment by luclemo** [comment]
J'aurais aimé te parler de vive voix pour être plus clair/explicite mais bon pas grave. S'il n'est pas possible d'indiquer les messages au niveaux des input, je vais faire des mockups. À suivre.

Après tu pourras faire l'implementation comme tu le juge respectable.

**Comment by luclemo** [comment]
@latch2112 ok voici la maquette. Le message d'erreur apparaît post-submit tel que convenu.

N'hésites pas si tu voix des problèmes pour l'implementation.

https://www.figma.com/file/37C8rvzqMasIK0zT9n3Mls/Alerts-%26-Errors?node-id=304%3A63

**Comment by latch2112** [comment]
@luclemo Très bien.  Quel composant de antD tu veux que j'utilise pour le message ?

**Comment by luclemo** [comment]
@latch2112 C'est le "closeable" 👉 https://ant.design/components/alert/#components-alert-demo-closable

**Comment by luclemo** [comment]
@latch2112 Merci, c'est super. Quelques styling issues pour être cohérent avec le reste, mais je ne sais pas à qui les addresser... @claudia1296?

![Pasted_Image_2020-04-23__11_08_AM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/e4d7c329-07eb-441c-a283-e0e2fc2c834a)

**Comment by luclemo** [comment]
Le lien pour la maquette est plus haut

**Comment by latch2112** [comment]
Oui, si @claudia1296 pouvait m'aider, ça serait super :) J'ai essayer mais j'ai pas réussi à prendre les trucs de figma ...  Comme j'avais mentionner dans le démo, j'ai pas réussi à rendre 'pixel perfect'

**Comment by latch2112** [comment]
@claudia1296 , le code actuel est sur dev...
