### ISSUE TITLE
Page Variant - Styling

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#213]
#### Specs + Design

- [Google Sheet](https://docs.google.com/spreadsheets/d/196QRqOZi4KMiK2r7X3Bvmt79vJJA7FiSVD4Ha9IPzVs/edit#gid=0)
- [Figma](https://www.figma.com/file/JOl4AYNyJcJN34tRT7lRjR/CLIN---Page-de-variant?node-id=298%3A2991)

---

#### Onglet Résumé
- [ ] Résumé
- [ ] Références externes
- [ ] Patients
- [ ] Conséquences

#### Onglet Fréquences
- [ ] Cohortes internes
- [ ] Cohortes externes

#### Onglet associations cliniques
- [ ] Clinvar
- [ ] Orphanet
- [ ] Radboudumc
- [ ] HPO

#### Onglet patients
- [ ] Tableau patients

**Comment by luclemo** [comment]
@claudia1296 pour l'onglet fréquences, je n'ai pas fait de design HiFi car c'est en fait deux tableau Ant qui suivent le même design que les autres.

**Par contre:** les colonne sont surtout des chiffres donc vois si c'est possible de les placer l'un à côté de l'autre avec 24px entre les deux. "Cohortes Externes" a moins de colonnes donc il peut être moins large que l'autre au besoin.

![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/e11ad2af-04ba-4189-ac67-f42d430552c7)

**Comment by luclemo** [comment]
## Overflow des strings


![Pasted_Image_2020-04-08__4_34_PM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/fa84b47d-f41b-42f1-9e7c-fa48dafa3263)

### Proposition:

Ajouter ces 2 lignes de CSS:

```
.variantPageContent .datalist .ant-card-body .listRow .rowValue {
    word-break: break-all;
    flex-grow: 2;
}
```
Ça devrait offrir une solution résiliante pour les autres edge case.

**Comment by luclemo** [comment]
## Traitement des noms de variants trop long

Actuellement il y a des noms de variant qui sont trop longs **dans le tableau et aussi en tête de page**:

![Pasted_Image_2020-04-08__4_36_PM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/6af27c88-b960-4da3-8624-608353da4dc7)

### Proposition:

Si le variant a plus de 30 charactères, on affiche:

- `les 15 premiers` + `…` + `les 15 derniers`
- On affiche le tout dans un tooltip sur hover

![Pasted_Image_2020-04-08__4_46_PM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/28943f4e-de58-419d-9bd7-7c26a02b5e39)

![Pasted_Image_2020-04-08__4_47_PM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/a856918d-c71a-4178-a4e9-1746310f1c27)

**Comment by luclemo** [comment]
## Card styling -- general specs

Voir le fichier figma pour le détails

![Pasted_Image_2020-04-08__4_56_PM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/2b8464e2-3cfc-4281-bdf7-3bdcdd1ccccb)

**Comment by luclemo** [comment]
@claudia1296 dans le screenshot du dernier commentaire: la **hauteur des rangées d'une ligne** et les **valeurs top-aligned** n'ont pas été corrigé je crois. Pour le reste c'est 💯

**Comment by luclemo** [comment]
@claudia1296 Hmmm, je pense qu'il y a encore des problèmes d'affichage pour les tableaux:

![Pasted_Image_2020-04-30__2_27_PM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/9f67b8fd-cb9a-448d-980d-77a1ce1d4687)

**Comment by luclemo** [comment]
@claudia1296 regarde la page de ce variant (surtout le tableau conséquences)
https://clin.cr-ste-justine.xyz/variantDetails/0F9E5830D33834EF00EAFC6F362762EC
Merci!
