### ISSUE TITLE
Overture Client: Load data and metadata provided By Alex into Local Overture Stack

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#215]
add substasks here

**Comment by Magnitus-** [comment]
@vferretti @luclemo 

Ca sembler rouler la. Quelques ajustements que j'ai du faire:
- Fixer des erreurs de syntax dans le fichier d'Alex
- Changer les submitterSampleIds pour des valeurs existantes dans notre jeu de donnee
- Changer les etudes pour des valeurs existantes dans notre jeu de donnee

**Comment by Magnitus-** [comment]
Ca fait environ 35 etudes a date pour le meme nombre de minutes, donc environ 1 minute par etude pour uploader.
