### ISSUE TITLE
Impact VEP = HIGH pour une conséquence "Synonymous" 

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#218]
Le variant 01E0E03A4FCE60DA95477E748B97AA29
a une conséquence "Synonymous" avec un impact VEP = HIGH  ce qui ne respecte pas la classification VEP définie à 
https://useast.ensembl.org/info/genome/variation/prediction/predicted_data.html#consequences

![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/453ae24c-c6e6-4229-a151-5b2d84dab8be)

**Comment by latch2112** [comment]
Internal data structure for 01E0E03A4FCE60DA95477E748B97AA29:
https://jsoneditoronline.org/#right=cloud.a70db257ec434ab8b449f9b1d9d1dc15&left=cloud.c376411b24a14a79911739e3cc51d54e

**Comment by latch2112** [comment]
Donc, la conséquence sur le gêne PFH7 a 2 conséquences:
synonymous_variant et splice_acceptor_variant
On affiche que la première...  Hors VEP considère synonymous_variant comme HIGH
Qu'est-ce qu'on doit faire ici ? afficher les deux ?
@vferretti

**Comment by vferretti** [comment]
On affiche les deux puisqu'Il y en a deux.

**Comment by FrancisRenaud** [comment]
Donc, en résumé, il faut afficher toutes les conséquences ou bien il y a quelque chose de plus particulier à faire? @vferretti @latch2112 

En d'autres termes, si on voulait écrire le titre de façon prescriptive, ça ressemblerait à quoi?

**Comment by vferretti** [comment]
On affiche toutes les conséquences pour un transcript donné. 
à faire aussi dans le tableau de la page de recherche de variant
