### ISSUE TITLE
Recherche par gène

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#219]
### Introduction
L'utilisateur doit être capable de chercher les variants dans un gène ou dans une liste de gènes donnée en saisissant des identifiants.

Phase I: Recherche avec **un seul gène** à la fois c’est-à-dire on ne supportera pas la recherche d’une liste de gène en un premier temps

https://docs.google.com/document/d/1AY0EtRk02QTL-RGTtPqc6Oetw7ACEgfnyv4ORynRhdI/edit

**Comment by latch2112** [comment]
@vferretti @luclemo 
Valider et assigner priorité au issues #233, #234, #235

**Comment by latch2112** [comment]
![image.png](https://images.zenhubusercontent.com/5c59d5e107cc4d6f39e559e4/fd95f0cc-b37d-4d81-a067-bc916e323a5c)

**Comment by latch2112** [comment]
Après revue des critères du document google, 
la requête ES doit implémenter la fonction 'Highlight'
