### ISSUE TITLE
Recherche par gène: mettre à jour la BD de gène et indexer les nouveaux champs dans l'index des variants

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#221]
Dans la page de recherche de variant, on doit pouvoir chercher par les critères suivants. 

Fichier source:  ftp://ftp.ncbi.nih.gov/gene/DATA/GENE_INFO/Mammalia/Homo_sapiens.gene_info.gz

Gene symbol - Colonne = Symbol: 
Gene Ensembl ID - Colonne = Other_designations, champ Ensembl
Gene Aliases - Colonne = Synonyms
Omin ID - Colonne = Other_designations, champ MIN
HGNC ID - Colonne = Other_designations, champ HGNC
NCBI Gene ID - Colonne = GeneID
Gene name - Colonne = Full_name_from_nomenclature_authority

**Comment by latch2112** [comment]
Voici le nouvel object genes:
`"genes": [
    {
      "biotype": "protein_coding",
      "ensemblId": "ENSG00000159363",
      "hgnc": "30213",
      "geneId": "23400",
      "hpo": [
        "Progressive cerebellar ataxia (HP:0002073)",
        "Difficulty walking (HP:0002355)",
        "Aggressive behavior (HP:0000718)",
        "Stooped posture (HP:0025403)",
        "Anarthria (HP:0002425)",
        "Rigidity (HP:0002063)",
        "Tremor (HP:0001337)",
        "Torticollis (HP:0000473)",
        "Rapidly progressive (HP:0003678)",
        "Psychotic episodes (HP:0000725)",
        "EMG: axonal abnormality (HP:0003482)",
        "Facial myokymia (HP:0000317)",
        "Parkinsonism (HP:0001300)",
        "Apathy (HP:0000741)",
        "Leg muscle stiffness (HP:0008969)",
        "Fatigue (HP:0012378)",
        "Lethargy (HP:0001254)",
        "Difficulty in tongue movements (HP:0000183)",
        "Hyposmia (HP:0004409)",
        "Upgaze palsy (HP:0025331)",
        "Postural tremor (HP:0002174)",
        "Progressive extrapyramidal movement disorder (HP:0007153)",
        "Nystagmus (HP:0000639)",
        "Mask-like facies (HP:0000298)",
        "Hyperactive patellar reflex (HP:0007083)",
        "Spastic tetraplegia (HP:0002510)",
        "Vertical supranuclear gaze palsy (HP:0000511)",
        "Spasticity (HP:0001257)",
        "Hypomimic face (HP:0000338)",
        "Hypokinesia (HP:0002375)",
        "Ataxia (HP:0001251)",
        "Muscle weakness (HP:0001324)",
        "Babinski sign (HP:0003487)",
        "Eyelid apraxia (HP:0000658)",
        "Cerebral cortical atrophy (HP:0002120)",
        "Depressivity (HP:0000716)",
        "Fever (HP:0001945)",
        "Hyperreflexia (HP:0001347)",
        "Abnormality of the foot (HP:0001760)",
        "Lingual dystonia (HP:0031008)",
        "Pes cavus (HP:0001761)",
        "Akinesia (HP:0002304)",
        "Dyskinesia (HP:0100660)",
        "Supranuclear gaze palsy (HP:0000605)",
        "Short attention span (HP:0000736)",
        "Progressive pes cavus (HP:0008075)",
        "Hypoplasia of the corpus callosum (HP:0002079)",
        "Progressive spastic paraplegia (HP:0007020)",
        "Hypertonia (HP:0001276)",
        "Diffuse cerebral atrophy (HP:0002506)",
        "Generalized muscle weakness (HP:0003324)",
        "Seizures (HP:0001250)",
        "Myoclonus (HP:0001336)",
        "Cerebellar atrophy (HP:0001272)",
        "Strabismus (HP:0000486)",
        "Cognitive impairment (HP:0100543)",
        "Distal sensory impairment (HP:0002936)",
        "Gait disturbance (HP:0001288)",
        "Parkinsonism with favorable response to dopaminergic medication (HP:0002548)",
        "Horizontal nystagmus (HP:0000666)",
        "Abnormality of finger (HP:0001167)",
        "Blepharospasm (HP:0000643)",
        "Hallucinations (HP:0000738)",
        "Visual hallucinations (HP:0002367)",
        "Spastic paraplegia (HP:0001258)",
        "Sensory axonal neuropathy (HP:0003390)",
        "Oculogyric crisis (HP:0010553)",
        "Bowel incontinence (HP:0002607)",
        "Abnormal caudate nucleus morphology (HP:0002339)",
        "Autosomal recessive inheritance (HP:0000007)",
        "Dysarthria (HP:0001260)",
        "Abnormality of the periventricular white matter (HP:0002518)",
        "Paraparesis (HP:0002385)",
        "Slow saccadic eye movements (HP:0000514)",
        "Postural instability (HP:0002172)",
        "Progressive spastic quadriplegia (HP:0002478)",
        "Anosmia (HP:0000458)",
        "Confusion (HP:0001289)",
        "Dystonia (HP:0001332)",
        "Dementia (HP:0000726)",
        "Hyperreflexia in upper limbs (HP:0007350)",
        "Urinary incontinence (HP:0000020)",
        "Neurogenic bladder (HP:0000011)",
        "Dysphagia (HP:0002015)",
        "Progressive gait ataxia (HP:0007240)",
        "Bradykinesia (HP:0002067)"
      ],
      "omim": ["610513"],
      "orphanet": [
        {
          "dataId": "27024",
          "panel": "Autosomal recessive spastic paraplegia type 78 (Orph:513436)"
        },
        {
          "dataId": "21506",
          "panel": "ATP13A2-related juvenile neuronal ceroid lipofuscinosis (Orph:314632)"
        },
        {
          "dataId": "21249",
          "panel": "Kufor-Rakeb syndrome (Orph:306674)"
        }
      ],
      "alias": [
        "CLN12",
        "HSA9947",
        "PARK9",
        "KRPPD",
        "SPG78"
      ],
      "location": "1p36.13",
      "geneSymbol": "ATP13A2",
      "radboudumc": [
        "Parkinson (Rad:Parkinson)",
        "Movement Disorders (Rad:Movement Disorders)",
        "Mendeloime Gene (Rad:Mendeloime Gene)",
        "Preconception Screening (Rad:Preconception Screening)",
        "Mitochondrial Disorders (Rad:Mitochondrial Disorders)"
      ]
    }`

**Comment by vferretti** [comment]
- Je ne vois pas le Gene name tel que spécifié plus haut.

**Comment by latch2112** [comment]
@vferretti 
Oui, je m'en suis aperçu en travaillant sur la requête ES...
J'ai mis à jour l'index...  (voir lien précédent)

**Comment by latch2112** [comment]
ETL Run...  Index mise a jour sur QA
