### ISSUE TITLE
Recherche par gene: Fournir le design UX

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#223]
Réutiliser la composante actuelle pour la recherche de variants mais en changeant les exemples fournis dans la boîte de recherche 

![image](https://user-images.githubusercontent.com/1181124/77760996-ae565280-700d-11ea-9cbc-a97957969029.png)

**Nouveaux exemples:** BRAF, ENSG00000157764…

**Affichage de la liste des matchs** 
On va suivre l’exemple de ICGC  https://dcc.icgc.org/search/g

**Règles:**

- Toujours afficher le Gene Symbol en première ligne 
- Afficher ensuite une ou plusieurs des champs suivants pour lequel on a un match ou plusieurs matchs

    - Gene Aliases (Afficher que les alias pour lesquels on a un match)
    - Gene Ensembl ID
    - Gene name
    - Omin ID
    - HGNC ID 
    - NCBI Gene ID
- La string qui matche doit être en caractère gras.
- Afficher seulement la liste des 5 premiers résultats 

**Sélection d’un gène ou des genes.** 
Dans la requete on aura un nouvelle pilulle de la forme
Gene = symbol
Ou
Gene = (symbol 1 U symbol 2 U symbol 3)

Quand on ouvre la boite on devrait etre en mesure d’enlever un gene à la fois.

---

## Resources

- [Figma design file](https://www.figma.com/file/Gwd3MdUEBhIf6JbcdUTzly/Clin---Recherche-Par-G%C3%A8ne?node-id=151%3A0) — specifications are in the design file.

**Comment by luclemo** [comment]
Design work is complete:

- [Figma design file](https://www.figma.com/file/Gwd3MdUEBhIf6JbcdUTzly/Clin---Recherche-Par-G%C3%A8ne?node-id=151%3A0) — specifications are in the design file.
