### ISSUE TITLE
Redirection to previous state upon session timeout

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#224]
### Feature

As a user I need to be be redirected to my current state/activity once my session has expired and I login again.

### Acceptance Criteria

**Scenario 1** User is redirected to login screen upon session expiration
  - **Given:** I am successfully logged-into the application
  - **When:** My session expires
  - **Then:** I am redirected to the login screen and I am redirected to previous state upon successful login

**Scenario 2** User is redirected to login screen when copying a link to a page of the app if he's not logged in
  - **Given:** I am not logged-into the application
  - **When:** I copy a link to a page of the application into by browser url bar
  - **Then:** I am redirected to the login screen and I am redirected to appropriate state upon successful login

**Note:** No information other than the global state of the information is preserved if not saved. (e.g. draft filters)

**Comment by nyanofthemoon** [comment]
@luclemo what exactly entails "previous state"?
- the page on which you were (same behavior as actual copy-paste url in the browser)
- keep some things (those things depend on the page)
- keep *everything* on the page (values in fields, etc)

**Comment by luclemo** [comment]
@nyanofthemoon Idéalement ça serait _everything on the page_ (3eme point) parce qu'on ne veut pas créer de frustration d'opération interrompu due au time-out, mais je vais laisser @vferretti confirmer.

**Comment by vferretti** [comment]
Quand une session expire, on voudrait 1) être diriger vers la page login et 2) après s’être loguer, être diriger vers la page où on voulait aller. Je crois que c'est relativement facile lorsque la page où on veut aller a un URL précis. 

Si on est dans la page de recherche de variants avec des filtres actifs et que la session expire, on a en ce moment le comportement suivant: 
- si on rajoute un critère de recherche, celui est rajouté dans la requete active mais aucune requête n'est effectuée et ce, sans avertissement à l'utilisateur. 
On voudrait idéalement que l'utilisateur soir redirigé à la page login, se logue et soit redirigé de nouveau vers la page de recherche  avec une des trois options suivantes: 
-- le nouveau critère de recherche est appliqué 
-- Le nouveau critère de recherche n'est pas appliqué mais on retrouve la page de recherche dans l'état où elle se trouvait avant l'expiration de la session.
-- on retrouve la page de recherche de variants 'vierge' comme si on arrivait d'une page patient ordinaire. Tout le travail fait avant l'expiration de la session serait perdue. 
Je suis correct avec l'option 3 si c'est plus simple. Mais il faudra rallonger le temps d'une session (un autre ticket)

- De la page de recherche de variant, on a un  comportement bizarre lorsqu'on clique sur le lien Patients dans l’entête. On obtient une liste vide de patients. Ce qu'il faut, c'est de pouvoir se reloguer et être redirigé vers la page de recherche de patients correctement affichée.

J'espère que ca aide. On peut en discuter si plus simple.

**Comment by denis-crsj** [comment]
@FrancisRenaud @luclemo Bonjour messieurs, j'aimerais tester cette tâche mais j'aurais besoin d'un peu de détails. Basé sur la chaine de commentaire et les 3 options proposées par Vincent, laquelle a été programmée au final ?

Aussi, j'aurais besoin de savoir quel est le délais pour le session time question de savoir combien de temps je dois laisser la session inactive.
