### ISSUE TITLE
Create 401 page for access denial

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#229]
### Feature

As a user I should be given clear messaging and redirection options when I attempt to access content for which I am not authorized.

### Acceptance Criteria

**Scenario:** User reaches a denied access area (error 403)
  - **Given:** I have successfully logged into the app
  - **When:** I navigate to a given URL
    - **And:** I do not have adequate user permissions to access the content
  - **Then:** I am redirected to an "access denied" page
    - **And:** I can click on the CTA button _or_ the back button in browser to go back to the previous page

#### Notes

If it is complicated to code the button with the user's previous URL, then simply use it to redirect to the patient list page. In that case, the button text should be changed appropriately to: `Retourner à la liste de patients`.

### Resources

- [Figma design file](https://www.figma.com/file/37C8rvzqMasIK0zT9n3Mls/Alerts-%26-Errors?node-id=252%3A4586)

**Comment by nyanofthemoon** [comment]
@luclemo we could also address fixing the "flash of content of the login page" when copy-pasting an url for a logged in user with this.

**Comment by nyanofthemoon** [comment]
@luclemo Can I keep the existing information in the header and footer ? I just want to make sure we're on the same page (since it's not there in the design):

![image.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/ccaa3447-df58-46c1-8732-54ce9ffbf9e1)

**Comment by luclemo** [comment]
Yes 100%, I was just saving time by not including repeated elements :)

**Comment by nyanofthemoon** [comment]
Cool ;) I think I can come up with something to "go back to previous page" using the browser history api :)

**Comment by nyanofthemoon** [comment]
@luclemo @vferretti We do not currently have a way to differenciate between:
- "404" entity does not exist
- "403" entity exists but you don't have the rights to see it
- "200" empty result set due to either 404 or 403 as described

I will thus implement this request as:
- if going to a patient page (with a patient id) and we get an empty result, you get the 403 page
- if going to a variant page (with a variant id) and we get an empty result, you get the 403 page
- if going to any other "non-entity" page, you cannot get the 403 page

**Comment by nyanofthemoon** [comment]
@claudia1296 Functionality done on branch `feat/229-access-denied-page`; the stylin' is all yours! :)

**Comment by nyanofthemoon** [comment]
Pull request as a WIP here : https://github.com/cr-ste-justine/clin-frontend/pull/199

**Comment by nyanofthemoon** [comment]
@claudia1296 Page created and functionality done. Soon to be merged unto dev branch.

**Comment by luclemo** [comment]
@nyanofthemoon J'essaye de valider le travail de @claudia1296 avec les infos qu'elle m'a donné mais j'ai un redirect bizarre.

Problem: http://recordit.co/iMSjN7uScg

Login info:
`practitioner@cr-ste-justine.xyz`
`qwerty123`

URL to test:
`https://clin.cr-ste-justine.xyz/patient/PA14909`

**Comment by denis-crsj** [comment]
Impossible d'accéder à la page actuellement. De toute façon, il n'y a aucune gestion de permissions pour le moment. Page complété par contre alors on pourra la revalider une fois rendu à implémenter la gestion des permissions
