### ISSUE TITLE
Téléchargement des fichiers

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#230]
Cette épic regroupe les billets en lien avec le téléchargement des fichiers génomiques à partir de l'interface web

**Comment by latch2112** [comment]
@luclemo @vferretti 
Svp, inclure une tâche de documentation technique de Overture (Song et Score) et de son implication au sein de Clin afin de compléter les tickets dans cet épique
Le projet Overture est potentiellement composé des repos suivant:

- https://github.com/cr-ste-justine/overture-dev
- https://github.com/cr-ste-justine/overture-dev-clin
- https://github.com/cr-ste-justine/score
- https://github.com/cr-ste-justine/SONG
- https://github.com/cr-ste-justine/song-auth
- https://github.com/cr-ste-justine/score-auth
- https://github.com/cr-ste-justine/overture-id-service
- https://github.com/cr-ste-justine/song-metadata-resolver
- https://github.com/cr-ste-justine/clin-overture-client
- https://github.com/cr-ste-justine/overture-python-sdk
- https://github.com/cr-ste-justine/node-functional-utils
- https://github.com/cr-ste-justine/node-configs
- https://github.com/cr-ste-justine/node-jwt
- https://github.com/cr-ste-justine/clin-external-proxy
- https://github.com/cr-ste-justine/clin-overture-schemas

Donc il possède plus de repos que le projet Clin lui-même et donc, réaliser cet épique peut être considéré comme ardu voir accablant

**Comment by vferretti** [comment]
Me demande bien pourquoi il y a autant de répertoires...

**Comment by Magnitus-** [comment]
Pour clin, le repo qui devrait etre suivi et compris est le suivant: https://github.com/cr-ste-justine/overture-dev-clin

Et possiblement lui: https://github.com/cr-ste-justine/overture-dev

Les autres repos peuvent etre consultes au besoin, mais ne sont pas necessaires pour rentrer dans le projet initialement.

**Comment by nyanofthemoon** [comment]
@vferretti Je viens de réviser tous les services et le 3/4 ont avait déjà l'équivalent, mais @Magnitus- a refusé dur comme fer de ré-utiliser ce l'équipe avait déjà fait.

**Comment by vferretti** [comment]
bon bon, je vais essayer de comprendre tout ca la semaine prochaine. Je ne sais pas trop de quoi vous parlez honnêtement, je n'ai pas suivi. Merci
