### ISSUE TITLE
 Clin Qa no longer Work on Firefox

### ISSUE THREAD

**Issue by latch2112** [Ferlab-Ste-Justine/clin-project#232]
### Steps to Reproduce

1. Go to https://clin.cr-ste-justine.xyz/ on firefox 74.0

### Expected behavior

showing login page

### What happens instead

blank page
### Screenshots

![image.png](https://images.zenhubusercontent.com/5c59d5e107cc4d6f39e559e4/56444cc5-50d8-4a98-b8a8-6a51ed088c24)A clear and concise description of what the bug is.

**Comment by vferretti** [comment]
J'obtiens une page blanche avec Firefox avec l'adresse clin.ferlab.bio

**Comment by denis-crsj** [comment]
Le problème semble résolu, j'ai réussi à afficher le site dans Firefox sans problème et j'ai réussi à me connecter
