### ISSUE TITLE
Recherche par gène: Implémenter le composant UI

### ISSUE THREAD

**Issue by latch2112** [Ferlab-Ste-Justine/clin-project#234]
Le composant UI doit être en mesure de contacter le service backend de recherche par gènes

Il affichera seulement les 5 premiers résultats.

Ensuite, le même composant doit être en mesure de consommer le service de recherche de variants...

Lorsqu’on sélectionne un gène, le critère est ajouté à la requête active de la page de recherche de variants et la liste des variants se rafraîchit.

On peut ajouter plusieurs gène dans la requête. On a alors un OU entre les gènes. Comme dans cet exemple du portail de ICGC:

**Comment by luclemo** [comment]
Design specs as per #223 are complete:
- [Figma design file](https://www.figma.com/file/Gwd3MdUEBhIf6JbcdUTzly/Clin---Recherche-Par-G%C3%A8ne?node-id=151%3A0) — specifications are re-iterated as notes inside the design file.

**Comment by vferretti** [comment]
Faire uniquement le UI sans le connecter a aucune action sur le sqon, le temps d'implémenter les tests en cours de définition

**Comment by nyanofthemoon** [comment]
@latch2112 Will need to discuss your comment soon so that I can understand what I am to implement.

**Comment by nyanofthemoon** [comment]
@claudia1296 SQON format to send to clin-proxy-api plz:

`{
    type: 'autocomplete',
    data: {
        id: 'gene_symbol',
        subtype: {
            type: 'generic',
            operand: 'one'
        }
        query: 'BRA',
        matches: ['BRAA', 'BRAF', 'BRAZ'],
        selection: ['BRAF']
    }
}`

`query` is the text searched
`matches` are the results returned for the text searched
`selection` are the selected results to apply to the query for variant search

**Comment by nyanofthemoon** [comment]
As per @latch2112, we should get rid of `matches` and `query` when saving the statement queries if we do not not need this information as it could be quite voluminous!

**Comment by latch2112** [comment]
yeah...  I think that only the selection is necessary...  if we want to change, we need to remove it and do another search (from the spec I saw on Figma)

**Comment by denis-crsj** [comment]
Tested
