### ISSUE TITLE
Recherche par gène: Implémenter le service de recherche de variants par gènes

### ISSUE THREAD

**Issue by latch2112** [Ferlab-Ste-Justine/clin-project#235]
Lorsqu’on sélectionne un gène, le critère est ajouté à la requête active de la page de recherche de variants et la liste des variants se rafraîchit.

On peut ajouter plusieurs gène dans la requête. On a alors un OU entre les gènes. 

Le service variant doit donc être en mesure de faire la recherche de ceux-ci sur des gènes symbol

**Comment by vferretti** [comment]
Je ne comprends pas ce que tu veux qu'on valide. 
Aussi, c'est écrit plus haut que la recherche va se faire sur le gene symbol

**Comment by latch2112** [comment]
Ces commentaires s'adressent au dévelopeur, sinon, j'aurais mentionner un nom de personne...
En effet, la structure interne du SQON fonctionne avec un 'schema' et le dev doit s'assurer qu'on puisse ne pas avoir de facette associer sinon le front-end et ou le service backend va briser...  
Le deuxième commentaire fait référence au champs de recherche du schema pour aider à guider le dev...

**Comment by nyanofthemoon** [comment]
@vferretti @luclemo This requires a major refactor of the SQON schema and its mapper.

**Comment by vferretti** [comment]
@nyanofthemoon peux-tu stp être plus précise?

**Comment by nyanofthemoon** [comment]
@vferretti Without going into the specifics of technicals, our current schema and mapper do not support fields of type without aggregation; it is a new concept and needs to be implemented in a fashion which will not break everything we have so far. For reference:

![image.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/0e46ccca-971b-4296-8643-19b31551e66b)

**Comment by nyanofthemoon** [comment]
@vferretti ![image.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/4832177c-d7c0-445c-aead-50eb4d8bf456)

**Comment by nyanofthemoon** [comment]
@latch2112 The schema does not permit "non-facetted" menu items (like visual menu items with async functionality etc). I am currently weighting the pros and cons between various possible implementations in regards to "flexibly" vs "fast to code" vs "developer friendly" for the updated schema structure. I think everyone wants this to remain as self-explanatory and easy to understand for the next developer that will come in contact with this part of the project.

**Comment by latch2112** [comment]
agree

**Comment by nyanofthemoon** [comment]
@latch2112 Yes, I really can't find any arguments to justify a corner solution. This is going to have a massive effect on both the SQON -> ES dialect mapper as well as the frontend facet-navigation code and its associated filter components. TDD is the right tool for this job.

**Comment by latch2112** [comment]
Excellent, j'étais pas trop dans le champs :smiley:

**Comment by vferretti** [comment]
Please provide a short technical summary of the work to do and an estimation of the effort (time).

**Comment by nyanofthemoon** [comment]
@vferretti Please note that this only pertains to the "backend" side of things:

Tasks required before starting development:
- unit tests to validate the existing SQON to Elastic Search mapper
-- need to define which test cases require to be written as unit tests
-- critical for validating that the new code retains the expected behaviour
- functional tests against the relevant proxy-api REST endpoints (variant and gene)
-- need to define which test cases require to be written as functional tests
-- critical for validating that the service chain retains the expected behaviour

Tasks relevant to the development of this new feature:
- finishing initial investigation work to define possible solutions
-- includes having a look at the feasability of those solutions with the frontend part
- development of the selected solution using TDD

Estimate:
No meaningful estimate can be provided at this point.

An equivalent investigation and scenario is to be expected for the "frontend", I will get to that once I make it to ticket #234.

**Comment by latch2112** [comment]
@vferretti Ce composant est également nécessaire pour la recherche de variant par identifiant; comportement similaire

**Comment by vferretti** [comment]
@nyanofthemoon combien ca prendrait de temps pour faire les units et le fonctionnal tests?

**Comment by nyanofthemoon** [comment]
@vferretti I just had a look at the test matrix written by @latch2112.

This is not a list of exact tests (like how many SNV for patient X); it is a list of test categories.

I do not know which of these categories are more critical than others and I also do not know the business significance of those tests nor of their result sets.

For this reason, I cannot provide an estimate.

**Comment by vferretti** [comment]
Je comprends qu'il s'agit d'un composant nouveau et qu'il faut ajuster le shema et toute la mécanique pour le plugger au reste. Ce que je comprends moins, c'est en quoi le champ Gene_symbol dans l'index est different des autres quand on le met dans un SQON. Est-ce qu'il ne s'agit pas simplement d'ajouter un terme au SQON du genre where variant ... .gene symbol = xx comme on le fait pour les autres champs?

**Comment by nyanofthemoon** [comment]
@vferretti The frontend "facet navigation" is populated using a JSON definition schema (similar strategy to kids-first). That schema defines (again, similar to kids-first) what is queried, where it is queries and how it is queried. In addition to that (also similar but a simplified version of kids-first), each of these definitions are defined (by their type: generic, composite, etc) visually in the frontend through React components.

The complexity lies with the ingredients, not the sauce.

**Comment by vferretti** [comment]
Je comprends tout ca. Mais je ne comprends pas pourquoi, à part le fait qu'on sélectionne différemment le critère de recherche (avec un text box) et donc qu'il faut coder ce nouveau composant, la recherche avec le sqon est si différente qu'il faille implémenter tous les tests avant. 
Autrement dit, si on avait à ajouter un autre multi-selection générique, est-ce que ca aurait été aussi risqué pour le sqon et la recherche?

**Comment by nyanofthemoon** [comment]
@vferretti If we needed another kind of component that is a "facet-like" query, we would probably only need to create a new React component. However, right now, _we do not support anything but facet searchable fields_ (things that are defined as an aggregation in ElasticSearch). Gene symbol is an autocomplete search (something found using a fragment of itself) which is a completely different concept that possibly introduces many changes in the existing code, which, my human mind cannot predict all of the possible bugs.

**Comment by vferretti** [comment]
Can we code it outside of the framework? Would it be simpler to make it specific and not generic? Actually, at some point  (much later), we will want to have the expend this component to upload a list of gene symbols like in ICGC and GDC. This represents something even more specific. In KF, they are UI components that are not managed by Arranger. Can we make an exception for this one? would it help. We don't absolutely need a generic solution. What do you think?

**Comment by latch2112** [comment]
Ah!  c'est de la broche à foin que tu veux !!!

**Comment by vferretti** [comment]
pas nécessairement. si c'est spécifique, c'est spécifique. Je veux pas qu'on tombe dans le piège de faire une solution générique qui coute cher pour une seule composante super spécifique.

**Comment by nyanofthemoon** [comment]
@vferretti We have a very flexible and lightweight solution. New functionality will not appear out of thin air, they need to be coded. We will be able to upload a list of genes later on, that is not a blocked.

I pride myself in my work- especially in my open-source work. I have cut corners several times for this project already- so much that there are no tests whatsoever. The codebase is getting bigger and more and more bugs are being introduced lately.

For this reason, no.

**Comment by latch2112** [comment]
Et c'est pas un composant spécifique, c'est un composant qui permet de faire de la recherche sur des identifiants tel que variant id, gene symbol, etc...

**Comment by vferretti** [comment]
I appreciate you are proud of you work and won't ask for something that would spoiled it. That's not my intend. I am just trying to understand the issues and discuss options. 
But again, I need to have an estimate of the effort of your plan to prioritize tasks. This is a normal request.

**Comment by nyanofthemoon** [comment]
@vferretti Once again, there are over 1,000 tests to write. Even if it (which it won't) took me 1 hour per test, it would take me 1,000 hours to write all of them.

I do not not have the business knowledge to know, for each of those tests cases, what is the meaning of the "input" not what the expected "output" is. Nobody has validated the data yet. Therefore I cannot write nor estimate something that I do not have knowledge over.

**Comment by vferretti** [comment]
@nyanofthemoon Would like to take a pause on development and start implementing tests? I asked you the questions when you came back from vacation and this is why the only tickets I left on github were the one for tests. I also prioritize one  the ticket you asked this week.

**Comment by vferretti** [comment]
Donc, pour faire la recherche par gene, il est recommandé d'implémenter la matrice de tests avant et il y en a mille à faire et on ne sait pas trop comment, donc on est bloqué. C'est ca?

**Comment by latch2112** [comment]
Oui.  La matrice des tests se trouve ici:
https://docs.google.com/spreadsheets/d/1RSjmjHFgoJujEeiUL8uvynfci874cOeNJZDzbwcaNrg/edit?usp=sharing
Je te recommande d'écrire sous forme de ticket ces tests et de nous donner les paramètres d'entré et le résultat attendu; 
Par exemple: Tel que Alex DL avait fait pour moi pour la transmission génétique

**Comment by latch2112** [comment]
Un exemple de test est: 
Si on sélectionne le type de variant 'SNV' pour le patient PA00002, il devrait y avoir x conséquence, y valeur omim
etc...  Ici le test précédent énumère le composant générique avec le composant booléen

**Comment by vferretti** [comment]
Je comprends que c'est mieux d'avoir des tests surtout dans une application aussi complexe et en fait je serais très rassuré d'en avoir. Je pense par contre qu'il n'est pas raisonnable de demander de définir et d'implémenter des centaines de tests. @latch2112 Tu ne trouves pas?

**Comment by latch2112** [comment]
Comme @nyanofthemoon a dit tantôt, on ne sait pas lesquels sont les plus critiques...
Par contre, en TDD c'est important de tous faire les tests car sinon ceux qui ne sont pas couvert risque de passé jusqu'en production.  Par contre puisque c'est toi qui a une meilleure compréhension du domaine, c'est à toi ou un autre SME de nous envoyer la liste des tests que tu juges critiques/prioritaires ce qui va déterminer la marge potentiel d'erreur acceptable.

Par exemple, pour la transmission génétique, j'ai codé 100% des cas car nous voulions toutes les transmissions possibles.

**Comment by vferretti** [comment]
Je pense qu'on mélange les issues. Pour le moment, on a peur de briser qq chose en rajoutant la recherche par gène. Ce qu'il faudrait, c'est un moyen de voir si on obtient les memes résultats avant et après l'implémentation de la recherche par gène, un peu comme si on avait 2 portails, un avec et un sans la recherche par gène.

**Comment by latch2112** [comment]
Pas tout à fait. On implémente une nouvelle recherche qui va avoir des impacts sur la recherche précédente...  Comment on fait pour valider le nouveau résultat et l'ancien puisque ni un ni l'autre contient les mêmes paramètres de recherches ?
Avant, ancien portails, pas de recherche par gêne donc pas possible de déterminer si la recherche par gène affecte les résultats ...  Et, un screenshot nous permettra pas de déterminer quelle partie du code a été brisé.  Quand on code des tests, ceux-ci sont exécuté au fur et à mesure de la progression du dévelopement de celui-ci.

**Comment by latch2112** [comment]
On as codé la partie précédente sans tests dans l'optique de pouvoir faire un démo de l'application; donc démontré son application et non sa validité. Maintenant, il est de nôtre devoir de valider ses résultats puisse que ce système sera utilisé en clinique afin poser un diagnostique

**Comment by latch2112** [comment]
Aussi, lors de l'écriture des tests, on vas également valider le spectre possible des gênes que nous pourrons trouvés avec l'aides des composants précédents.

**Comment by vferretti** [comment]
je veux bien faire des tests, je n'ai rien contre ca au contraire, je suis d'accord avec vous contrairement à ce que vous pensez. C'est juste que c'est irréaliste de penser qu'on va implementer mille tests pour toutes les combinaisons possibles. Il faut une stratégie pour les choisir plus intelligemment. je crois que Arranger en a entre 50 et 100 pour les requêtes. C'est plus réaliste.

**Comment by latch2112** [comment]
Excellent, ça revient au commentaire de @nyanofthemoon qui mentionnait vouloir connaître lesquels sont prioritaire

**Comment by nyanofthemoon** [comment]
The unit tests related to the SQON -> ES dialect mapper have been implemented. Please not that they do not validate the actual data returned by the mapped queries!

I believe we need to implement functional testing on the variant proxy api service ASAP, but no "valid dataset" to test against is unavailable at the time of this writing, so I am moving on to this feature ticket.
