### ISSUE TITLE
Page header redesign — patient info

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#247]
### Goal

Only include necessary patient details in the page header in order to reduce vertical space:

**Line 1:**

- Patient Name
- Gender
- RAMQ 
- Proband / Parent tag
- Family

**Line 2:**

- HPO

### Resources

_Include any links to additional documentation, technical and/or design specs_

**Comment by denis-crsj** [comment]
Cette carte est toujours d'actualité mais les critères seront à revoir. Je déplace la carte temporairement dans Notion et on pourra y revenir lorsque les specs auront été mises à jour.
