### ISSUE TITLE
Définir les specifications techniques pour téléchargement des fichiers génomiques

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#249]
Voici un premier jets des specifications fonctionnelles (et un peu technique) sur le téléchargement des fichiers. La tâche consiste à définir les spécifications techniques de la fonctionnalité avant son implémentation. 

https://docs.google.com/document/d/1L0ezK7VSwCI0RfqnASFs5uvxTnWUzi9EvtA7eQ0x7qw/edit#

**Comment by latch2112** [comment]
J'ai pris conscience du document google, valider et mise à jour l'aspect technique de celui-ci.
La prochaine étape consiste à convertir ce document en Épique si c'est pas déjà fait et écrire les histoires qui lui sont rattachés.
