### ISSUE TITLE
Index variant_centric et gene_centric, supprimer la repetition de Radboudumc

### ISSUE THREAD

**Issue by Emma-Drieux** [Ferlab-Ste-Justine/clin-project#251]
Exemple:
"radboudumc" : [
          "Mendeloime Gene (Rad:Mendeloime Gene)",
          "Preconception Screening (Rad:Preconception Screening)",
          "Hemostatic/Thrombotic (Rad:Hemostatic/Thrombotic)"
        ]
Pour "Mendeloime Gene (Rad:Mendeloime Gene)", ne mettre que "Mendeloime Gene"

**Comment by latch2112** [comment]
ETL run... index mise a jour
![image.png](https://images.zenhubusercontent.com/5c59d5e107cc4d6f39e559e4/66f97410-04c1-4b6e-9d49-5ec51591e496)
