### ISSUE TITLE
 Annotation OMIM: indexer les phenotypes OMIM dans l’index variant

### ISSUE THREAD

**Issue by Emma-Drieux** [Ferlab-Ste-Justine/clin-project#252]
## Objectif: 
Ajouter les informations contenues dans la base de données d'OMIM

**Voir specification**
https://docs.google.com/document/d/1UlYI-Eqtvj9wDmBx7nUvdSFRfWtKDa1MhZ8u-luPPeA/edit#

Dans le document cité ci-dessus, se référer aux parties suivantes:
- Données a rajouter dans l'index mutation_centric: **Implementation/Index/modification de l'index mutation_centric**
- Source des données: **Implementation/Source des données**

Tasks:
- [x] Change cellbase to include index for gene MIM
- [x] populate cellbase with the gene MIM
- [x] extract "Omim phenotype data"
- [x] make the join with the MIM Number of cellbase
- [x] populate cellbase with new Omim phenotype data
- [x] Index cellbase in ES
- [x] Write ETL rule for variants index

**Comment by latch2112** [comment]
changement de notre cellbase pour être en mesure de faire de la recherche par gene MIM number

**Comment by latch2112** [comment]
@Emma-Drieux Merci pour l'analyse dans le google doc mais je veux te laisser savoir qu'il existe beaucoup plus que trois cas de figure, les données présentent peuvent se trouver dans n'importe quel ordre ainsi que le phenotype peut posséder plusieurs mode de transmissions; autrement dit, il ne suit pas une logique.

**Comment by latch2112** [comment]
Next step will be to extract "Omim phenotype data"

**Comment by latch2112** [comment]
Next step: make the join with the MIM Number

From specification:
> La valeur genemap2.txt/MIM Number permettra de faire la jointure avec le mim number obtenu avec le fichier NCBI
