### ISSUE TITLE
Index- mutation_centric: Insérer la position de l'exon

### ISSUE THREAD

**Issue by Emma-Drieux** [Ferlab-Ste-Justine/clin-project#253]
Insérer la position de l'exon dans les donnees générales dans variant_centric (ex. 2/7)
_Source: a partir du fichier vcf d'annotation - champ INFO ID=CSQ, EXON_

**Comment by latch2112** [comment]
Adding code for loading exon
test
changing index structure to include exon
test
dry run and test
run ETL

**Comment by latch2112** [comment]
bonne nouvelle: on as pas besoin de changer la ligne de commande VEP !

**Comment by latch2112** [comment]
nouvelle structure :

consequences.transcripts.exon (0..n . 1..n . 0..n)

example:
`{
              "biotype" : "protein_coding",
              "conservationsScores" : {
                "PhyloP17Way" : 0.03119
              },
              "geneAffectedId" : "ENSG00000105483",
              "consequence" : [
                "missense_variant"
              ],
              "strand" : -1,
              "transcripts" : [
                {
                  "featureType" : "Transcript",
                  "canonical" : false,
                  "exon" : "3/11",
                  "featureId" : "ENST00000391898"
                },
                {
                  "featureType" : "Transcript",
                  "canonical" : false,
                  "refSeqId" : "NM_001351782.1",
                  "exon" : "7/15",
                  "featureId" : "ENST00000519940"
                },
                {
                  "featureType" : "Transcript",
                  "canonical" : false,
                  "refSeqId" : "NM_001184903.1",
                  "exon" : "4/11",
                  "featureId" : "ENST00000520015"
                },
                {
                  "featureType" : "Transcript",
                  "canonical" : false,
                  "refSeqId" : "NM_001351791.1&NM_001351788.1&NM_001351789.1&NM_001351792.1&NM_001351790.1&NM_001184902.1",
                  "exon" : "6/13",
                  "featureId" : "ENST00000520753"
                }
              ],
              "impact" : "MODERATE",
              "geneAffectedSymbol" : "CARD8",
              "aaChange" : "F102I",
              "predictions" : {
                "FATHMM" : "TOLERATED",
                "CADD_score" : 0.03797,
                "SIFT" : "DAMAGING",
                "DANN_score" : 0.16412,
                "FATHMM_score" : 0.19311,
                "SIFT_score" : 0.91255,
                "Polyphen2_HVAR_score" : 0.25278,
                "REVEL_score" : 0.05495
              },
              "cdnaChange" : "304A>T"
            },`
