### ISSUE TITLE
Annotation OMIM

### ISSUE THREAD

**Issue by Emma-Drieux** [Ferlab-Ste-Justine/clin-project#254]
Voir specification 
https://docs.google.com/document/d/1UlYI-Eqtvj9wDmBx7nUvdSFRfWtKDa1MhZ8u-luPPeA/edit#

**Comment by latch2112** [comment]
Ceci a l'envergure d'un épique.  Il doit être briser en morceaux avec un SME (Subject Matter Expert) ainsi que les architectes du système.

**Comment by Emma-Drieux** [comment]
Tu penses a quoi comme morceaux? on avait mis les champs a rajouter dans l'index mutation_centric dans le ticket https://github.com/cr-ste-justine/clin-project/issues/252 il faut rajouter quoi en plus? (on a mis un tableau dans le doc avec le contenu qu'on aimerait afficher, faudra peut etre donner la maquette pour Claudia j'imagine)

**Comment by Emma-Drieux** [comment]
Au pire, on pourrait en discuter, tu me diras ce qu'il faut mettre comme strories pour cet epic
