### ISSUE TITLE
Index Patient.container

### ISSUE THREAD

**Issue by Emma-Drieux** [Ferlab-Ste-Justine/clin-project#255]
Dans Index Patient_centric, source specimen, peut etre mettre container dans la liste des identifiants

**Comment by latch2112** [comment]
peut être ?
svp, fournir la source des données

**Comment by Emma-Drieux** [comment]
Oui pour l'instant c'est juste une idée rien de sur, je le mets pour ne pas l'oublier..
C'est dans Index Patient.specimens.container. Ce champ représente l'id de l'échantillon au niveau du laboratoire (external id), ce n'est pas évident de faire le lien entre le champ et ce qu'il represente

**Comment by denis-crsj** [comment]
@Emma-Drieux Qui peut valider ces changements ?

**Comment by Emma-Drieux** [comment]
C'est deja fait, mais on attendra d'avoir les nouvelles modifs du modeles avant de valider ;)

**Comment by denis-crsj** [comment]
Après discussion avec Emma, les modifications qui sont présentement en cours pour le modèle FHIR invalident cette carte.
