### ISSUE TITLE
Integrate a CI/CD environment to CLIN

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#256]
You could consider as well cloud services such as  https://www.cloudbees.com/ or https://circleci.com/ or others. 

The rational being that 1) Collab is a temporary solution and 2) we still don't know what our environments will look like when we move with the government infrastructure.

**Comment by latch2112** [comment]
Whatever the choice; the goal is to be able to create and teardown a subset of the Clin System; 
All the ETLs need to be executed after the creation so that we can execute functional tests against.
We can create environment on the fly or within a timeframe (like daily); GitHub's push will initiate its test against that environment.  
So ETL will teardown and create a new environment or sub-environment, etc...
For this to be successful, we need a 'Control' (for Clin) I mean, a patient or a trio, it's genetics control files and variants; and 3 users (practitioner, geneticist and an admin) It can be a subset of what we currently have...  We should write test against the control and we should always expect the same result from change to change (unless specification changed; in that case, the tests need to be modified to reflect the new specifications)

**Comment by latch2112** [comment]
Another easy solution will be to use a very small cluster on Collab and build the entire script to create and teardown the equivalent of current Clin-QA.  We could put an Apache Airflow on top to execute the various ETLs and scripts needed to populate the control. 
Github have the concept of actions that can initiate a workflow after a push or anything else... We should look into these to keep tooling to minimum.

**Comment by latch2112** [comment]
https://github.com/features/actions

**Comment by latch2112** [comment]
Good news...
From Github action pages...

> You can use a runner hosted by GitHub or host your own runner. A runner waits for available jobs. When a runner picks up a job, it runs the job's actions and reports the progress, logs, and final results back to GitHub. Runners run one job at a time.

**Comment by latch2112** [comment]
I move this epic up in priority because we need a CI/CD to be able to run the functional test which block feature like Recherche par gène...

**Comment by latch2112** [comment]
@nyanofthemoon @Magnitus- 
Ceci est l'épique du CI/CD...  C'est pour vous garder dans le loop

**Comment by Magnitus-** [comment]
@latch2112 
So basically, it's Gitlab CI for Github. Sounds like a logical choice. 

If we can have our own runners, than we can move sensitive test data there which solves that problem.

Lets just make sure that the multi-container orchestration (which really is what we after for integration tests) is robust. In Onespan, I ended up having to implement my own ad-hoc solution for that (launching multiple containers from the container the test ran on) which was less than ideal (in situations where the pipeline fails for example). Its better if management of a fleet of containers (ex: the docker-compose up/down) is intrinsic to the framework.

I'm not familiar with the details of Apache Airflow, though I've heard the name on occasion.

**Comment by Magnitus-** [comment]
@latch2112 @nyanofthemoon 
Also, separately, especially as the system grows, I would try to also write more isolated functional tests around mostly self-contained core features if possible.

If we boot the entirety of clin from each repo, we might encounter some performance issues (not to mention the logistic of determining which versions of the components to run). 

It think it makes sense to have orchestration repos to trigger integration tests for various components.

For Overture with clin for example, I have this orchestration repo: https://github.com/cr-ste-justine/overture-dev-clin

I would trigger the overture integration tests only when that repo changes and I would not run clin in its entirety. I just need the overture stack + keycloak + elasticsearch + the patient index.

@vferretti

**Comment by Magnitus-** [comment]
Also, separately from testing, I would leverage the pipelines to do the following:

- Build and push images (can be done from each repo, semantic versioning needs to be enforced, you can't override an existing tag with a new image)
- Deployments (triggered when orchestration repos change).

**Comment by latch2112** [comment]
From Github action:

> We recommend that you do not use self-hosted runners with public repositories.
> 
> Forks of your public repository can potentially run dangerous code on your self-hosted runner machine by creating a pull request that executes the code in a workflow.

**Comment by Magnitus-** [comment]
We can circumvent that by making private prod-like orchestration repos and run our integration tests on those.

Anyways, if we need private test data...

**Comment by latch2112** [comment]
Oui.

Donc l'investigation sur l'utilisation des actions GitHub est concluente; Il s'avère être un excellent outil pour développer notre CI/CD.

La prochaine étape est d'arrivé avec un plan de développement du CI/CD

**Comment by latch2112** [comment]
Voici le plan initial:  https://docs.google.com/document/d/14xr6CVn4vK_J-OtecAgJLXUk3qgPVINWh2wvEmGr4oE/edit

@Magnitus- Il faudrait rajouter la partie SONG et SCORE dans le plan...  j'ai vu la doc préliminaire mais tu connais plus que moi les étapes ainsi que les actions à exécuter sur chacun de tes repos.

**Comment by latch2112** [comment]
Prochaine étape...  Faire les tickets du plan après révision
