### ISSUE TITLE
changer l'affichage des publication PudMed

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#258]
Dans la page Variant et dans la page de Recherche de variant, on affiche la liste des publications sous la forme d'une liste de Pubmed IDs. Étant donnée qu'il peut y en avoir beaucoup (ce qui est une surprise), on va changer l'affichage. 

Afficher le nombre de publications sous le format: n où n est le nombre de publications.

Mettre un hyperlien sur le nombre de publications
Si n = 1 le lien est https://www.ncbi.nlm.nih.gov/pubmed/<bdExt.pubmed[0]>
Exemple: https://www.ncbi.nlm.nih.gov/pubmed/25157968/

Si n > 1 le lien est de la forme 
https://www.ncbi.nlm.nih.gov/pubmed?term=<bdExt.pubmed[0]>+<bdExt.pubmed[1]>+ … + <bdExt.pubmed[n-1]>[uid]
Exemple: https://www.ncbi.nlm.nih.gov/pubmed?term=23317446+22735384+20818844+20551065+25157968+22356324+14679157+22972589+21639808+22663011+23020132+20630094+22608338+12068308+22048237+22805292[uid]

**Comment by luclemo** [comment]
@claudia1296 @vferretti Pour l'affichage, je propose un simple lien comme ceci `17 Publications` où le `n` = le nombres de publications, mais le tout est un lien.

J'ai mis à jour la maquette de la page de variant, mais voici un screenshot.

![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/e1c025b7-b465-4306-ae3d-756ad089dc44)

On fait la même chose pour le tableau.

**Comment by luclemo** [comment]
S'il `n` = 0, on reste cohérent avec les autres composantes et on affiche: `--`
