### ISSUE TITLE
Remove pagination from multi-select facets in query builder (Specific filters)

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#259]
### Enhancement

Certain fields in the query builder facets have thousands of values. Navigating through these with the pagination is awkward. In order to improve the UX we would like to **remove the pagination from all multi-select facets** and replace them with a "view more" button + scroll 

### Functional specifications

- Display a maximum of 10 values by default
- If there are more than 10 values available for a given field, display a "show more" component:
  - Component should span full width of dropdown container
  - Component is made up of: total number of values + link to display all (label TBD)
- Clicking the display all link will display all values and the overflow will be accessed on scroll
- The button toolbar (annuler / appliquer) should remain fixed to bottom of dropdown (not in scroll)
- Max-height of dropdown container is 500px

_HiFi design coming, but in mean time…_

![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/0d9ba725-2967-443c-81bd-7075c11a99d9)

### Resources

_Designfile coming_

**Comment by denis-crsj** [comment]
Done for Specific filters. Need to be done for the Generic filters. See new ticket https://github.com/Ferlab-Ste-Justine/clin-project/issues/409
