### ISSUE TITLE
Créer le tableau des fichiers dans la page Patient

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#270]
Voir les spécifications associées à l'épic
https://docs.google.com/document/d/1L0ezK7VSwCI0RfqnASFs5uvxTnWUzi9EvtA7eQ0x7qw/edit#heading=h.7waay42flx2y

**Comment by denis-crsj** [comment]
Transféré au icebox pour l'instant. sera de retour sous peu
