### ISSUE TITLE
Ajouter les phénotypes du patient dans l'index des variants

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#271]
Tel que spécifié dans le fichier de [spécification de la page variant (onglet Associations cliniques) ](https://docs.google.com/spreadsheets/d/196QRqOZi4KMiK2r7X3Bvmt79vJJA7FiSVD4Ha9IPzVs/edit#gid=1472128291), on voudrait afficher le nombre de patients qui possèdent un variant donné avec un phénotype donné.

Pour ce faire, il faut ajouter le champ de type array donors.phenotype[k] dans l'index variant
Les valeurs seront de la forme habituelle avec le terme et le ID entre parenthèses
Exemple: Intellectual disability (HP:0001249)

**Comment by latch2112** [comment]
@vferretti Est-ce que tu veux les observations phénotypiques positives et négatives ou juste les positives ?

**Comment by latch2112** [comment]
tâches:

mettre à jour le client patient/es pour obtenir la liste des phénotypes des patients à l'indexation
test
mettre à jour l'index variant
test
dry run
test
etl

**Comment by latch2112** [comment]
**note:** Ceci va faire augmenter la taille de l'index variants assez drastiquement 
Les besoins calculés initialement devraient être revu

Chaque variant (~ 200k variants / exôme) qui ont des donneurs vont également avoir tous les phénotypes dudit donneur

**Comment by vferretti** [comment]
Essayons. 
Bon point, On mettra juste les observations positives

**Comment by latch2112** [comment]
Excellent
