### ISSUE TITLE
Index - mutation-centric: changer le champ “consequence”.“aaChange”

### ISSUE THREAD

**Issue by Emma-Drieux** [Ferlab-Ste-Justine/clin-project#273]
Le champ “consequence”.“aaChange” doit etre représenté comme suit:
“p.(”+Amino_acids.substring(0,1) + Protein_position + Amino_acids.substring(2)+”)”

Exemple d'une valeur: _“aaChange”: "p.(Gln2013Ter)"_

Actuellement, le code des amino-acides utilisé est a une lettre. Il y a deux options possibles pour obtenir le résultat de l'exemple cité ci-dessus:
- Utiliser la notation hgvs dans VEP
- Utiliser un dictionnaire pour la correpondance lettre aa - code a trois lettres:
Phe:F, Leu:L, Ile: I, Met: M, Val: V, Ser/S, Pro: P, Thr: T, Ala: A, Tyr: Y, His: H, Gln: Q, Asn: N, Lys: K, Asp: D, Glu: E, Cys: C, Trp: W, Arg: R, Ser: S, Arg: R, Gly: G, Stop (si utilisé)

Documentation:
https://docs.google.com/document/d/1nBxhbUui-bHy2E4PCtGSy239-vos1MjYoBs4jM2aCPo/edit#

**Comment by denis-crsj** [comment]
Carte déplacée vers le Icebox de Notion pour l'instant.
