### ISSUE TITLE
Index - mutation_centric: ajouter un champ “donor”.”origin” 

### ISSUE THREAD

**Issue by Emma-Drieux** [Ferlab-Ste-Justine/clin-project#274]
Ce champ permettra de déterminer quel parent a transmis la mutation. Par la suite, cette donnée sera integrée dans le tableau Résultats du rapport comme expliqué dans le document d'analyse

Document:
https://docs.google.com/document/d/1nBxhbUui-bHy2E4PCtGSy239-vos1MjYoBs4jM2aCPo/edit#

Taches:
- Rajouter a l'index mutation_centric, au niveau du bloc ** "donor" ** le champ: ** ”origin” **
- Remplir ce champ selon l'algorithme décrit dans la section: ** Champs à implémenter/Algorithme ** du document d'analyse

**Comment by latch2112** [comment]
Si ce champs ne sert pas à la recherche et s'il sert uniquement à afficher dans un rapport, surtout qu'il ne s'applique pas à tous les donneurs, ne serait-il pas préférable de le générer au moment du rapport ?

**Comment by Emma-Drieux** [comment]
Je pense pas qu'on ait a mettre un filtre pour cette donnee, mais il ne sert pas uniquement dans le rapport: il sert lors de l'analyse a tracer la transmission du variant au sein de la famille. Disons que si on avait a positionner cette information, on la metterait avant le mode de transmission (les fameux AD, AR XD etc) pour repondre a la question: quelle(s) branche(s) de la famille a transmis l'allele? En d'autre terme, le geneticien doit etre en mesure de visualiser cette information dans la liste des variants. 
Pour revnir au rapport, cette information sera aussi utile pour praticien pour mettre en place sa strategie de conseil genetique.

Pour ce qui est des donneur, en effet, de facon generale, l'information de la transmission au sein de la famille n'est utile que si on a au minimum un trio, pour le reste, on ne peut pas arriver a une conclusion quant a la transmission de l'allele. On peut par exemple faire le choix de ne rien afficher pour la colonne transmission dans le cas d'un duo ou solo, apres c'est un autre point a discuter

**Comment by latch2112** [comment]
good merci

**Comment by latch2112** [comment]
@Emma-Drieux ; @vferretti 
Est-ce que ticket est prêt ? (il est dans la colonne backlog)

**Comment by Emma-Drieux** [comment]
attends je regarde..

**Comment by Emma-Drieux** [comment]
Oui normalement c'est ok. Pour l'origine parentale, faudra suivre le document: https://docs.google.com/document/d/124CFQCSWOtNeeA-6PprKTc-aEGJJWdEphbruML6345Q/edit#

**Comment by Emma-Drieux** [comment]
N'hesite pas si t'es des questions ;)
