### ISSUE TITLE
Determine Required Tests for SQON -> ES Mapper

### ISSUE THREAD

**Issue by nyanofthemoon** [Ferlab-Ste-Justine/clin-project#280]
Please define the exact test cases to implement;

**As an example, using PA00002**:

**Test Case 1**
![image.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/27554559-99dc-4984-83e8-089f97edd5d1)

**Test Case 2**
![image.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/1479eeb2-cea3-4985-a5cc-1308893e9bb6)

**Test Case 3***
![image.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/9e1367f2-f0d8-4053-abb1-4fb6f79bfb34)

**Test Case 4**
![image.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/3b482aa5-b16e-4845-8663-1dd3e1a7187d)

You can use @latch2112 test matrix as a starting point: https://docs.google.com/spreadsheets/d/1RSjmjHFgoJujEeiUL8uvynfci874cOeNJZDzbwcaNrg/edit?usp=sharing

Please note that the resultset is not required for this ticket (unit testing) but will be required later on for functional testing the variant service. We are testing the translation between the SQON (from variant interpretor) and ElasticSearch.

**Comment by vferretti** [comment]
See
https://docs.google.com/document/d/1KxTwO-HoNem9vgOB6u0hKKS1fmC6csGrXMDusFZahHI/edit?usp=sharing
