### ISSUE TITLE
Filtre tableau patient – créer les composantes facette

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#291]
### Feature

La facette nous permet de filtrer le tableau par un ou plusieurs critères (c'est un `or`)

### Specs

**Note:** les maquettes sont un peu dépassées donc, créer les composantes pour les facettes suivant **les mêmes features** que les facettes des variants:

  - Loupe pour filtrer dans la facette
  - Boutons `Tout sélectionner | Aucun`
  - Le nombre de résultats pour chaque terme à droite
- Aucune pagination dans les facettes (si on a plus que 10 termes suivre la même interaction que #259)
- Pas de bouton expand pour fermer/ouvrir chaque facette (c'était une idée qui figure dans la maquette mais qu'on ne fait pas)

Pour l'affichage des filtres:
- Filtre **Position**: on affichera Proband ensuite Parent
- Pour **Statut de la requête**: Active puis Completed
- **Institution**, **Laboratoire**: par ordre alphabétique
- **Médecin référent**, **Généticien**: par ordre alphabétique  (sur le nom de famille)
- Filtre **Famille** dans l'ordre suivant: Solo, Duo et Trio

On se concentre uniquement sur les facettes dans ce ticket, pas la barre des tag au-dessus du tableau qu'on voit dans la maquette!

### Resources

https://share.goabstract.com/bb2c408f-65e3-48a1-a236-2d0ef5d84d2f?collectionLayerId=65960f1f-47b5-42ee-945e-5c98545d363a&mode=design

**Comment by latch2112** [comment]
Nous avons aucun composant (de la recherche de variant) qui répond au demandes  
pour l'affichage des filtres suivantes:

Filtre Position: on affichera Proband ensuite Parent
Pour Statut de la requête: Active puis Completed
Institution, Laboratoire: par ordre alphabétique
Médecin référent, Généticien: par ordre alphabétique (sur le nom de famille)
Filtre Famille dans l'ordre suivant: Solo, Duo et Trio

Les composants des variants sont tous sans exception trié par quantité.

On doit écrire un système différent qui va 'gérer ces nouveaux filtres' et afficher leur information dans un ordre différent.
Ensuite, leur action (filtre des variants) génère un SQON qui est affiché dans un système de recherche et envoyé au fur et à mesure au service de variants; similaire à celui demandé mais le rendu visuel du SQON est aussi différent. On doit ré-implémenter ce système de rendu ou modifier le système existant pour le faire fonctionner avec ceux des patients.


@nyanofthemoon Est-ce que j'oublie quelques choses dans les grandes lignes ?

**Comment by nyanofthemoon** [comment]
@latch2112 That sums it up, methinks.

**Comment by latch2112** [comment]
@luclemo Ce ticket est beaucoup trop gros pour une histoire; c'est un épique au sein d'un épique;
Pour briser en morceaux ce ticket, tu dois assoir ensemble, un SME (Subject Matter Expert) ainsi que les architectes du système.

**Comment by luclemo** [comment]
@latch2112 Récemment le message a été "Créez des tickets et on prend les tickets qu'on veut".

Ce ticket résume, après des échanges avec @vferretti et @Emma-Drieux, le comportement souhaité pour chaque facette ainsi que leur affichage.

Bien que ce sont 5 facettes distinct au niveau back-end, c'est dans un seul ticket adressé à @claudia1296 car du point de vue design et UX c'est une composante générique (tel que le multi-select générique qu'on a fait pour le filtre des variants) qu'elle peut développer avec des données hard-codées tel que convenu ce matin. L'objectif étant de lui donner un nouveau projet et d'éviter de la bloquer.

Pour ce qui est des taches (pas encore définis) qui concernent le hook-up de vraies données, tu sembles être bien parti dans ton commentaire très clair appuyé par @nyanofthemoon. Donc super les SME + Je peux faire du copier/coller des bouts de ton message en tickets si ça peut vous aider à vous organiser, mais je ne suis absolument pas en mesure d'y inclure des détails technique. 

Il me fera plaisir de m'assoir avec les SME et architectes du système (on pourrait même s'appeler par nos petits noms?). En effet, je pourrais ainsi offrir des réponses précises aux questions précises qui relève du ** user interaction**, du **rendu visuel**, ou des résultats souhaités **du point de vue du user**. Autrement, si ça relève de préoccupations techniques, je vais bien écouter afin d'apprendre mais, n'étant pas mon domaine, je n'aurais pas grand choses à offrir... Main on a des experts du domaine donc ça va bien aller 😀🌈

**Comment by luclemo** [comment]
TL;DR allez-y, rien ne vous retient, au contraire…
