### ISSUE TITLE
Bloc parent dans specimen a enlever

### ISSUE THREAD

**Issue by Emma-Drieux** [Ferlab-Ste-Justine/clin-project#299]
Actuellement, dans la structure des données de FHIR, un Specimen dépend d’un parent. Le but de la storie étant de se limiter au tissu source et de supprimer le champ qui renvoie vers un Specimen parent.
Le problème qui se pose et auquel il faudra répondre c’est que dans SONG, il y a la notion de Specimen → Sample.

**Livrables** 
- Donner la nouvelle structure de Specimen et la documenter
- Esquiser une solution pour SONG

**Comment by denis-crsj** [comment]
@Emma-Drieux Salut Emma, comment est-ce qu'on peut tester cette carte et qui serait en mesure de le faire ?

**Comment by Emma-Drieux** [comment]
C'est juste adapter le modele, mais pour ce qu'on est entrain de faire actuellement avec Vincent, on s'est dit qu'on se focalise sur les donnees de la soumission, et on a la chance de ne pas avoir de specimens XD .. Les modifs que j'ai fait y a un moment maintenant sont a revoir simplement parce que on veut documenter les particularites de notre modele (ex. pour les champs a rajouter (qui sont au fait des extensions), on a nos propres valeurs: ca implique qu'il faudra definir cette nouvelle contrainte, l'extension et notre dictionnaire de valeurs).. on laisse ca de cote pour le moment avec le consentement aussi :)

**Comment by denis-crsj** [comment]
Après discussion avec Emma, les modifications qui sont présentement en cours pour le modèle FHIR invalident cette carte.
