### ISSUE TITLE
Rajouter une extention "consanguinite" (ang. inbreeding) au patient

### ISSUE THREAD

**Issue by Emma-Drieux** [Ferlab-Ste-Justine/clin-project#300]
Les valeurs que peut prendre ce champ est un booleen (true or false)

**Livrable**
- Donner la nouvelle version de la structure du json patient

**Comment by denis-crsj** [comment]
@Emma-Drieux Qui serait en mesure de valider cette tâche ?

**Comment by Emma-Drieux** [comment]
Ben ofait j'ai defini l'extension dans le modele (y a fort longtemps), mais la, on cherche aussi a avoir l'implementation guide, donc je pense qu'on va attendre de ne plus avoir d'erreur (la tu vois, j'ai une erreur avec la definition des valueSet que je dois fixer). On laisse ca de cote pour le moment

**Comment by denis-crsj** [comment]
Après discussion avec Emma, les modifications qui sont présentement en cours pour le modèle FHIR invalident cette carte.
