### ISSUE TITLE
[CLIN_VAR] Functional test for gene Service

### ISSUE THREAD

**Issue by latch2112** [Ferlab-Ste-Justine/clin-project#302]
Please write the following functional tests in a postman collection to be executed using newman in clin-proxy-api. Please refer to tests/functional/collections directory and tests/functional/runner.js.

Define list of positive and negative tests to write
Write defined tests
Service routes are located in src/services/api/gene

**Comment by nyanofthemoon** [comment]
Skeleton done here: https://github.com/cr-ste-justine/clin-proxy-api/pull/99
