### ISSUE TITLE
Données en Francais/Anglais

### ISSUE THREAD

**Issue by EmmyDx** [Ferlab-Ste-Justine/clin-project#303]
Notre interface web s’affiche dans les deux langues. Il faudra définir une stratégie afin que les champs dans FHIR inclus les deux cas
Il faudra definir préalablement les champs qui s'affichent sur l'interface et dans quelle langue ils s'affichent --> tableau
Ce point doit faire l’objet d’une analyse afin qu’on soit fixé sur ce qu’on a a changer et la meilleure stratégie
Ex. standard HPO disponible dans les deux langues : https://www.hetop.eu/hetop/

**Comment by denis-crsj** [comment]
Cela semble être une tâche d'analyse et/ou d'investigation. Je suggère de ne pas placer ce type de tâche dans le tableau mais plutôt de trouver un autre endroit pour garder ce type de tâches et ne pas les oublier. Notion serait surement un bon endroit pour cela, à voir...
