### ISSUE TITLE
Créer le service pour la recherche par facette du tableau Participant

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#304]
SQON + Requete ES

**Comment by latch2112** [comment]
Le SQON ainsi que son interpréteur Elasticsearch du service de recherche patient doit contenir les champs suivants:

- Position
- Statut de la requête
- Institution
- Médecin référent
- Laboratoire
- Généticien
- Famille

@vferretti : Est-ce que tu vois autres choses ?

**Comment by latch2112** [comment]
Investigation du service

**Comment by latch2112** [comment]
il semblerait que **Position** ne soit pas un champs par lequel on peut chercher. **Position** est une extrapolation Frontend du champs suivant:
"isProband" : true

**Comment by latch2112** [comment]
consolidation du code du 'sqon mapper' pour ré-utilisation efficaces

**Comment by latch2112** [comment]
le sqon-mapper utilise une version optimisé de ES (recherche par terme au lieu de 'match')
Doit faire le mapping patient et ré-indexer ...  voir si ça marche avec le ETL patient

**Comment by denis-crsj** [comment]
Un autre plan de match a été établi. une nouvelle carte sera ouverte
