### ISSUE TITLE
Afficher le tableau OMIM dans la page Variant

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#306]
Voir specification
https://docs.google.com/document/d/1UlYI-Eqtvj9wDmBx7nUvdSFRfWtKDa1MhZ8u-luPPeA/edit#

### Defects
- [ ] Ajouter les liens manquant dans les colonnes comme mentionné dans les spécifications:  https://docs.google.com/document/d/1UlYI-Eqtvj9wDmBx7nUvdSFRfWtKDa1MhZ8u-luPPeA/edit#heading=h.7pkft8b9bw54

**Comment by latch2112** [comment]
Après le nouveau ETL et suite au spécification, l'information pour le tableau sera

- genes.geneMim (1..1)
- genes.omim.* (1..n) 
  - genes.omim.phenotypeMim (1..1)
  - genes.omim.phenotype (1..1)
  - genes.omim.inheritance (1..n)

**Comment by latch2112** [comment]
`{
        "_index" : "mutations_test",
        "_type" : "_doc",
        "_id" : "4072103968AFF18A675F1B88082C208F",
        "_score" : 1.0,
        "_source" : {
          "genes" : [
            {
              "biotype" : "protein_coding",
              "ensemblId" : "ENSG00000218336",
              "hgnc" : "29944",
              "geneMim" : [
                "610083"
              ],
              "hpo" : [
                "Delayed speech and language development (HP:0000750)",
                "Microcornea (HP:0000482)",
                "Microphthalmia (HP:0000568)",
                "Iris coloboma (HP:0000612)",
                "Ptosis (HP:0000508)",
                "Global developmental delay (HP:0001263)",
                "Autosomal recessive inheritance (HP:0000007)",
                "Sclerocornea (HP:0000647)",
                "Macrotia (HP:0000400)",
                "Hypertelorism (HP:0000316)",
                "Long philtrum (HP:0000343)",
                "Narrow palpebral fissure (HP:0045025)",
                "Retinal detachment (HP:0000541)",
                "Ocular anterior segment dysgenesis (HP:0007700)",
                "Intellectual disability (HP:0001249)",
                "Reduced visual acuity (HP:0007663)",
                "Pendular nystagmus (HP:0012043)",
                "Low-set ears (HP:0000369)",
                "Esotropia (HP:0000565)"
              ],
              "geneSymbol" : "TENM3",
              "geneId" : "55714",
              "omim" : [
                {
                  "phenotype" : "Microphthalmia, isolated, with coloboma 9",
                  "phenotypeMim" : "615145",
                  "inheritance" : [
                    "AR"
                  ]
                },
                {
                  "phenotype" : "icrophthalmia, syndromic 15",
                  "phenotypeMim" : "615145",
                  "inheritance" : [
                    "AR"
                  ]
                }
              ],
              "name" : "teneurin transmembrane protein 3",
              "orphanet" : [
                {
                  "dataId" : "13955",
                  "panel" : "Colobomatous microphthalmia (Orph:98938)"
                }
              ],
              "alias" : [
                "MCOPCB9",
                "ten3",
                "TEN3",
                "MCOPS15",
                "TNM3",
                "ODZ3",
                "Tenm3"
              ],
              "location" : "4q34.3-q35.1",
              "radboudumc" : [
                "Vision Disorders",
                "Preconception Screening"
              ]
            }
          ],
          "annotationTool" : "VEP 97",
          "start" : 182346995,
          "altAllele" : "CG",
          "refAllele" : "C",
          "type" : "insertion",
          "chrom" : "4",
          "dnaChange" : "C>CG",
          "availableDbExt" : {
            "hpo" : true,
            "orphanet" : true,
            "radboudumc" : true
          },
          "lastAnnotationUpdate" : "2020-05-27",
          "consequences" : [
            {
              "biotype" : "protein_coding",
              "geneAffectedId" : "ENSG00000218336",
              "consequence" : [
                "intron_variant"
              ],
              "strand" : 1,
              "transcripts" : [
                {
                  "pick" : "1",
                  "featureType" : "Transcript",
                  "canonical" : true,
                  "refSeqId" : "NM_001080477.4",
                  "featureId" : "ENST00000511685"
                }
              ],
              "pick" : true,
              "impact" : "MODIFIER",
              "geneAffectedSymbol" : "TENM3",
              "canonical" : true
            }
          ],
          "donors" : [
            {
              "adAlt" : 17,
              "patientId" : "PA00002",
              "specimenId" : "SP00011",
              "gq" : 48,
              "gt" : "1/1",
              "practitionerId" : "PR00202",
              "relation" : "Proband",
              "filter" : "PASS",
              "familyId" : "FA0002",
              "organizationId" : "OR00101",
              "adFreq" : 1,
              "qd" : 6.71,
              "zygosity" : "HOM",
              "adTotal" : 17,
              "lastUpdate" : "2020-05-27",
              "sequencingStrategy" : "WXS",
              "studyId" : "ET00011",
              "genotypeFamily" : "FTH:1/1,MTH:1/1"
            },
            {
              "adAlt" : 15,
              "patientId" : "PA00052",
              "specimenId" : "SP00061",
              "gq" : 42,
              "gt" : "1/1",
              "practitionerId" : "PR00202",
              "relation" : "FTH",
              "filter" : "PASS",
              "familyId" : "FA0002",
              "organizationId" : "OR00101",
              "adFreq" : 1,
              "qd" : 6.71,
              "zygosity" : "HOM",
              "adTotal" : 15,
              "lastUpdate" : "2020-05-27",
              "sequencingStrategy" : "WXS",
              "studyId" : "ET00011"
            },
            {
              "adAlt" : 15,
              "patientId" : "PA00027",
              "specimenId" : "SP00036",
              "gq" : 42,
              "gt" : "1/1",
              "practitionerId" : "PR00202",
              "relation" : "MTH",
              "filter" : "PASS",
              "familyId" : "FA0002",
              "organizationId" : "OR00101",
              "adFreq" : 1,
              "qd" : 6.71,
              "zygosity" : "HOM",
              "adTotal" : 15,
              "lastUpdate" : "2020-05-27",
              "sequencingStrategy" : "WXS",
              "studyId" : "ET00011"
            }
          ],
          "mutationId" : "chr4:g.182346995C>CG",
          "impactScore" : 1,
          "specimenList" : [
            "SP00011",
            "SP00061",
            "SP00036"
          ],
          "assemblyVersion" : "GRCh38",
          "frequencies" : {
            "LDx-CHUSJ" : {
              "AC" : 6,
              "AF" : 1,
              "HC" : 3,
              "AN" : 6,
              "PN" : 3
            },
            "interne" : {
              "AC" : 6,
              "AF" : 1,
              "HC" : 3,
              "AN" : 6,
              "PN" : 3
            }
          }
        }
      }`

**Comment by vferretti** [comment]
@latch2112  is this ticket still blocked?

**Comment by latch2112** [comment]
@vferretti Oui, le bloquant est en peer review...  Il reste le ETL à re-rouler pour avoir les données

**Comment by latch2112** [comment]
@vferretti unblock

**Comment by vferretti** [comment]
Ajouter les liens tels que spécifiés dans le document
https://docs.google.com/document/d/1UlYI-Eqtvj9wDmBx7nUvdSFRfWtKDa1MhZ8u-luPPeA/edit#heading=h.7pkft8b9bw54

**Comment by denis-crsj** [comment]
@claudia1296 J'ai ajouté le defect dans la description en haut et je vais bouger la carte dans "In Progress"

**Comment by denis-crsj** [comment]
@claudia1296 J'ai testé la tâche de nouveau et je ne vois toujours pas les liens, est-ce normal ?

**Comment by denis-crsj** [comment]
Les liens apparaissent maintenant et redirigent correctement sur le site OMIM.
