### ISSUE TITLE
Requête médecin: intégrer le consentement du patient

### ISSUE THREAD

**Issue by EmmyDx** [Ferlab-Ste-Justine/clin-project#307]
Lors de la consultation clinique, le médecin fait remplir au patient un formulaire de consentement pour l’analyse génétique. L'idée est d'intégrer cette donnée dans notre modèle FHIR.

Documentation a realiser:
https://www.notion.so/ferlab/Feuille-de-route-68f97b055407413fac9ad338d82e2118?p=b936ec6853474a75a363219ca65c4908

**Comment by denis-crsj** [comment]
Cela semble être une tâche d'analyse et/ou d'investigation. Je suggère de ne pas placer ce type de tâche dans le tableau mais plutôt de trouver un autre endroit pour garder ce type de tâches et ne pas les oublier. Notion serait surement un bon endroit pour cela, à voir...
