### ISSUE TITLE
Page de Variant: tous les scores ne s'affichent pas dans le tableau des conséquences

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#313]
allez à https://clin.cr-ste-justine.xyz/variantDetails/60BD53F4F6DD64F77D5CAE0038BC4524

Ce variant possède des scores CADD (entre autre)  mais ils ne sont pas affiché dans le tableau Conséquences.

Spec: https://docs.google.com/spreadsheets/d/196QRqOZi4KMiK2r7X3Bvmt79vJJA7FiSVD4Ha9IPzVs/edit#gid=0

**Comment by nyanofthemoon** [comment]
assigned @latch2112 as support and knowledge transfer to be able to complete this ticket

**Comment by latch2112** [comment]
Pour valider au niveau de la bd ES, on peut faire la recherche suivante dans Kibana (disponible en localhost 5601 aprè l'ouverture d'un tunel ssh):
`GET /mutations/_doc/60BD53F4F6DD64F77D5CAE0038BC4524`

**Comment by latch2112** [comment]
la conséquence est la suivante:
`{
        "biotype" : "protein_coding",
        "conservationsScores" : {
          "PhyloP17Way" : 0.19243
        },
        "consequence" : [
          "stop_gained"
        ],
        "transcripts" : [
          {
            "pick" : "1",
            "featureType" : "Transcript",
            "canonical" : true,
            "refSeqId" : "NM_001300891.1",
            "featureId" : "ENST00000436041"
          }
        ],
        "impact" : "HIGH",
        "geneAffectedSymbol" : "PRAMEF27",
        "canonical" : true,
        "predictions" : {
          "CADD_score" : 0.75041,
          "DANN_score" : 0.23962,
          "LRT_pred" : "NEUTRAL",
          "LRT_score" : 0.03045
        },
        "geneAffectedId" : "ENSG00000274764",
        "strand" : -1,
        "pick" : true,
        "aaChange" : "C411*",
        "cdnaChange" : "1233G>T"
      }`

**Comment by latch2112** [comment]
Regardons au niveau du service variant en local:
GET à `https://localhost:5001/variant/{uid}`
ou {uid} est 60BD53F4F6DD64F77D5CAE0038BC4524

la réponse aussi possède la bonne information 
`"predictions": {
                    "CADD_score": 0.75041,
                    "DANN_score": 0.23962,
                    "LRT_pred": "NEUTRAL",
                    "LRT_score": 0.03045
                },`

**Comment by latch2112** [comment]
reste juste à se pencher sur le frontend...

**Comment by latch2112** [comment]
https://github.com/cr-ste-justine/clin-frontend/pull/218

**Comment by latch2112** [comment]
mauvais noms de variable des objects utilisés
