### ISSUE TITLE
Recherche de variants: Le bouton Back ne retourne pas la page dans l'état initial

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#314]
Allez à la page de recherche de variant pour un patient de type Probant (c-a-d avec des variants)
appliquez un filtre quelconque ex. Impact VEP = Modifier
cliquer sur un variant de la liste pour obtenir sa page de variant
Faire Back
Bug: la page de recherche de variant a perdu son filtre initial Impact VEP = Modifier

**Comment by latch2112** [comment]
Les specifications originale lorsqu'on entre dans la page dans la page de recherche de variants d'un patient est :
Si un filtre par défaut existe, on applique celui-ci
Si aucun filtre par défaut existe, on affiche aucun filtre et une requête vide.
Dans un SPA (lorsqu'on click BACK) dans un browser, on retourne dans la page précédente ; hors ceci revient à ce qui est mentionner plus haut:

Donc, on doit ajouter une nouvelle règle lorsqu'on arrive dans la page de recherche de variants ainsi que lorsqu'on click sur un variant:
Lorsqu'on click sur un variant, enregistrer le filtre "en cours"
Lorsqu'on entre sur la page de recherche de variants:
S'il existe un filtre "en cours"; afficher celui-ci

**Comment by latch2112** [comment]
@nyanofthemoon Je viens de me souvenir que c'est possible que ces features avaient déjà été fait ? Hors ce serais vraiment un bug ?

**Comment by nyanofthemoon** [comment]
@latch2112 me semble que j'avais mis qu'on allait chercher dans cet ordre quand on arrive sur la page...
1- redux sous `draft` (requete en cours pas sauvegardee)
2- si `draft` vide, aller cherche le "default statement"
3- si pas de "default statemement", mettre un empty statement

**Comment by latch2112** [comment]
Lorsque le ticket 197 sera réglé, il sera plus simple d'addresser celui-ci

**Comment by denis-crsj** [comment]
Après vérification en QA ce matin, le problème semble résolu. Je ferme donc cette carte.
