### ISSUE TITLE
Design on-boarding: Create a Figma component for the variant facet bar

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#315]
### Background

I created a ["Playground" project area](https://www.figma.com/files/project/9051622/%F0%9F%8F%80-Playground) in our team dashboard to serve as a space for getting comfortable with Figma and design systems. 

We have many custom components which were originally created as Sketch symbols. We would like to transfer these into Figma components in order to add them to our UI Kit library for use across various files/projects.

This is a great opportunity to learn how components and libraries work in Figma!

### Task

The first task is to recreate the clin **variant facet bar** as a Figma component. I have already dumped the Sketch symbol it into the file.

Make your edits directly in this file:

- https://www.figma.com/file/rCQdoNzOTSXZBBAOwyZJDy/Component-Exercises?node-id=123%3A8229

### Guidelines

- Figure out how to include team libraries into a new file. You will need to pull in styles and icons from:
  - `Clin - UI Kit` library
  - `Material Icon` library
- Use auto-layout where it can help with consistency and reduction of number of containers
- Make heavy use of components and nested components for maximum flexibility and overrides
- Keep the 8pt grid system as a reference for measurements

### Resources

- Figma [best practices](https://www.figma.com/best-practices/) and resource list I created: https://docs.google.com/document/d/1xq8EgxiIW78DNPQSo1N4IRkDFYQj2U9HLA35Xd_aGF4/edit#heading=h.u0csd4k39obe

**Comment by denis-crsj** [comment]
Very well documented and a good idea. Moving the card to the Icebox in Notion for now though just to clear the backlog a little and focus on the priorities related to the MVP. Let's re-add it to the backlog a bit later.
