### ISSUE TITLE
Facette variants: incapable de sélectionner certaines valeurs filtrées par recherche

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#316]
### Summary of problem

When narrowing down values via search in variants facet, certain values cannot be selected.

### Steps to Reproduce

1. Go to `Génomique > Type de gène`
2. Click on search icon and type `pr`
3. Try to click on `processed_pseudogene `

### Expected behavior

I should be able to select the value

### What happens instead

Unable to select

### Screenshots

![Pasted_Image_2020-05-19__10_09_AM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/a34bb0ad-e34a-4a5f-8b40-ad554562052f)

### Additional context

This also happens for other fileds. Example:

- Génomique > HPO 
- Type `n` in search
- Unable to select `Nystagmus `

**Comment by denis-crsj** [comment]
Testé, problème résolu.

**Comment by denis-crsj** [comment]
@YanLabCHU Quel était le problème ?
