### ISSUE TITLE
Traitement des variants: Téléchargement d'un rapport diagnostique format excel

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#323]
# Feature

As a genetician I want to select one or more filtered variants from the variants table and export (download) the data as a custom formatted excel document which I can include into a larger diagnostic report.

#### Background

- I am logged into the app
- I am on the variant interpreter page for a given patient (with proper permission)
- The variant table is populated

#### Scenario 1

User can successfully download a formatted excel document from selected variants

  - **Given:** Background
  - **When:** I select one or more variants (checkbox) from the table
    - **And:** I click on the "générer rapport" button
    - **And:** A report is successfully generated in the background
  - **Then:** A pre-formatted excel document is downloaded to my machine
    - **And:** I obtain a success notification

#### Scenario 2

User cannot successfully download a formatted excel document from selected variants

  - **Given:** Background
  - **When:** I select one or more variants (checkbox) from the table
    - **And:** I click on the "générer rapport" button
    - **And:** A report is unable to be generated in the background (error)
  - **Then:** I obtain an error notification

#### Functional & UX specs

- [Google Doc](https://docs.google.com/document/d/1nBxhbUui-bHy2E4PCtGSy239-vos1MjYoBs4jM2aCPo/edit#heading=h.hejj8miepfuy)

#### HiFi Mockups

- [Figma](https://www.figma.com/file/8ARRZswPZbRs583ZKDs7ln/CLIN---Tableau-des-variants-cliniques?node-id=298%3A2991&viewport=1025%2C670%2C0.33503401279449463)

#### Component details

- [Ant notification with custom icon](https://ant.design/components/notification/#components-notification-demo-custom-icon)

#### Résumé suite du contenu des colonnes du rapport
Vue actuelle du rapport:
![Vue actuelle](https://user-images.githubusercontent.com/12585875/85775017-636fd800-b6ed-11ea-9ae6-b5b2bd1792f6.png)

**1. Pour la première colonne: "Variation nucléotidique", Mettre comme titre "Variation Nucléotidique (GRChv38)"**
Concernant le contenu des cellules de cette colonne:
A droite, c'est l'excel qu'on génère, a gauche le format du tableau qu'on aimerait avoir

![rapport](https://user-images.githubusercontent.com/12585875/85775560-e2651080-b6ed-11ea-8581-627c5c54fc4f.png)

- Pour chaque nouvelle donnée, il faut revenir a la ligne
- Il manque l'id de dbSNP (format rs...)
- Le symbol du gène devrait être en gras
- Modifications cDNA (85 G>T) et de l'acide amine (ou AA en abréviation), les mettre comme sur le tableau: c.(...) pour le changement cDNA et p.(....) pour celui de l'AA
- Il y a le cas ou on a plusieurs variantion d'AA (ex. chr11:g.233419G>A  gène:SIRT3    NM_175932.2   NM_012239.6     397G>A     154G>A      R133W   R52W). Il faudra dupliquer les lignes de telle sorte a avoir pour chaque ligne un seul NM.. une seule variation de cDNA et une seule variation d'AA

**2. Pour la deuxième colonne: Statut (origine parentale)**
- Faut mettre Hétérozygote (pour HET) et Homozygote (pour HOM)
- Mettre la phrase; "couverture de la variation .... lectures de séquences" comme suit:

![rapport](https://user-images.githubusercontent.com/12585875/85776331-9bc3e600-b6ee-11ea-92d4-b07683a60b9e.png)

**3. La prédiction in silico** c'est celle de SIFT
**4. Colonne ClinVar**
- Mettre les significations cliniques en francais Cf. tableau de correspondance des termes de significations cliniques en annexe du document d'analyse
- Pour l'identifiant mettre: (ClinVar variation ID: ....) comme sur le tableau modèle
![rapport](https://user-images.githubusercontent.com/12585875/85777522-b0ed4480-b6ef-11ea-973a-c65aad77eaed.png)

> Remarque: Pour les cases vides dans le tableau, mettre des 0 comme sur le modele

**Comment by luclemo** [comment]
@FrancisRenaud comme on en a parlé, ce ticket se limite au téléchargement dès que l'on clique sur le bouton. On traitera le modal avec le preview dans une tâche séparée.

Je te laisse relire le google doc pour les specs, et si tu as des questions hors du contexte design/UX, n'hésites pas à contacter @Emma-Drieux. Merci!

**Comment by Emma-Drieux** [comment]
@claudia1296 Francis a codé le téléchargement du rapport, manque a ajuster les données, j'ai tt mis dans la section: "Résumé suite du contenu des colonnes du rapport" du ticket, n'hésite pas si t'as des questions ;)
