### ISSUE TITLE
Traitement des variants: modal avec aperçu du rapport diagnostique

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#324]
# Feature

This is an enhancement of #323

As a genetician I want to: see a preview of the formatted variant report table and then download it.

#### Background

- I am logged into the app
- I am on the variant interpreter page for a given patient (with proper permission)
- The variant table is populated

#### Scenario 1

User can see a preview of the formatted variant report table prior to download

  - **Given:** Background
  - **When:** I select one or more variants (checkbox) from the table
    - **And:** I click on the "générer rapport" button
  - **Then:** A modal will open containing a formatted preview of my report and action buttons (annuler / télécharger)

#### Scenario 2

User can successfully download the table report from the modal

  - **Given:** Scenario 1 (modal is open)
  - **When:** I click on "télécharger"
    - **And:** A report is successfully generated in the background
  - **Then:** A pre-formatted excel document is downloaded to my machine
    - **And:** I obtain the success notification (see #323)

#### Scenario 3

User cannot successfully download the table report from the modal

  - **Given:** Scenario 1 (modal is open)
  - **When:** I click on "télécharger"
    - **And:** A report is unable to be generated in the background (error)
  - **Then:** I obtain the error notification (see #323)

#### Functional & UX specs

- [Google Doc](https://docs.google.com/document/d/1nBxhbUui-bHy2E4PCtGSy239-vos1MjYoBs4jM2aCPo/edit#heading=h.hejj8miepfuy)

#### HiFi Mockups

- [Figma](https://www.figma.com/file/8ARRZswPZbRs583ZKDs7ln/CLIN---Tableau-des-variants-cliniques?node-id=534%3A11699&viewport=-1195%2C712%2C1)

#### Component details

- [Ant modal with loader button](https://ant.design/components/modal/#components-modal-demo-async)
- [Ant small table](https://ant.design/components/table/#components-table-demo-size)
- [Ant notification with custom icon](https://ant.design/components/notification/#components-notification-demo-custom-icon)

**Comment by denis-crsj** [comment]
Moving issue to the Icebox temporarily to focus on the MVP.
