### ISSUE TITLE
Page liste des patients

### ISSUE THREAD

**Issue by Emma-Drieux** [Ferlab-Ste-Justine/clin-project#332]
## Barre recherche

- Recherche ne fonctionne pas: ID Famille, ID specimen

**Comment by latch2112** [comment]
Recherche ne fonctionne pas: ID Famille, ID specimen - fix
William fait partie de deux études: exome quebec et rapido...
Fait un ticket pour l'ordre des colones svp (frontend) ...  le reste c'était du backend

**Comment by Emma-Drieux** [comment]
ok - c'est fait
