### ISSUE TITLE
Page patient - Mettre toujours Nom puis prenom du patient

### ISSUE THREAD

**Issue by Emma-Drieux** [Ferlab-Ste-Justine/clin-project#334]
Mettre toujours nom et prenom du patient
Actuellement, c'est ce qui est affiche dans clin
![Nom prenom patient.png](https://images.zenhubusercontent.com/5c5c6036df0733a30555cc4e/bf59ea57-f3df-4ca7-8eeb-c5eb410afcce)

# Objectif:
Realiser le design puis l'integrer a l'app Clin

**Comment by denis-crsj** [comment]
Tâche testée avec succès.
