### ISSUE TITLE
Transformer certains liens de façon cliquable dans une nouvelle fenêtre

### ISSUE THREAD

**Issue by EmmyDx** [Ferlab-Ste-Justine/clin-project#335]
# Page liste des patients
- Lorsqu'on fait un clique droit sur l'identifiant d'un patient, on ne peut pas l'ouvrir dans un nouvel onglet

# Page variants
- Lorsqu'on fait un clique droit sur l'identifiant d'un variant, on ne peut pas l'ouvrir dans un nouvel onglet

**Comment by latch2112** [comment]
Ceci n'est pas un feature , dans un Single Page App et non un site web, on doit implémenter ce clic droit

**Comment by denis-crsj** [comment]
Transfert de la carte dans le Icebox temporairement question de focuser sur le MVP.
