### ISSUE TITLE
Ajouter un scroll pour la liste des filtre sauvegardés

### ISSUE THREAD

**Issue by EmmyDx** [Ferlab-Ste-Justine/clin-project#338]
Pour la liste de “Mes filtres”, il y a un nombre limités (22 filtres) qu’on peut afficher: réduire la fenêtre et faire un scroll bar pour que l’utilisateur puisse tout visualiser

**Comment by denis-crsj** [comment]
Fermeture de la carte temporairement question de focuser sur le MVP
