### ISSUE TITLE
Ameliorer l'affichage du menu des filtres de la liste des variants

### ISSUE THREAD

**Issue by EmmyDx** [Ferlab-Ste-Justine/clin-project#340]
# Métriques
La notation en anglais n'est pas obligatoire - il faudra discuter de la possibilite ou pas de l'avoir avec les developpeur

| Nom actuel       |    Changement  (Fr)   | Changement  (En)   | 
| :------------ | :-------------: |  :-------------: | 
| depth_quality | Qualité de la profondeur (Fr) | Depth quality (En)  |
| allelic_alt_depth| Profondeur allélique Alt (Fr) |  Alt Allelic depth (En)  |
| total_depth  | Profondeur totale de lecture (Fr)  | Total read depth (En)   |
| genotype_quality  | Qualité du génotype (Fr)  | Genotype quality (En)   |

# Variants - Reference externe
Références externe**s** au pluriel
Les noter correctement sur l’interface

- Pubmed
- DbSNP
- ClinVar

# Génomique - Référence externe
Références externe**s** (au pluriel)
Les noter correctement sur l’interface

- HOP
- Radboudumc
- Orphanet
- OMIM

# Impacts - Évidences cliniques (Clinvar)
- Mettre au pluriel
- Afficher la liste correctement:

Benign
Benign/Likely benign
Likely benign
Conflicting interpretation
Risk factor
Drug response
Uncertain significance
Not provided
Pathogenic
Association
Other
Protective
Affects
Pathogenic/Likely pathogenic

# Fréquences
Noter la liste correctement
- GnomAD Exomes
- GnomAD Genomes
- ExAC
- UK 10k
- 1000 GP3

# Transmission - Zygosite
Noter la liste comme suit:
- Hétérozygote (au lieu de HET)
- Homozygote (au lieu de HOM)

**Comment by denis-crsj** [comment]
carte transférée temporairement dans le Icebox pour focuser sur le MVP
