### ISSUE TITLE
Ouverture de deux menus en meme temps

### ISSUE THREAD

**Issue by Emma-Drieux** [Ferlab-Ste-Justine/clin-project#341]
Lorsqu'on rentre dans un sous-menu d'un filtre dans variant interpreter, puis qu'on passe a un autre, le premier ne se referme pas automatiquement

Voir le screenrecord:
https://drive.google.com/file/d/1aMzKIJogRgpvbcQKtD8z63Bka5Sim7_5/view

### Solution
Il faut cliquer pour ouvrir un top-level menu (non pas hover)

**Comment by vferretti** [comment]
@claudia1296 quand on ouvre un sous menu (ex. Genome -> Types de gene) et qu'on met sa souris à l'exterieur, le sous-menu se ferme au lieu de rester ouvert

**Comment by denis-crsj** [comment]
Problème résolu. Les menus se referment maintenant automatiquement lorsqu'on clique sur un autre menu.
