### ISSUE TITLE
Génomique-HPO: boutons “Observés” et “Non-observés” ne fonctionnent pas

### ISSUE THREAD

**Issue by Emma-Drieux** [Ferlab-Ste-Justine/clin-project#342]
Ces boutons sont supposés faire apparaître les phenotypes (“Observés” ou “Non-observés” selon la sélection de l’utilisateur) au top de la liste, en gras et tagues (voir le design avec Luca)

**Comment by luclemo** [comment]
@Emma-Drieux oui, mais c'est un peu plus compliqué que ça. En fait ceci est due à la pagination et on devait se pencher las-dessus après le #259 que @FrancisRenaud termine en ce moment.

**Comment by Emma-Drieux** [comment]
Ah ok.. On peut l'enlever, je l'ai mis pour ne pas qu'on l'oublie c'est tout

**Comment by denis-crsj** [comment]
Carte bougée dans le Icebox de Notion pour l'instant
