### ISSUE TITLE
Modifier l'affichage des colonnes liste des patients

### ISSUE THREAD

**Issue by Emma-Drieux** [Ferlab-Ste-Justine/clin-project#343]
Changer l’ordre actuel des colonnes de la liste des patients
![image](https://user-images.githubusercontent.com/12585875/83669981-6ff68a00-a5a0-11ea-891a-b4e3cc2fab9b.png)

L'ordre qu'on aimerait avoir est le suivant:
Identifiant patient (ex. PA00123), Nom, Prénom, Date de naissance, Institution, Position, Medecin referent, Requete, Statut

**Comment by denis-crsj** [comment]
Carte déplacée vers le Icebox de Notion pour le moment
