### ISSUE TITLE
Rajouter d'autres colonnes pour liste des patients

### ISSUE THREAD

**Issue by Emma-Drieux** [Ferlab-Ste-Justine/clin-project#345]
![image.png](https://images.zenhubusercontent.com/5c5c6036df0733a30555cc4e/32fd2271-ee71-446b-a142-cb2f599a6c29)

Ajouter dans l’option “Afficher” les colonnes suivantes: 

- MRN
- RAMQ, ID Famille
- Famille
- ID Specimen
- Étude

**Ces colonnes seront décochées par defaut**

**Comment by denis-crsj** [comment]
Carte déplacée vers le Icebox de Notion
