### ISSUE TITLE
Montrer tous le filtres sauvegardés

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#346]
Page recherche de variant, liste des filtres sauvegardés. Présentement, celui en cours est enlevé de la liste ce qui fait que la liste change tout le temps lorsqu'on change de sélection. 
afficher toujours la liste complete

**Comment by denis-crsj** [comment]
@luclemo Je ne sais pas si je suis à la bonne place mais lorsqu'on sélectionne un filtre, il ne semble pas disparaitre mais semble plutôt être déplacé vers le haut de la liste. Est-ce que nous voulons modifier cela pour que les filtres restent au même endroit dans la liste ou ce comportement est adéquat ?

![image](https://user-images.githubusercontent.com/64538118/87979035-6cab5500-ca9f-11ea-9f25-e83c6cd3ca07.png)

**Comment by luclemo** [comment]
@denis-crsj en fait on parle ici des filtre savegardés:
![image](https://user-images.githubusercontent.com/1451515/88323528-5ea04300-ccf0-11ea-88d7-199652a8977e.png)

Le problème est que lorsqu'on on affiche un de nos filtres et que l'on reviens au menu du screenshot, le filtre "active" ne paraît plus dans la liste.

**Comment by denis-crsj** [comment]
Testé avec succès, le filtre sauvegardé actif apparait maintenant dans la liste correctement
