### ISSUE TITLE
Solution de sauvegarde temporaire de l'info du patient

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#354]
### Feature

Pour être en mesure de commencer à tester l'intégration de HAPI, nous devons mettre en place une solution temporaire permettant de récupérer les infos patient et les envoyer à HAPI d'une certaine manière.

Utiliser un server HAPI FHIR en local pour la sauvegarde. Voir projet clin-fhir-server pour le détail de la procédure pour en démarrer une instance locale avec docker-compose.

### Acceptance Criteria
N/A

### Resources
N/A

**Comment by denis-crsj** [comment]
@FrancisRenaud @plaplante-chust Il faudrait seulement décrire un peu la méthode qui sera utilisé ici. Je crois que vous aviez parlé d'une façon temporaire comme un JSON ou quelque chose du genre, je vous laisse ajouter les détails dans le ticket.

**Comment by plaplante-chust** [comment]
Utiliser un server HAPI FHIR en local pour la sauvegarde.  Voir projet clin-fhir-server pour le détail de la procédure pour en démarrer une instance locale avec docker-compose.

**Comment by plaplante-chust** [comment]
https://clin.ferlab.bio/fhir est maintenant disponible sur Collab
Il est également possible de lancer une instance de clin-fhir-server localement via docker-compose.
