### ISSUE TITLE
Mise à jour de Elastic Search à la version 7

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#356]
La mise à jour à la version 7 va demander d'ajuster les différents systèmes qui se connectent à ElasticSearch : clin-proxy-api + le processus d'indexation des variants.

À discuter avec Jeremy mais je crois que pour l'indexation des variants, une ré-écriture est déjà prévue.

**Comment by plaplante-chust** [comment]
La mise à jour à la version 7 va demander d'ajuster les différents systèmes qui se connectent à ElasticSearch : clin-proxy-api + le processus d'indexation des variants.  À discuter avec @jecos mais je crois que pour l'indexation des variants, une ré-écriture est déjà prévue.

**Comment by denis-crsj** [comment]
Mise à jour complétée
