### ISSUE TITLE
Variant Interpreter : améliorer l'affichage des conséquences

### ISSUE THREAD

**Issue by EmmyDx** [Ferlab-Ste-Justine/clin-project#358]
Voici le filtre appliqué:

![capture d'écran_1](https://user-images.githubusercontent.com/12585875/86625488-1fa18c00-bf93-11ea-9f07-d63bdb49ad26.png)

Lorsque le nombre de conséquences dépasse la 10ene, on ne voit pas toutes les conséquences de la modification (cf. la capture d'écran ci-dessous):
![capture d'écran_2](https://user-images.githubusercontent.com/12585875/86625607-55467500-bf93-11ea-85fd-0ed9a123f6ca.png)

## Solution possible
Afficher un nombre limité de conséquences (supposons 2 au maximum) et les autres avec la possibilité de dérouler la liste comme dans KF (cf. capture d'écran d'un exemple de KF):

![exemple](https://user-images.githubusercontent.com/12585875/86626331-8a06fc00-bf94-11ea-95f6-c7f0a8ca3341.png)

**Comment by denis-crsj** [comment]
@YanLabCHU Je ne vois pas le correctif de mon côté. Est-ce poussé en QA ?

**Comment by YanLabCHU** [comment]
@denis-crsj  Oui, maintenant ils sont tous affichés dans la colonne.

**Comment by denis-crsj** [comment]
@YanLabCHU L'objectif de la carte est en fait de faire le contraire :) On ne veut pas toute les voir dans la colonne ! Il faut en afficher une et mettre un icône "+" comme dans la capture d'écran.

**Comment by YanLabCHU** [comment]
@denis-crsj Je pensais que c'était juste une des solutions possible, pas forcément celle qu'on implémente. L'erreur c'était que la colonne n'affichait pas toutes les informations (Tu peux voir que ça coupe au milieu de la dernière ligne), pis ça c'est corrigé :)

**Comment by denis-crsj** [comment]
On peut fermer cette carte. En temps et lieu, si jamais on décide d'implémenter la solution proposée par Emma, nous pourrons le faire dans une nouvelle carte
