### ISSUE TITLE
Variant Interpreter: liste de certains filtres ne s'affichent pas

### ISSUE THREAD

**Issue by EmmyDx** [Ferlab-Ste-Justine/clin-project#359]
## Remarque relevée
La liste de certains filtres ne s’affiche pas (pas de scrollbar). Voici un exemple :

![liste valeurs filtre](https://user-images.githubusercontent.com/12585875/86627243-fb937a00-bf95-11ea-9c7b-4a1a8b1fad70.png)

Plusieurs filtres sont dans le même cas:
- Filtre Variants: onséquences (celui qui figure sur la capture d'écran ci-dessus), Chromosomes
- Filtre Génomique: Type de gene, Radboudumc et orphanet
- Filtre Impacts: evidence clinique (ClinVar)

## Solution
Mettre un scrollbar pour pouvoir accéder à toutes les valeurs

**Comment by denis-crsj** [comment]
Ce problème sera résolu automatiquement en réglant la carte 409 que @FrancisRenaud va s'occuper.
