### ISSUE TITLE
File repository: Change the way we display files that include multiple participants

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#360]
In the File Repository, we display files with multiple participants in the following way
![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/8e6342ba-fc85-48be-b6a7-6a1183ea1e53)

i.e with only one participant ID in the Participant column and with a series of Yes, No in the Proband column.

Fix: In both columns, display "Many"  when a file includes more than one participant.

**Comment by denis-crsj** [comment]
This card should be in KF instead, it was created here by mistake. Transferring card to the Icebox in Notion for now.
