### ISSUE TITLE
page variant - frequences cohorte interne: mettre la rangée total au bas du tableau en caractères gras

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#361]
dans le tableau suivant, la ligne sur le total devrait apparaître au bas du tableau. 
![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/b5185a64-0e1f-44ee-8929-19a3eaf5733d)
En caractère gras si possible

**Comment by denis-crsj** [comment]
Testé avec succès.
