### ISSUE TITLE
Page Variant - Associations cliniques: enlever les genes lorsqu'il n'y a pas d'associations

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#362]
lorsqu'un gène n'a pas d'association, ne pas afficher la ligne. Voir cette capture d'écran
![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/fc92bdcf-487e-4e9f-9313-accab69c5461)

**Comment by denis-crsj** [comment]
@vferretti Si jamais la section n'a pas de données, affichons nous quand même la section avec un message "aucune donnée disponible" ou nous n'affichons tout simplement pas la section ?

**Comment by denis-crsj** [comment]
Testé et fonctionnel pour l'instant. Si jamais nous voulons enlever la section lorsqu'il n'y a pas de résultats, nous pourrons toujours le faire dans une nouvelle carte
