### ISSUE TITLE
Internationalisation / Gestion des langues dans Keycloak

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#364]
### Feature

Pour le moment, les traductions sont gérées via des fichiers ".properties" dans le projet clin-keycloak-theme.

À considérer: une solution de gestion de traductions pour tous nos projets. Zanata?

### Acceptance Criteria

Toutes les pages en lien avec le login/authentification sont bilingues.

### Sub-Tasks
_List of what needs to be done  on the technical side._
- [ ] Sub-task 1
- [ ] Sub-task 2
- [ ] Sub-task ...

### Testing Strategy
_Who can test it? How do we test it? What do we need to test it?_

### Defects
_List of defects/bugs found during QA._
- [ ] Defect 1
- [ ] Defect 2
- [ ] Defect ...

### Resources
_Include any links to additional documentation, technical and/or design specs_

**Comment by plaplante-chust** [comment]
Pour le moment, les traductions sont gérées via des fichiers ".properties" dans le projet clin-keycloak-theme.
À considérer: une solution de gestion de traductions pour tous nos projets.  Zanata?

**Comment by denis-crsj** [comment]
@plaplante-chust De ce que j'ai vu, cela semble bien fonctionner. Je ferme la carte
