### ISSUE TITLE
Installer/Configurer serveur mail en QA

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#365]
Tel que discuté avec Jeremy et Éric, puisqu'il ne s'agit ici que d'un envoi de courriel ad-hoc (reset password), nous allons utiliser Gmail pour démarrer. On ajustera au besoin.

Donc, dans Keycloak, sélectionner le "realm" "Clin" - realm settings - email. Saisir l'info du serveur gmail.

**Comment by plaplante-chust** [comment]
Tel que discuté avec @jecos et @Magnitus- , puisqu'il ne s'agit ici d'un envoi de courriel ad-hoc (reset password), nous allons utiliser Gmail pour démarrer.  On ajustera au besoin.

Donc, dans Keycloak, sélectionner le "realm" "Clin" - realm settings - email.  Saisir l'info du serveur gmail.

**Comment by denis-crsj** [comment]
@jecos @Magnitus- Bonjour messieurs, quel est le statut sur cette tâche ? J'avais le feeling ça avait été fait non ?

**Comment by denis-crsj** [comment]
Bon je viens de tester l'envoi de courriel sur le site et ca marche alors je ferme la carte !
