### ISSUE TITLE
Dette Technique: clin-frontend - router

### ISSUE THREAD

**Issue by plaplante-chust** [Ferlab-Ste-Justine/clin-project#382]
@plaplante-chust commented on [Thu Jul 30 2020](https://github.com/Ferlab-Ste-Justine/clin-frontend/issues/246)

Voir s'il n'y a pas une façon plus efficace et moins "error-prone" de gérer les routes.  À chaque route ajoutée dans le  react-router, on doit modifier la méthode manualUserNavigation() du fichier router.js pour y ajouter une condition pour notre nouvelle route sinon, impossible d'etre redirigé directement sur la page (via un copy+paste de l'url, un bookmark, ou une redirection à partir de keycloak) - on sera redirigé sur /patient/search puisqu'on tombera dans le "else".

**Comment by denis-crsj** [comment]
Dette technique, je transfert au Icebox pour le moment
