### ISSUE TITLE
Amélioration de l’interface de soumission : ajout d’un champ qui indique la priorité d'une requête

### ISSUE THREAD

**Issue by EmmyDx** [Ferlab-Ste-Justine/clin-project#386]
## Description
Afin de pouvoir distinguer les requêtes prioritaires, le laboratoire a besoin que cette information soit disponible sur la formulaire adressé par le service de soin. Ceci conduira a l'application de la procédure "Génome Rapide" pour les requêtes indiquées comme urgentes, les autres faisant partie des prélèvements dits de routine.

La source FHIR de type ServiceRequest dispose d’ors et déjà d'un champ qui l'indique, reste alors a intégrer cette donnée a notre interface afin de pouvoir remplir ce champ.

**Comment by denis-crsj** [comment]
Cela sera ajouté dans un 2e temps. Je déplace la carte temporairement vers Notion pour focuser sur le MVP et nous pourrons la ramener en temps et lieu.
