### ISSUE TITLE
Amélioration de l’interface de soumission : possibilité pour l'utilisateur d'indiquer que c'est lui le médecin référent

### ISSUE THREAD

**Issue by EmmyDx** [Ferlab-Ste-Justine/clin-project#387]
## Description
Actuellement, pour le 3e onglet de l'application web permettant la soumission des données cliniques, on peut indiquer le médecin référent dans un champ dédié a la saisie de cette donnée:

![medecin_ref_soumission.png](https://images.zenhubusercontent.com/5c5c6036df0733a30555cc4e/ac57f2e8-eecd-4fd6-8448-a3e4e3dfd707)

On aimerait que l'utilisateur connecté puisse indiquer que c'est lui le médecin référent, via par exemple une case a cocher sans pour autant qu'il ait a sélectionner son nom dans la liste.

**Comment by denis-crsj** [comment]
Cela sera ajouté dans un 2e temps. Je déplace la carte temporairement vers Notion pour focuser sur le MVP et nous pourrons la ramener en temps et lieu.
