### ISSUE TITLE
Utilisation d'un serveur externe pour stocker les terminologies

### ISSUE THREAD

**Issue by EmmyDx** [Ferlab-Ste-Justine/clin-project#389]
## Description
Actuellement dans notre modèle de données qui repond au standard FHIR, les valeurs non connues dans HL7 et qui sont de type Coding ou CodeableConcept, comme par exemple les terminologies standards, sont stockées dans des sources de type CodeSystem. Ceci est pratique tant que le volumes des termes n'est pas conséquent, mais pour les terminologies comme HPO qui ont un gros volumes de valeurs, il est préférable d'avoir recours a un serveur externe pour stocker ces terminologies et obtenir en retour une URL qu'on pourra indiquer dans nos sources FHIR.

## Objectif
Deux serveur peuvent nous permettre de stocker les terminologies:
https://ontoserver.csiro.au/
https://smilecdr.com/docs/fhir_repository/terminology.html

Le but étant de tester chacun d'entre eux afin de sélectionner celui qui sera le plus pratique a utiliser pour stocker nos terminologies comme HPO ou MONDO

**Comment by denis-crsj** [comment]
Cela semble être une tâche d'analyse et/ou d'investigation. Je suggère de ne pas placer ce type de tâche dans le tableau mais plutôt de trouver un autre endroit pour garder ce type de tâches et ne pas les oublier. Notion serait surement un bon endroit pour cela, à voir...
