### ISSUE TITLE
Integrer les projets de recherche

### ISSUE THREAD

**Issue by EmmyDx** [Ferlab-Ste-Justine/clin-project#392]
Ceci necessite deux types de sources: ReserachSubject et ResearchStudy

**Comment by denis-crsj** [comment]
Cela semble être une tâche d'analyse et/ou d'investigation. Je suggère de ne pas placer ce type de tâche dans le tableau mais plutôt de trouver un autre endroit pour garder ce type de tâches et ne pas les oublier. Notion serait surement un bon endroit pour cela, à voir...
