### ISSUE TITLE
Amélioration des informations relatives a l'age d'apparition du phénotype

### ISSUE THREAD

**Issue by EmmyDx** [Ferlab-Ste-Justine/clin-project#398]
Dans le modèle actuel, nous disposons du descriptif (en anglais) de l’age d’apparition. L’idée est de trouver le moyen d'intégrer un champ dans notre modèle qui donne l'intervalle d’age qui sera par la suite l’affiché sur notre application

**Comment by denis-crsj** [comment]
Cela est plus une tâche d'analyse et/ou d'investigation. Je déplace dans Notion pour le moment.
