### ISSUE TITLE
Traitement des cas foetus et NNE

### ISSUE THREAD

**Issue by EmmyDx** [Ferlab-Ste-Justine/clin-project#400]
Le modèle de données doit couvrir les cas du fœtus et nouveau né
Rq : Pour le prélèvement fœtal, il faut préciser la DDR

**Comment by denis-crsj** [comment]
Cela semble être une tâche d'analyse et/ou d'investigation. Je suggère de ne pas placer ce type de tâche dans le tableau mais plutôt de trouver un autre endroit pour garder ce type de tâches et ne pas les oublier. Notion serait surement un bon endroit pour cela, à voir...
