### ISSUE TITLE
Mettre en place le service de recherche de médecin référent

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#414]
### Feature

Il faut faire fonctionner la barre de recherche de la page 3 du formulaire permettant de trouver et sélectionner le Médecin référent. La recherche doit pouvoir se faire par Nom ainsi que par # licence.

Le résultat sera le suivant --> _Dr. prénom nom [# licence]_

Il faut alors s'assurer que le service retourne toutes les informations requises. Les 3 champs se retrouvent dans la source FHIR "Practioner". Voir analyse pour plus d'infos : https://www.notion.so/ferlab/CLIN-Comptes-utilisateur-et-ACL-5bfc6908a3cc4267a633b3a1e6986c88.

Il y aura sans doute une validation du champs "Rôle" à faire également pour permettre de retourner l'info des médecins seulement.

### Acceptance Criteria
Appeler le service retourne toutes les infos nécessaires à l'affichage:
- Prénom
- Nom
- Numéro de licence

### Sub-Tasks
_List of what needs to be done  on the technical side._
- [ ] Sub-task ...

### Testing Strategy
N/A

### Defects
_List of defects/bugs found during QA._
- [ ] Defect ...

### Resources
Maquette Figma : https://www.figma.com/file/xEHYxOCLtFUISHLQXP0PZa/formulaire-soumission?node-id=393%3A9

**Comment by plaplante-chust** [comment]
Après discussion avec Lucas, le champ de recherche de médecin référant doit avoir le même comportement que la recherche de patient.

À clarifier:
1. Est-ce "case sentivie"
2. Est-ce que les accents sont ignorés?
3. Doit-on supporter le fuzzy logic?
4. Est-ce que le terme doit être recherché à n'importe quelle position? ex.: Medecin "Bouchard"  On cherche "bou" - on a un résultat.  Si on cherche "chard" - est-ce qu'on a un résultat?

@FrancisRenaud PTI.

**Comment by denis-crsj** [comment]
Voici les réponses basée sur le fonctionnement de la recherche patient:

1. Non, ce n'est pas case sensitive.
2. Les accents ne sont pas ignorés et sont pris en compte dans la recherche. Par contre, si un nom contient un accent, il ne ressortira pas dans les résultats si on ne le met pas, ce qui devrait à mon avis être corrigé. Nous devrions pouvoir trouver le nom même si l'accent est omis.
3. Le fuzzy logic n'est pas actuellement supporté mais si les efforts ne sont pas très grand. nous pourrions le mettre. Toutefois, si les efforts sont considérables, nous l'ajouterons dans une phase 2 comme amélioration.
4. Actuellement ce n'est pas le cas. Pour ce point, je validerais avec @luclemo car je ne sais pas s'il y aurait un danger d'avoir trop de résultats de recherche, ce qui n'aiderait pas l'utilisateur non plus. Exemple, rechercher "m" ressortirais tous les noms avec un "m"...

@plaplante-chust @FrancisRenaud

**Comment by plaplante-chust** [comment]
@denis-crsj concernant le point 4, en fait, faudrait simplement déterminer combien de résultats maximum on va renvoyer du backend.  10, 15, 20?  Perso, j'aurais tendance à y aller pour 10 et si l'utilisateur ne trouve pas ce qu'il cherche, c'est qu'il doit rafiner son critère de recherche.

**Comment by denis-crsj** [comment]
@plaplante-chust Après avoir discuté avec @luclemo, on ne veux pas intégrer cette fonctionnalité. La recherche doit se faire seulement par le début du nom et doit également se faire par le nom de famille seulement ainsi que le No. de licence. On ne veux pas être en mesure de chercher par le prénom.

@FrancisRenaud @YanLabCHU  FYI
