### ISSUE TITLE
Page 3 - Médecin référent - Affichage de la liste

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#424]
Une fois le service backend complété, il faut maintenant l'appeler et faire afficher la liste pour être en mesure de sélectionner un médecin.

Pour le fonctionnement des critères de recherches, voir la carte https://github.com/Ferlab-Ste-Justine/clin-project/issues/414.

### Visuel

Composant Ant à utiliser : https://ant.design/components/select/#components-select-demo-search
Maquette Figma : https://www.figma.com/file/xEHYxOCLtFUISHLQXP0PZa/formulaire-soumission?node-id=393%3A9

![image](https://user-images.githubusercontent.com/64538118/91563928-c0feeb80-e90d-11ea-9af5-bd3b55961999.png)

**Comment by plaplante-chust** [comment]
Hypothèse: recherche par nom, prénom et/ou numéro de license via FHIR
