### ISSUE TITLE
la création de rapport dans la page recherche de variants retourne un erreur

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#431]
- Aller dans la page de recherche de variants https://qa.clin.ferlab.bio/patient/PA14909/variant#
- Sélectionner un ou plusieurs variants et cliquer sur Créer rapport
Bug: retourne un message d'erreur
![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/54e9c4a2-44ad-41fe-b779-595a57516e8a)

**Comment by denis-crsj** [comment]
Problème résolu, le rapport se télécharge correctement sans message d'erreur
