### ISSUE TITLE
Formulaire - Bouton Annuler

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#449]
### Feature

Chaque page du formulaire a un bouton Annuler permettant à l'utilisateur d'annuler sa saisie de donner et quitter le formulaire. Lorsqu'on clique sur le bouton Annuler, une boite modale apparait à l'écran et avise l'utilisateur que sa progression sera perdue et lui demande de confirmer ou d'annuler pour retourner au formulaire. S'il quitte, il est redirigé vers la liste de Patients.

#### Composante

**Confirmation modal dialog**
https://ant.design/components/modal/#components-modal-demo-confirm

**Text**
- Titre : `Quitter sans enregistrer les modifications?`
- Content: aucun
- Boutons: `Annuler` et `Quitter`

![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/e2285222-1aba-40a3-bcaf-d4eb953d149e)

### Sub-Tasks
_List of what needs to be done  on the technical side._
- [ ] Clear state du formulaire pour éviter de récupérer des infos non voulues

### Testing Strategy
_Who can test it? How do we test it? What do we need to test it?_

### Defects
_List of defects/bugs found during QA._
- [ ] Defect ...

### Resources
_Include any links to additional documentation, technical and/or design specs_

**Comment by denis-crsj** [comment]
@luclemo Juste indiquer quel composant utiliser svp.

**Comment by luclemo** [comment]
@denis-crsj ✅

**Comment by jmalizia** [comment]
Lorsque je rentre les informations du patient ou suis dans le formulaire de prescription et que je clique "annuler", aucune boîte modal n'apparait. Je suis automatiquement rediriger vers la liste des patients.
J'utilise Chrome on Mac (v87.0.4280.66). 

- J'ai annulé après que j'ai sauvegardé le profil du patient (JJT MMT) puis j'ai annulé (sans cliqué suivant) = problème décrit présent
J'ai annulé après que j'ai sauvegardé le profil du patient (JJT2 MMT), fais annulé et remplis la prescription. J'ai sauvegardé la prescription puis j'ai annulé (sans cliqué suivant) = problème décrit présent

**Comment by jmalizia** [comment]
Tout fonctionne maintenant aux 2 pages (profil patient et prescription) tant en EN qu'en FR avec les bons textes
