### ISSUE TITLE
Sync clin to use global style/theme structure

### ISSUE THREAD

**Issue by francisl** [Ferlab-Ste-Justine/clin-project#453]
Match cross application base style/theme architecture

reference from KF https://github.com/kids-first/kf-portal-ui/tree/dev/src/style

- [ ] Rename directory structure
- [ ] Rename base style files
- [ ] Reference those file in project

**Comment by denis-crsj** [comment]
Je ferme pour l’instant, sera ré-ouverte sous peu si nécessaire
