### ISSUE TITLE
Formulaire de soumission: Texte par défaut manquant pour l'interprétation

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#462]
Il faut mettre le mot "interprétation" dans le dropdown par défaut. Voir maquette de Lucas
![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/6629f28b-9a6e-4dd3-b90e-41fe095ec275)

**Comment by denis-crsj** [comment]
Déjà mentionné dans #458, je vais donc fermer la carte
