### ISSUE TITLE
Formulaire de soumission: mot anglais dans la version française

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#463]
Mettre "Sans objet" dans la version française
![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/8b10946c-5985-4e42-9001-cacc04a17c59)

@YanLabCHU  est-ce que tu crée quand même une observation quand c'est sans objet?

**Comment by YanLabCHU** [comment]
@vferretti Yes!

**Comment by denis-crsj** [comment]
Correctif mentionné à la carte #458, je vais donc fermer celle-ci
