### ISSUE TITLE
Formulaire de soumission: les signes cliniques ne semblent pas obligatoire pour pouvoir passer à la page 3 du formulaire

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#464]
![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/727e8301-2546-4aa5-a0f0-e9003561b6ae)

**Comment by denis-crsj** [comment]
Déjà mentionné à la carte #461, je vais donc fermer la carte
