### ISSUE TITLE
Implémenter UI page Patient

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#491]
https://www.figma.com/file/Hvh1kY1o0rzzO89IuOYITP/CLIN---Page-de-patient?node-id=252%3A4586

### Defects
- [x] Le nom de famille du patient dans l’entête devrait être tout en majuscule
- [x] Le carré avec le nom du patient devrait être aligné avec le mot “Prescription” de la table de prescription en dessous résultant en une marge un peu plus large à gauche du carré
- [x] La couleur des en-têtes de colonnes pour le tableau de prescription devrait être #536377 et non #233750
- [x] L’icône de flèche à côté du dropdown menu “Actions” devrait être plus grosse
- [x] La présentation du nom du médecin est incorrect dans les pop-up "info", voir maquette.

### Screenshots
![image](https://user-images.githubusercontent.com/64538118/99453744-6a44f480-28f3-11eb-9c2b-495fed95dec3.png)

![image](https://user-images.githubusercontent.com/64538118/99453666-48e40880-28f3-11eb-8e89-dab5aedf0abe.png)

![image](https://user-images.githubusercontent.com/64538118/99453833-8b0d4a00-28f3-11eb-8c8b-1b43bfc28e3c.png)ç

![image](https://user-images.githubusercontent.com/64538118/99538350-d9196080-297a-11eb-8e42-f735ccfefddf.png)

**Comment by denis-crsj** [comment]
Quelques defects ont été ajoutés (voir description), je remet la carte en "In progress"

**Comment by jmalizia** [comment]
problèmes résolus, je ferme la carte
