### ISSUE TITLE
Implémenter UI page Patient - Onglet Clinique

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#492]
Implémenter UI page Patient - Onglet Clinique

### Defects
- [x] Dans le tableau des signes clinique, il faut afficher le nom du HPO en texte au lieu du ID
- [ ] La présentation du nom du médecin est incorrect, voir maquette
- [ ] La présentation du nom du médecin est incorrect dans le pop-up "info" également, voir maquette.

### Screenshots
![image](https://user-images.githubusercontent.com/64538118/99538001-5c868200-297a-11eb-988d-6623ca38f6a3.png)

![image](https://user-images.githubusercontent.com/64538118/99538140-863fa900-297a-11eb-8dc4-4eec1441bc21.png)

![image](https://user-images.githubusercontent.com/64538118/99537478-bd618a80-2979-11eb-8c42-7e4ab447e67a.png)

**Comment by denis-crsj** [comment]
J'ai noté quelques defects dans la description, je remet donc la carte en In Progress

**Comment by jmalizia** [comment]
1) afficher le nom du HPO et non l'ID -> régler
2) présentation du nom du médecin -> non corrigé voir screenshots (maquette vs CLIN présentement)**
3) non corrigé --> voir screenshots (maquette vs CLIN présentement)**
** le nom du médecin doit être afficher de façon constante à travers CLIN --> NOM, Prénom (aucun titre en préfix)
Maquette
![Screen Shot 2020-11-24 at 3 50 06 PM](https://user-images.githubusercontent.com/73133507/100151274-f8c6f200-2e6e-11eb-8a88-fd0de89f1148.png)

CLIN présentement - profil patient
![Screen Shot 2020-11-24 at 4 01 18 PM](https://user-images.githubusercontent.com/73133507/100151293-fc5a7900-2e6e-11eb-83b3-57899b8ed14d.png)

CLIN présentement - page patient
![Screen Shot 2020-11-24 at 4 00 55 PM](https://user-images.githubusercontent.com/73133507/100151613-63782d80-2e6f-11eb-94ad-0308a7a1ec4e.png)

**Comment by denis-crsj** [comment]
Après discussion avec Claudia, les règles d'affaires pour l'affichage avaient changé. je ferme donc la carte
