### ISSUE TITLE
Page de création de compte

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#493]
Implémenter le formulaire de création de compte basé sur la maquette UX Balsamiq et sur nos standard de design actuel (voir UI Kit Figma)

Mettre en place la gestion des pages non authentifiées dans clin-frontend (puisque la page de création de compte n'est pas authentifiée)

https://www.figma.com/file/FGI66deuiYLeiacJlAhd2C/Login-Flow?node-id=252%3A4586

**Design**
À discuter avec Claudia/Lucas avant implémentation

**Comment by plaplante-chust** [comment]
Implémenter le formulaire de création de compte basé sur la maquette UX Balsamiq et sur nos standard de design actuel (voir UI Kit Figma)

**Comment by francisprovost** [comment]
On hold jusqu'à l'update du backend

**Comment by jmalizia** [comment]
@francisprovost est-ce que c'est carte a été faite finalement?

**Comment by francisprovost** [comment]
Non c'est dans les prochains projets à faire tout ce qui est en lien avec la création de compte et la gestion de droits

**Comment by denis-crsj** [comment]
Je ferme pour l’instant, sera ré-ouverte sous peu si nécessaire
