### ISSUE TITLE
Création de compte - Créer service dans Clin Proxy API

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#494]
- Créer l'utilisateur dans FHIR et dans Keycloak
- Gestion des erreurs
- Gérer le rollback si l'insertion dans un des 2 système a échoué

**Comment by plaplante-chust** [comment]
N.B.: Pour appeler Hapi Fhir à partir de clin-proxy-api, on devra utiliser un auth token pour un service account défini dans keycloak.  Un appel à Keycloak devra être fait pour acquérir un token (en passant un client_id et un secret en paramêtre).  Les client_id et client_secret NE doivent PAS être hardcodés dans le code - ils doivent être passé en paramètre à l'application via des variables d'environnement.  On devra également gérer l'expiration de ce token (qui expire à un interval d'une minute présentement).

**Comment by denis-crsj** [comment]
Je ferme pour l’instant, sera ré-ouverte sous peu si nécessaire
