### ISSUE TITLE
Création de compte - envois email configuration du mot de passe

### ISSUE THREAD

**Issue by plaplante-chust** [Ferlab-Ste-Justine/clin-project#495]
### Feature

Lorsque l'administrateur CQGC (clin) se connecte à Keycloak pour valider le profile du "practitioner" et ACTIVER le compte, un email doit être envoyé au "practitioner" pour qu'il puisse configurer son mot de passe.  

Se baser sur le template de mail de reset password dans le thème keycloak (https://github.com/Ferlab-Ste-Justine/clin-keycloak-theme).

**Comment by denis-crsj** [comment]
Je ferme pour l’instant, sera ré-ouverte sous peu si nécessaire
