### ISSUE TITLE
Corriger ElasticsearchRestClientIntegrationTest

### ISSUE THREAD

**Issue by plaplante-chust** [Ferlab-Ste-Justine/clin-project#496]
**Bug description**

Le test ElasticsearchRestClientIntegrationTest ne test pas la bonne fonctionnalité.
L'insertion doit être faite dans Hapi Fhir et on doit ensuite valider que l'IndexerInterceptor Fhir a bien indexé le patient dans ES.

**Comment by denis-crsj** [comment]
Transféré au Icebox pour le moment
