### ISSUE TITLE
Touch-up visuel Onglet Variant - Footer en double

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#502]

**Comment by francisprovost** [comment]
@denis-crsj On a une liste de changements à faire quelques part?

**Comment by denis-crsj** [comment]
@francisprovost Il semble que la plupart des petits glitchs aient été corrigé avec la carte #508 mais il resterait le footer qui apparait en double sur la page à corriger svp.

**Comment by francisprovost** [comment]
@denis-crsj Je règles ce problème en même temps que de faire #504. On peut probablement closer cet issue alors

**Comment by denis-crsj** [comment]
Après discussion, il semble que ce glitch sera réglé en même temps que la #504. Je ferme donc cette carte
