### ISSUE TITLE
Forgot password screen: fix background image

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#503]
fix background image to behave like the login screen (I suspect this issue is also present on the other login flow screens)

![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/a96a2e7a-19df-4110-b59d-e1521f7cbf40)

**Comment by jmalizia** [comment]
l'image réagit maintenant comme celle du login. Je ferme la carte
