### ISSUE TITLE
Tableau vide dans la page variantes

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#506]
**Bug description**
La page variant affiche un tableau vide pour les patients. 

**Steps To Reproduce**
1. Go to patients' list
2. Click on a patient
3. Click on 'Variants' tab
4. See empty table

**Expected behavior**
Tableau devrait être populé par la liste des variantes.

**Comment by denis-crsj** [comment]
Le problème semble résolu. Le tableau Variant reste remplit correctement
