### ISSUE TITLE
Fixer le status dans la liste des patients

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#511]
**Frontend**: 
- La valeur du status doit être traduite
- La bonne couleur doit être assignée

**Backend**: 
- Le status d'un patient dans être soit draft, active, on-hold, revoked, completed, entered-in-error ou unknown.

**Comment by jmalizia** [comment]
Quelles sont les couleurs de ses statuts car il ne sont pas listés dans la spec:
- entered-in-error 
- unknown
