### ISSUE TITLE
Loading element position

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#512]
**Bug description**
Le loading element est en haut.

**Steps To Reproduce**
1. Go to 'patient list'
2. Click on 'any patient'

**Expected behavior**
Le loading element devrait être au centre

**Screenshots**
![loading-bug.png](https://images.zenhubusercontent.com/5f313d03d7df470e8324c4c8/9d90b1ee-32c2-4c91-bc88-cbb2f785fe9a

**Comment by francisprovost** [comment]
Le problème semble avoir été réglé
