### ISSUE TITLE
Page variant : Ajouter le champs AN pour les frequences des cohortes externes

### ISSUE THREAD

**Issue by jecos** [Ferlab-Ste-Justine/clin-project#519]
Dans la page d'un Variants> Onglet `Frequences` dans le tableau `Cohortes externes`on affiche uniquement les champs AF et AC. Hors, nous pouvons aussi afficher le champs AN. 

Sous-taches :

- [x] Indexer les champs AN pour les cohortes gnomad, topmed et 1000 genomes
- [x] Modifier le mapping dans clin-proxy-api
- [x] Afficher les champs dans le tableau dans clin-frontend
- [x] Modifier "LDM" par "Cohorte"

**Comment by denis-crsj** [comment]
tout semble avoir été ajouté
