### ISSUE TITLE
Tableau de variants - Effet de lenteur

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#524]
@luclemo À discuter. Possible que ce soit un problème de perception à cause de l'icône de chargement. Autres façon de possible de gérer le chargement ?

loader des placeholder à la place ? (Ex : https://codepen.io/Kaladan/pen/yjgzEo)

**Comment by vferretti** [comment]
j'enleverais carrément l'icone de chargement

**Comment by luclemo** [comment]
Avons-nous d'abord déterminer la raison de la lenteur? Car ces icônes ont une très bonne raison d'être pour indiquer au user qu'une opération est en cours lorsqu'il y a un petit délais. Sinon il peut penser que qqchose est brisé (et le temps perçu est plus long).

Par contre, c'est certain que les délais en question sont sensé être exceptionnels. Si on a ce genre de lenteur à chaque opération le problème ce trouve ailleurs.
