### ISSUE TITLE
Traduction termes français - Libellés

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#525]
Passer au travers de chaque pages et s'assurer de traduire tout les libellés en français.

**Comment by jmalizia** [comment]
Ajout d'une nouvelle erreur de libellé en FR dans le profil du patient

"Soumis le" devrait être "Soumise le" puisque c'est une prescription qui est soumise

"Soumis par" devrait être "Soumise par" puisque c'est une prescription qui est soumise
<img width="384" alt="Screen Shot 2020-12-09 at 10 56 11 AM" src="https://user-images.githubusercontent.com/73133507/101653401-49ad1d80-3a0d-11eb-8419-f23885b155f5.png">

manque l'accent circonflexe sur le o d'hopital -> devrait être "Hôpital"
<img width="168" alt="Screen Shot 2020-12-09 at 10 58 06 AM" src="https://user-images.githubusercontent.com/73133507/101653557-6f3a2700-3a0d-11eb-984e-02b8fc0a4d2f.png">

**Comment by jmalizia** [comment]
fixed!
