### ISSUE TITLE
Aucun résultat HPO disponible dans la barre de recherche “quick filter”

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#531]
### DEFECTS
- [ ] Lorsque je tape un terme HPO dans la barre, ca marque qu'il y a un nombre de résultats mais les résultats ne s'affichent pas et on ne peut pas cliquer sur le nombre de résultats

![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/a46a911d-b422-4739-a7e0-60868a9afb84)

**Comment by denis-crsj** [comment]
@francisprovost Lorsque je tape un terme HPO dans la barre, ca marque qu'il y a un nombre de résultats mais les résultats ne s'affichent pas et on ne peut pas cliquer sur le nombre de résultats

**Comment by francisprovost** [comment]
Étrange. Je vais regarder, peut-être un un problème avec tout les changement qu'il y a eu depuis

**Comment by francisprovost** [comment]
Le problème est lié à #580 . Je vais mettre mon travail sur l'autre issue et mettre à jour celle-ci (#530) quand #580 sera terminé

**Comment by denis-crsj** [comment]
Corrigé.

**Comment by denis-crsj** [comment]
@francisprovost Finalement, il semble que si on veut annuler la recherche, il soit impossible de fermer la boite à part que par en cliquant sur le "x". Même en cliquant sur d'autres filtres la boite de recherche reste ouverte. Je crois qu'il faudrait surement que le boite se ferme si on clique à l'extérieur de celle-ci
