### ISSUE TITLE
Arrondir la valeur dans la colonne gnomAD

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#535]
Il faut arrondir le chiffre à **4 décimales après la virgule**.

![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/600749aa-8b24-4716-bfd0-0cb3478e9763)

**Comment by vferretti** [comment]
3 décimales

**Comment by denis-crsj** [comment]
la valeur est maintenant arrondie
