### ISSUE TITLE
Filtre HPO - Les boutons Aucun / Observés / Non-observés ne fonctionnent pas

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#541]
Les boutons Aucun / Observés / Non-observés ne fonctionnent pas. Seul le bouton "Tout sélectionner" fonctionne.

Il faut modifier pour que lorsque nous cliquons sur "Observés" ou "Non-observés", les items qui sont sélectionnés soient remontés vers le haut de la liste. Sinon, il est difficile, voir impossible, de savoir si des valeures ont bel et bien été sélectionnées.

![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/c9dca591-b3dc-47fa-9d8a-7052c8d35bf6)

### DEFECTS
- [ ] Bouton "non-observés" ne fonctionne pas

**Comment by denis-crsj** [comment]
@luclemo Salut. Serait-ce possible de détailler le fonctionnement voulu

**Comment by luclemo** [comment]
Je penses que tu a bien résumé la chose. J'en avais aussi parlé live à @YanLabCHU et il semblait bien comprendre.

---

**On clique sur "observé":**
- Tous les signes observés sont remontés en haut de la liste en mode "checked"

**On re-clique sur observé:**
- Tous les signes observés qui sont "checked" sont alors "unchecked"

☝️ Même méchanique pour les signes non-observés. 

---
**On clique sur "observé ET non-observé":**

- Dans ce cas, on fait la même méchanique que le premier use-case, mais dans l'ordre chronologique des actions.

**Comment by luclemo** [comment]
Dernier point @denis-crsj il faudrait faire une carte (si ce n'est pas déjà fait) pour ramener l'affichage des petits points rouge er verts pour le valeur observés/non-observés. Ils ont disparus…

**Comment by denis-crsj** [comment]
@YanLabCHU Le bouton "Observés" fonctionne mais "non-observés" ne semble pas fonctionner, rien ne se produit lorsqu'on le clique

**Comment by denis-crsj** [comment]
Après révision, ca fonctionne correctement. le bug soulevé est un autre problème qui sera traité dans une autre carte
