### ISSUE TITLE
Position du footer change en passant d'une tab à une autre

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#542]
**Bug description**
Dans la page patient, lorsqu'on clique sur l'onget `Clinique` est que le height de la page est différent, le footer change de position pour s'aligner plus en bas. En revenant sur l'onglet précédent `Patient`, le footer est encore tout en bas.

**Steps To Reproduce**
1. Aller dans la liste des patients
2. Clique sur une fiche patient qui est 'Soumise'
2. Clique sur l'onglet 'Clinique'
3. Note que le footer a changé de position
4. Clique sur l'onglet 'Patient'
4. Le footer est toujours en bas.

**Expected behavior**
En discussion avec @luclemo pour savoir c'est quel behavior qu'on souhaite avoir.

**Comment by luclemo** [comment]
@YanLabCHU C'est parce que lorsque lorsqu'on passe d'un onglet à un autre, on n'a pas un vrai page refresh donc on n'a pas une réinitialisation du scroll bar. Le problème se pose sur un laptop, mais pas sur un écran de 24" je pense. Je ne suis pas certain s'il y a un work-around pour ça vue qu'un scroll se réinitialise on load 🤷‍♂️ ?

**Comment by luclemo** [comment]
@YanLabCHU est-ce que ce serait qqchose qu'on peut régler avec `react-sticky`? https://ant.design/components/tabs/#components-tabs-demo-custom-tab-bar

**Comment by YanLabCHU** [comment]
@luclemo ça ressemble à ça le sticky https://react-sticky.netlify.app/#/basic, je pense que c'est plus utilisé pour que le header soit sticky si tu scroll.
Je pensais régler ça avec un minimum height pour les `<TapPane>` t'en penses quoi?

**Comment by luclemo** [comment]
Oui c'est une option... honnêtement ce que j'aimerai voir c'est le header qui prend sa place, le footer pinned en bas et le content qui prend le reste.

Qqchose comme `flex:1` ou `1fr` (si grid) pour le content qui se rafraîchi entre les tabs, mais je ne sais pas si c'est possible. Anyway, fais comme tu pense est le mieux… ce n'est pas qqchose tellement important pour passer une demi-journée! 👍

**Comment by denis-crsj** [comment]
nous allons toucher la page patient pour des modifications qui régleront sans doute le problème.
