### ISSUE TITLE
Page variant : filtre sur les score remonte les variants qui n'ont pas de valeur pour le score filtré

### ISSUE THREAD

**Issue by jecos** [Ferlab-Ste-Justine/clin-project#543]
**Bug description**
Quand on filtre par un score (ex.:CADD) alors on a bien les variant pour lesquels le score est dans l'intervalle, mais on a aussi ceux qui n'ont pas de valeur pour ce score :

**Steps To Reproduce**
1. Aller sur la page Variant de [PA0046](https://qa.clin.ferlab.bio/patient/PA0046/#variant) 
2. Clicquer sur `Impacts`, puis `CADD`
3. Changer min et max pour 0.5 et 0.8
4. Cliquer sur Appliquer
5. Dans le tableau on voit bien les variants qui ont un score CADD compris entre 0.5 et 0.8, mais on voit aussi les variants sans score CADD

**Screenshots**
<img width="1625" alt="CADD_issue" src="https://user-images.githubusercontent.com/1424506/100471740-e9cb8400-30a8-11eb-9085-a9db3bbfd3e6.png">

**Comment by denis-crsj** [comment]
Les variants sans score n'apparaissent plus. problème résolu.
