### ISSUE TITLE
Page recherche variant : Impossible de chercher par gene

### ISSUE THREAD

**Issue by jecos** [Ferlab-Ste-Justine/clin-project#545]
**Bug description**
Lorsqu'on cherche des variants par gene, la liste retournée est toujours vide

**Steps To Reproduce**
1. Aller sur la page de variant d'un participant : https://qa.clin.ferlab.bio/patient/PA0046/#variant
2. Ouvrir la facette `Genomique`
3. Dans le champs texte, saisir un gene qui est present dans la liste des variants (ex.: `KRTAP2-2`), puis selectionner le gène
4. La liste des variants est vide

**Expected behavior**

**Comment by denis-crsj** [comment]
@jecos De mon côté la liste des variant est toujours vide après avoir sélectionné le gêne dans la barre de recherche, je remet donc la carte dans "In progress"

**Comment by denis-crsj** [comment]
C'est réglé.
