### ISSUE TITLE
Page detail variant : les consequences devraient etre regroupé par type de consequence 

### ISSUE THREAD

**Issue by jecos** [Ferlab-Ste-Justine/clin-project#546]
Dans cette page :

https://qa.clin.ferlab.bio/variantDetails/016e6db5d4ddf1f43fb1732ea25d538852b5e178/#summary

On voit qu'il y a plusieurs consequences pour le meme transcript.

Les lignes devraient etre regroupées par gène, brin, impact et transcript. La colonne conséquence devrait etre une liste de valeur (représentées dans le ui par differentes lignes dans la colonne)

- [x] Modifier l'index pour regrouper les consequences
- [x] Dans le UI des pages variants (liste et détail), gérer le champs consequence comme une liste

**Comment by jecos** [comment]
L'index a été modifié (variants_bt_bat1_re_003)

**Comment by jmalizia** [comment]
incapable de voir si le problème est réglé
