### ISSUE TITLE
Page patient: Ne pas afficher les tableaux et les sections s'ils sont vides

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#549]
comme par exemple ici
![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/c4dfbb7b-5511-46f8-a166-50991b3233fb)

**Comment by jmalizia** [comment]
valider plusieurs cartes et les sections des signes cliniques n'apparaissent plus si elles sont vides
