### ISSUE TITLE
Page de recherche de variants: la dernière ligne du tableau semble tronqué et il n'y jamais de bordure horizontale

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#552]
Des fois la ligne est complète lorsqu'on joue avec le scrollbar

![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/1be3ab84-2592-49cd-a833-ecc7ad281b6d)

**Comment by denis-crsj** [comment]
Difficile à reproduire car bug intermittent. Déplacé dans le Icebox pour le moment car bug mineur
