### ISSUE TITLE
Page de recherche de variant: Réinitialisation du choix des colonnes ne fonctionnent pas. 

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#553]
La première ligne est aussi vide. 

![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/06c20c03-79d0-4e46-ac49-87b9850730b7)

**Comment by jmalizia** [comment]
problème réglé, toutes les colonnes apparaissent et se rafraichissent selon ce que je coche/décoche
