### ISSUE TITLE
Page de recherche de variants: Mauvais comptes dans les facettes

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#554]
Aller à https://qa.clin.ferlab.bio/patient/PA0039/#variant

Appliquer le filtre mgst3 

Cela trouve un seul variant qui n'est pas dans clinvar et qui n'est pas dans pubmed d'après le tableau de résultat. POutant quand on ouvre la facette Réference externe, cela dit que ce variant y est. 

![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/13946f64-567a-40a6-81d4-1033d681f72c)

**Comment by denis-crsj** [comment]
Je ferme pour l’instant, sera ré-ouverte sous peu si nécessaire
