### ISSUE TITLE
Bouton back et onglets de page

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#555]
Le bouton Back nous retourne à l'onglet précédemment visité. Est-il possible que le bouton Back retourne à la page précédente? Si trop compliqué, on laisse faire

**Comment by francisprovost** [comment]
Effectuer ce changement nous ferait probablement perdre quel tab nous étions quand on fait back dans la page de variant. (Ou du moins on aurait un flow un peu étrange ou la première tab loaderait et ensuite on bougerait sur la dernière visité)

Si on veut la possibilité de revenir à la recherche de n'importe quel tab, on pourrait ajouter un bouton "retour" ou un breadcrumb qui pourrait facilité le retour.

**Comment by denis-crsj** [comment]
Improvement qui n'est pas critique pour le moment alors je vais bouger au Icebox temporairement
