### ISSUE TITLE
Recherche des variants: Ajuster le nom des facettes (surement dans la BD à l'étape de l'ETL ?)

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#556]
Facette variant.Référence externe
Mettre dbSNP,  ClinVar, OMIM.  (respectez la case des lettres)

Facette genomique.Référence externe
Mettre OMIM, Orphanet, HPO

Facette Impact.Evidence clinique (Clinvar)
Remplacez les soulignés par un espace blanc entre les mots
ATTENTION: on a les valeurs "association" et "_association" @jecos Peux-tu regarder stp?
Mettre tout en lettre minuscule.

Catégories de scores FATHMM, SIFT, Polyphen2 HVAR, LRT. 
Mettre les mots complets

**Comment by denis-crsj** [comment]
Je ferme pour l'instant, la carte sera ré-ouverte en temps et lieu
