### ISSUE TITLE
Page de recherche de variants: Changer l'action après la suppression d'un filtre

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#557]
- Aller à la page de recherche de variant pour un patient donné
- Ouvrir un filtre sauvegardé quelconque
- Cliquer sur "Supprimer"
-> La liste des filtres apparaît de nouveau. 
On devrait plutôt afficher simplement la liste des variants sans aucun filtre appliqué

**Comment by jmalizia** [comment]
Lors de la suppression du filtre, le reset des variants est exécuté, mais je neux pas pas tout simplement enlever le filtre à moins de le supprimer ou d'en définir un autre
![Screen Shot 2020-12-16 at 3 24 47 PM](https://user-images.githubusercontent.com/73133507/102402516-e2660f00-3fb2-11eb-919e-6724b390b59c.png)
