### ISSUE TITLE
Onglet Recherche de variants: Le menu des filtres ne disparaît pas automatiquement

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#558]
- Ouvrir le menu Impacts.Evidence clinique (Clinvar) par exemple
- Choisir une valeur et cliquer Appliquer
-> le filtre s'applique  mais le menu "Impacts" reste ouvert. 
Fermer tous les menus après avoir cliquer sur "Appliquer"

**Comment by denis-crsj** [comment]
Les menus se ferment maintenant correctement.
