### ISSUE TITLE
Page Patient, onglet Variant: La duplication d'une requête ne fonctionne pas

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#559]
- Allez à l'onglet Variant pour un patient qui a des variants
- écrire une requête quelconque, (ex. Impacts.SIFT = T) qui retourne une liste de variants non vide
- Dupliquer la requête en cliquand sur l'icone "Dupliquer" à droite de celle-ci (voir capture d'écran plus bas)
-­> La requete dupliquée ne retourne aucun résultats c-à-d aucun variant

![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/5626d646-9d01-4e5c-a8e7-62d3a72bae02)

**Comment by denis-crsj** [comment]
la duplication fonctionne maintenant correctement
