### ISSUE TITLE
Page Patient, onglet Variant: mettre le nombre de variant à coté du titre de l'onglet Variants

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#560]
Mettre entre parenthèses le nombre de variants dans la liste ((25) dans l'exemple suivant)

![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/ff0721c4-530f-4768-b133-bdcbd91449d4)

### DEFECTS
- [x] Il faut mettre le nombre total de variants pour la requête active et non pas seulement le nombre de variants dans la page même. Voir imprime-écran

**Comment by denis-crsj** [comment]
le chiffre est maintenant le bon
