### ISSUE TITLE
Ouverture de l'onglet Variant étrange

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#561]
Ouverture de l'onglet Variant vraiment bizarre. Il semble que la page apparait et qu'ensuite elle reload immédiatement une 2e fois.

Voir vidéo
https://www.dropbox.com/s/n6sihg8njhf5vpd/weird.mp4?dl=0

**Comment by jmalizia** [comment]
problème réglé. Ferme la carte
