### ISSUE TITLE
Page Patient, onglet Variant: Corriger les rapports selon les spec

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#563]
Les rapports générés ne suivent plus les spécifications. C'était le cas avant. 
Corriger selon les specifications décrites dans ce document
https://docs.google.com/document/d/1nBxhbUui-bHy2E4PCtGSy239-vos1MjYoBs4jM2aCPo/edit#heading=h.hejj8miepfuy

**Comment by denis-crsj** [comment]
Les spécifications pour le rapport ne sont pas très clair alors il est difficile de valider si le résultat est conforme ou non. Il faudrait avoir un jeu de donnée ainsi qu'un exemple clair de résultat contre quoi le valider. Je vais devoir prendre le temps de comprendre les spécifications avant tout.
