### ISSUE TITLE
Page variant : un b apparait dans lautocomplete des genes

### ISSUE THREAD

**Issue by jecos** [Ferlab-Ste-Justine/clin-project#564]
**Bug description**
un b apparait dans lautocomplete des genes

**Steps To Reproduce**
1. Aller dans la page de recherche de variant pour un patient
2. Cliquer sur Génomqiue
3. Dans le champs texte saisir 3 lettres qui correspondent à un gene (ex.: `PAB`)
4. Dans l'autocompletion on voit un `b` pur chaque gene retournée

**Screenshots**
![Screen Shot 2020-12-02 at 1.44.31 PM.png](https://images.zenhubusercontent.com/5cab6ac920cddd7cf9ba5b40/8e10b126-ffcf-4b9d-b4e0-d9e95c6179ae)

**Comment by denis-crsj** [comment]
le "b" n'apparait plus
