### ISSUE TITLE
formulaire de soumission clinique: Le résumé n'est pas sauvegardé

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#565]
Créer un patient et remplir le champ  "Résumé" de la deuxieme page du formulaire, section Résumé de l’investigation 
Faire suivant
Faire précédent
le résumé a disparu. 

Faire le meme exercise et au lieu de faire suivant, faire sauvegarder. Ouvrir la page du patient dans une autre fenetre, le résumé n'est pas là.

**Comment by denis-crsj** [comment]
@YanLabCHU Le problème est fixé lorsqu'on fait suivant et back mais si je clique sur "Continuer le formulaire" et que j'ajoute du texte dans la case, Sauvegarde et quitte ensuite, lorsque je reviens de nouveau pour éditer la prescription, le champs est revenu vide

**Comment by jmalizia** [comment]
Bug réglé. La sauvegarde se fait correctement dans les boîtes de textes "Résumé" et "hypothèse(s) de diagnostics"
