### ISSUE TITLE
Liste des patients [pagination du tableau] - Changer le nombre de patient pas page ne fonctionne pas

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#568]
On ne peut pas changer de valeur dans le select
![Pasted_Image_2020-12-02__3_49_PM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/36fc4594-0504-4967-98ba-1769f5f3801e)

**Comment by jmalizia** [comment]
Maintenant capable de changer le nombre d'item par page et tout se réajuste correctement.
