### ISSUE TITLE
Listse de patients - Les choix de colonnes ne sont plus enlignés

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#569]
Les éléments doivent être pleine largeur et les cases à cocher doivent être alignées à droite

![Pasted_Image_2020-12-02__4_07_PM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/92d26983-e11d-4082-ad61-462b4b9f9e2c)

**Comment by denis-crsj** [comment]
tout est maintenant bien aligné
