### ISSUE TITLE
Page patient - désactiver l'animation des tabs

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#570]
Actuellement, lorsque nous passons de l'onglet patient à l'onglet clinique par exemple, le contenu s'anime par les côtés.
Utilisez plutôt la transition par défaut: https://ant.design/components/tabs/#components-tabs-demo-basic

**Comment by denis-crsj** [comment]
L'animation est maintenant celle par défaut
