### ISSUE TITLE
Page variant - la sélection d'une requête déclenche un soulignement du bouton union

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#572]
![Pasted_Image_2020-12-02__5_59_PM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/f9019cfe-8f6c-49e1-8837-20dbe8b9a13a)

**Comment by jmalizia** [comment]
problème réglé. le soulignement de l'union ne se fait plus (reste grisé)
