### ISSUE TITLE
Pour une prescription déjà créee, lorsque qu'on quitte, nous sommes redirigés vers la page de recherche des patients

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#573]
**Bug description**
Lorsque je quitte une prescription en brouillon, je retourne à la page de patient plutôt que de rester dans le profil du patient.

**Steps To Reproduce**
1) ouvrir un profil patient
2) je continue de "compléter une prescription"
3) lorsque je clique sur annuler et confirme en cliquant sur quitter -> revient vers la page de recherche des patients

**Expected behavior**
Devrait rester dans le profil patient. Ce behavior sera d'autant plus utile lorsque les patients pourront avoir N prescriptions

**Screenshots**
![Screen Shot 2020-12-02 at 11.36.03 AM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/dd49cdd3-aa5b-4ceb-afa7-c22650ea139a)
![Screen Shot 2020-12-02 at 11.36.08 AM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/8d0eb9eb-1854-463d-8c9d-78b5b544c187)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser = chrome
 - Version 87.0.4280.67

**Comment by denis-crsj** [comment]
fixé.
