### ISSUE TITLE
Texte du “Résumé de l’investigation” ne se sauvegarde pas

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#575]
**Bug description**
Lorsque l’on met du texte et sauvegarde la page 2, puis que nous faisons soit suivant ou précédent et que nous revenions à la page 2 encore, le texte mis dans la boite Résumé de la section “Résumé de l’investigation” disparait

**Steps To Reproduce**
1) ouvrir un profil patient
2) je continue de "compléter une prescription"
3) je vais à la page 2 et inscrit du texte dans la boîte de texte "Résumé" de la section "Résumé de l’investigation"
4) je sauvegarde
5) j'appuie sur suivant (page 3) ou précédent (page 1) et reviens à la page 2c -> le texte n'est p

**Expected behavior**
texte inscrit devrait rester dans la boîte une fois sauvegardé

**Screenshots**
![Screen Shot 2020-12-03 at 9.46.41 AM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/5809c8eb-9bcc-4a28-b7f9-a64c462015c3)

![Screen Shot 2020-12-03 at 9.47.03 AM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/59dee796-28ae-483f-a4da-6459fa9369f7)

![Screen Shot 2020-12-03 at 9.47.15 AM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/55e9a5d8-e588-4f56-8d07-7955d34ebb48)

**Desktop (please complete the following information):**
OS: MacOS 10.15.7
Browser = chrome
Version 87.0.4280.67

**Comment by YanLabCHU** [comment]
duplicate #565 ?

**Comment by jmalizia** [comment]
yes duplicate
