### ISSUE TITLE
List des patient et variant - popover a un shadow sur un autre container

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#577]
Le shadow du popover devrait être directement au dessus de la liste des patient, et non pas au dessus d'un autre container.

![afficher-popover.png](https://images.zenhubusercontent.com/5f313d03d7df470e8324c4c8/4ac0fb85-51a8-426f-99a9-4b2ac75a87c1)

**Comment by denis-crsj** [comment]
fixé
