### ISSUE TITLE
Affichage des petits points rouge er verts pour le valeur observés/non-observés

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#581]

**Comment by denis-crsj** [comment]
@YanLabCHU Où ? Dans la page des variants dans la colonne conséquence ?

**Comment by denis-crsj** [comment]
@YanLabCHU Ok j'ai trouvé ou, dans le menu des filtres. Impossible de confirmer que tout marche car le bouton "non-observés" ne marche pas mais pour le point vert ca fonctionne. Restera juste à confirmer que les points rouges apparaissent également
