### ISSUE TITLE
Mettre à jour les données du patient après avoir sauvegardé et cliquer sur annuler 

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#583]
Pour le moment, lorsqu'on clique sur un patient (en brouillon), clique sur Compléter le formulaire et change ses infomrmation, sauvegarde puis clique sur annuler, on revient dans la fiche du patient, mais avec les information obsolètes.

**Comment by jmalizia** [comment]
problème réglé. La modification d'information sur un formulaire d'un patient en "brouillon" est sauvegardée correctement et s'affiche bien dans le profil patient et la page patient par la suite.
