### ISSUE TITLE
Label des signes cliniques est manquants 

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#584]
**Bug description**
Label des signes cliniques est manquants 

**Steps To Reproduce**
1. Go to patient ID 2713 (Harvey QA)
2. Click on tab "Clinique" and then on "Compléter le formulaire"
3. Saved the profil and click on next to get to page 2
4. I filled in some info and at the bottom I cannot see the labels for the "signes cliniques". If I open up the tree, I can see the banches' labels but for not the main ones. I also did a search and could see and it properly selected the signs I had entered

**Expected behavior**
Should see the main clinical signs' labels

**Screenshots**
![Screen Shot 2020-12-09 at 1.37.09 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/67231a29-0f50-47bd-a8e7-9d1834c8a29e)
![Screen Shot 2020-12-09 at 1.37.14 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/220752b2-62d6-49ca-82cc-d6c05acab394)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Macbook Pro 13"
 - OS: MacOS 10.15.7
 - Browser Chrome for Mac
 - Version 87.0.4280.88 (latest version)

**Comment by YanLabCHU** [comment]
duplicate #585
