### ISSUE TITLE
Page recherche de variants: Changer le nombre de variant par page ne fonctionne pas

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#586]
Rien ne change lorsqu'on clique sur le menu pour changer le nombre de variantes par page

**Comment by denis-crsj** [comment]
Ca fonctionne bien maintenant.

Il faudra sans doute un peu addresser le comportement du tableau lorsqu'on change de page avec 200 résultats par page, le délais est un peu long et on devrait, à mon avis, ramener l'utilisateur en haut du tableau mais on pourra addresser dans une autre carte
