### ISSUE TITLE
Page de recherche patient: toute la page se rafraichit après avoir cliquer sur réinitialiser

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#587]

**Comment by jmalizia** [comment]
Problème persistent. 
Je suis sur Chrome 87.0.4280.88
J'ai modifié les colonnes d'affichages (ajouté 2 et déplacer 2 supplémentaire). En réinitialisant, la page reste sur la page de refresh et n'en sort jamais. Lorsque je reclique sur mon favorites du site CLIN, je retombe sur la page de recherche des patient réinitialiser.
![Screen Shot 2020-12-16 at 4 29 25 PM](https://user-images.githubusercontent.com/73133507/102408627-e4809b80-3fbb-11eb-8299-fba94ec98f91.png)

**Comment by YanLabCHU** [comment]
J'arrive pas à reproduire

**Comment by denis-crsj** [comment]
De mon côté je suis incapable de reproduire le bug sur Chrome ainsi que sur Firefox après plusieurs essais. Étant donné que ca semble être un bug plutôt difficile à reproduire et peut-être aussi intermittent, je suggère de fermer la carte pour le moment et on verra si le problème revient.
