### ISSUE TITLE
Plusieurs filtres (Exemple filtre FATHMM): les valeurs ne s'ajoutent pas à la requête

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#588]
Lorsque je choisi T ou D, rien ne s'ajoute à la requête

![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/6711ee49-f22b-4a09-ac29-c6ec97be7c6b)

**Comment by jmalizia** [comment]
semble s'appliquer, mais est-ce possible que certains impacts FATHMM on les 2 types (T et D) car je n'arrive pas aux même chiffres?
quantité pour chacun + somme des 2
![Screen Shot 2020-12-16 at 12 30 42 PM](https://user-images.githubusercontent.com/73133507/102404242-67522800-3fb5-11eb-8497-2c10c30c5f71.png)
![Screen Shot 2020-12-16 at 12 31 39 PM](https://user-images.githubusercontent.com/73133507/102404325-8fda2200-3fb5-11eb-9085-84e8db61c910.png)
mais je n'ai que 576 pages (à 15 items chaque et la dernière n'en a que 4)
![Screen Shot 2020-12-16 at 12 31 54 PM](https://user-images.githubusercontent.com/73133507/102404389-aaac9680-3fb5-11eb-9049-c49e96488f2a.png)

**Comment by jmalizia** [comment]
problème réglé selon ce qui est choisi, les variants soit ajoutés ou supprimé de la liste
