### ISSUE TITLE
Valider si certains impacts FATHMM de types T et D peuvent avoir les 2 impacts en même temps

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#592]
**Bug description**
est-ce possible que certains impacts FATHMM on les 2 types (T et D) car je n'arrive pas aux même chiffres?
quantité pour chacun + somme des 2
![Screen Shot 2020-12-16 at 12.30.42 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/3d95d41a-8027-4bc0-b267-79d33727b373)
![Screen Shot 2020-12-16 at 12.31.39 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/67f09fa5-c1ac-4eb3-8222-e7cb41aac05b)

mais je n'ai que 576 pages (à 15 items chaque et la dernière n'en a que 4)
![Screen Shot 2020-12-16 at 12.31.54 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/2fa83fc2-2064-4b79-ba65-8984667ce4c0)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: Chrome for Mac
 - Version 87.0.4280.88

**Comment by jecos** [comment]
Je pense que c'est possible. Un meme variant peut etre associé à plusieurs  transcript qui peuvent etre T ou D. A valider avec l'outil de noteboo : https://notebook.qa.cqdg.ferlab.bio/#/

**Comment by jecos** [comment]
Oui c'est possible : [https://notebook.qa.cqdg.ferlab.bio/#/notebook/2FYA3H8EM](https://notebook.qa.cqdg.ferlab.bio/#/notebook/2FYA3H8EM)

**Comment by jmalizia** [comment]
ok, donc j'en déduis que les valeurs sont bonnes et qu'ils y en a moins, car certains ont les 2 impacts simultanément
