### ISSUE TITLE
impossible de supprimer réinitialiser le filtre à moins de supprimer celui choisi

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#593]
**Bug description**
je neux pas pas tout simplement enlever le filtre à moins de le supprimer ou d'en définir un autre
![Screen Shot 2020-12-16 at 3 24 47 PM](https://user-images.githubusercontent.com/73133507/102402516-e2660f00-3fb2-11eb-919e-6724b390b59c.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser Chrome for Mac
 - Version 87.0.4280.88

**Comment by francisprovost** [comment]
Je ne comprends peut-être pas bien le flow pour avoir l'erreur mais je n'arrive pas à reproduire ici. Quand j'ai un filtre "vide" comme le tient, les boutons "Nouveau", "Duplicate" et "Supprimer" sont disponible

**Comment by jmalizia** [comment]
Oui, mais je n'arrive pas à faire un "clear" pour enlever le filtre si je ne le veux plus. Si je fais supprimer, je supprime mon filtre sauvegardé.

**Comment by francisprovost** [comment]
Si je comprends bien, "Nouveau" fait ce que tu veux. On pourrait peut-être avoir un bouton "clear" qui fait la même chose si ce n'est pas assez clair pour les utilisateurs / use case

**Comment by jmalizia** [comment]
Ce serait un expected behavior, donc je vais soulever le point avec Lucas

**Comment by jmalizia** [comment]
Appuyer sur la poubelle de la ligne de la requête ou sur Nouveau pour effacer les filtres
