### ISSUE TITLE
La page patient apparaît quand on va à la page de login

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#595]
Déconnectez-vous de clin
ouvrir un nouveau browser
allez sur le site de clin
On voit la page liste de patients apparaitre avant que la page de login apparaisse

**Comment by vferretti** [comment]
voir vidéo a https://www.dropbox.com/s/72r18sw41kqc6q1/flashAtLogin.mp4?dl=0

**Comment by denis-crsj** [comment]
Difficile à reproduire, bougé dans le Icebox pour le moment
