### ISSUE TITLE
Page blanche lorsque l'on clique sur le bouton annuler dans les filtres de variant

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#597]
**Bug description**
Page blanche lorsque l'on clique sur le bouton annuler dans les filtres de variant

**Steps To Reproduce**
1. Go to any filter menu (I chose "Gènes") - Patient PA0046
2. Click on any filter (I chose "Types de Gènes") 
3. Then click on "<Annuler" to go back
4. See error -> white page

**Expected behavior**
we are expecting to go back one level in the filter menu.

**Screenshots**
![Screen Shot 2020-12-17 at 9.32.37 AM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/c10905f7-03d5-43d7-95da-2181eb3332c5)
![Screen Shot 2020-12-17 at 9.25.57 AM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/6705598d-9035-4975-bc80-d0d8b6f5b909)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.17
 - Browser Chrome for Mac
 - Version 87.0.4280.88

**Comment by francisprovost** [comment]
Je n'arrive pas à reproduire. Peut-être déjà réglé?

**Comment by jmalizia** [comment]
semble être réglé oui. Moi non plus, je n'arrive pas à reproduire le comportement que cela me faisait hier

**Comment by YanLabCHU** [comment]
Je peux reproduire en changeant les étapes.

**Comment by jmalizia** [comment]
semblent se produire seulement sur quelques uns spécifiquement
IMPACTS 
 - FATHMM
 - SIFT
 - Polyphen2
 - LRT

**Comment by francisprovost** [comment]
Parfait jvais tester ça

**Comment by denis-crsj** [comment]
@francisprovost @YanLabCHU Le bouton fonctionne maintenat sauf que quand ça nous ramène au menu précédent, l'option sur laquelle nous avions cliqué reste sélectionnée avec un visuel un peu bizarre.

![image](https://user-images.githubusercontent.com/64538118/104231078-6b3e6200-541c-11eb-9885-a80e775d85ca.png)

**Comment by YanLabCHU** [comment]
@denis-crsj J'avais réglé cette carte au backend, s'il y d'autres bugs, c'est sûrement pas par rapport à cette carte.

**Comment by francisprovost** [comment]
@denis-crsj @YanLabCHU C'est un bug que j'avais réglé. Je pense avoir remis la propriété que je ne devais pas. Je vais réglé ça, pas besoin d'ouvrir un autre ticket
