### ISSUE TITLE
Incapable de définir 2 conséquences SPLICES via la recherche de filtres

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#598]
**Bug description**
Dans la page variant d'un patient, incapable de définir 2 conséquences via la recherche de filtres. Je voulais essayer de tester le bug sur le regroupement des variant par type que Jeremy avait ouvert. Le variant contenait 2 conséquences SPLICES (donor et acceptor). En recherchant et en applicant 2 filtres, j'ai une page blanche

**Steps To Reproduce**
1. go on Variant page of Patient PA0046
2. Clicked on search bar of the filters
3. typed in "Splices" and selected "Splice donor"
4. then typed in the same search and selected "Splice acceptor"
5. blank page
6. tried by inverting the choices, same issue. Also tried with one the 2 splices above selected along with "Splice region" same issue. I tried with different other filters but it worked fine. The issues seems to only occur with the 3 "Splice" filters

**Expected behavior**
The second filter should have been applied for me to choose a 3rd one

**Screenshots**
![Screen Shot 2020-12-17 at 10.09.29 AM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/e149139c-a48b-485b-897f-00c848798ad1)
![Screen Shot 2020-12-17 at 10.51.32 AM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/070c4f77-9024-4d1d-905b-79fff24850d9)
![Screen Shot 2020-12-17 at 10.51.41 AM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/af984384-fc1c-4897-b80d-28e1ecb560f5)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser Chrome for Mac
 - Version 87.0.4280.88 (latest public version)

**Comment by denis-crsj** [comment]
Problème résolu.
