### ISSUE TITLE
Page de recherche variantes: Sans filtres, les variants affichés dans chaque page sont inconsistents

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#599]
**Bug description**
Lorsqu'on a aucun filtre appliqué, les variantes affichées dans une page (exemple 2) ne seront plus les mêmes si on change de page.

**Steps To Reproduce**
1. Go to Page de recherche de variantes pour un patient
2. Aucun filtre ne doit être appliqué
3. Garder en mémoire le dernier variants, puis aller à la page 2
4. Revenir à la page 1, le dernier variant n'est plus le même

**Expected behavior**
Les mêmes variants sont affichés lorsqu'on change de page et revient.
![variant-1.png](https://images.zenhubusercontent.com/5f313d03d7df470e8324c4c8/fdaf29eb-74d9-4701-b796-b2c48cd73728)![varaints-2.png](https://images.zenhubusercontent.com/5f313d03d7df470e8324c4c8/55235b0d-f041-45df-a3fc-faa9595726c9)

**Comment by denis-crsj** [comment]
problème résolu
