### ISSUE TITLE
Tableau de variants - Regression barre de recherche

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#601]
- Enlever les ✓ partout
- Remettre les bonnes couleurs pour les tags de chiffres
- Quand on a sélectionné un item (ex: `Developmental delay with autism spectrum disorder and gait instability`) on ne voit plus le state "selected" dans le dropdown.

![Pasted_Image_2020-12-22__11_38_AM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/780d1e99-33fd-4977-976e-9b15df8c5fb2)

### Voici ce qu'on devrait avoir:

Search default
![Search dropdown.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/ca84ceb0-0fd8-4fe5-81bc-582218f3ab91)

Search hover
![Search dropdown -- hover.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/d3c56570-ea06-4f0d-bd42-7cfc96b2cd62)

Search selected
![Search dropdown -- results.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/afca1e42-5107-4b83-a592-cf5ab7f9068a)

**Comment by denis-crsj** [comment]
@claudia1296 Comme discuté, voir 3 petits correctifs pour la couleur de la police

**Comment by denis-crsj** [comment]
Tout est réglé, je ferme la carte
