### ISSUE TITLE
Page de recherche de variant - Manque un retour de ligne entre deux conséquences

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#602]
Voir screenshot: Intron devrait être sur sa propre ligne 

![image.png](https://images.zenhubusercontent.com/5bbcbdee387e41362246faa0/99529877-0e33-43e2-a02b-22ea8a66024e)

**Comment by francisprovost** [comment]
J'ajoute simplement un espace pour le moment, le data est construit de façon que "Intron" fait partie de la même conséquence

**Comment by denis-crsj** [comment]
corrigé.
