### ISSUE TITLE
Mauvaise langue de l'interface à la déconnexion

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#603]
- Loguez-vous à CLIN pour arriver à la page Patients en Français
- Déconnectez-vous
->  la page login obtenue est en Anglais

**Comment by denis-crsj** [comment]
Problème plus complexe que prévu. Je retire la carte du tableau car nous devrons avoir une rencontre a ce sujet et voir comment on adresse le problème pour recréer des cartes

**Comment by francisprovost** [comment]
- La langue entre Keycloak et CLIN ne sont pas synchronisé
- https://www.keycloak.org/docs/10.0/server_development/#_locale_selector
    - url param et cookie ne semble pas pris en compte
- La dernière langue utilisée dans keycloak est gardée en mémoire 
- CLIN perd la langue choisit au rafraîchissement de la langue
