### ISSUE TITLE
Recherche de variants: le bouton back réinitialise la requête

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#604]
- Aller à la page de recherche de variant
- Créer un nouveau filtre en cliquant sur le bouton Nouveau
- Faire une requête quelconque ex. type de variant = SNV
- Cliquer sur un variant du tableau pour ouvrir sa page
- Faire back à partir du bouton du browser
Résultat: la requête type de variant = SNV est perdue et on retrouve une liste de variant non filtrée. Si on avait un filtre par défaut de définit, c'est celui-ci qui s'appliquerait. 

On veut retrouver la page de recherche dans l'état où on l'a laissée avant de cliquer sur un variant.

**Comment by francisprovost** [comment]
Je n'arrive pas à reproduire.

Testé avec ou sans filtres favoris

**Comment by denis-crsj** [comment]
Difficile à reproduire, bougé dans le icebox pour le moment
