### ISSUE TITLE
Page de Variantes: Impossible de changer la valeur de certains filtres

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#608]
**Bug description**
Impossible de changer la valeur de certains filtres: 

**Steps To Reproduce**

_Se **produit** sur d'autres filtres que 'SIFT'_
1. Go to 'Variant Page'
2. Click on 'Impacts'
3. Click on 'Sift'
4. Can't change the value

**Expected behavior**
We should be able to change the value.

**Screenshots**
![sift](https://user-images.githubusercontent.com/69463110/103686150-611fed80-4f5c-11eb-8f25-43c9f9a42f3a.png)

**Comment by denis-crsj** [comment]
Il est maintenant possible de changer la valeur
