### ISSUE TITLE
Mauvais statut après avoir finaliser un patient

### ISSUE THREAD

**Issue by francisprovost** [Ferlab-Ste-Justine/clin-project#609]
**Bug description**
Le status du patient n'est pas mis à jour lorsqu'on soumet le formulaire et redirigé vers la liste des patients. 
Le status se mets à jour si on refraichit la page.

**Steps To Reproduce**
1. Créer un nouveau patient
2. Aller dans la fiche du patient pour compléter le formulaire
3. Retourner à la liste de patient et le status est toujours "Brouillon"  au lieu de "Soumise" 
    - Avec un refresh de la page, le status change pour le bon

**Expected behavior**
Le status devrait être mis à jour lorsqu'on soumet le formulaire est redirigé vers la liste des patients.

**Comment by jmalizia** [comment]
Problème résolu, le comportement attendu se produit à correctement. Je ferme la carte
