### ISSUE TITLE
Changemenet du flow de création des resources Patient et ServiceRequest

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#612]
https://www.notion.so/ferlab/Modification-du-mod-le-FHIR-pour-les-Practitioners-564725211546443b8f6d71582310a5c9

**Comment by YanLabCHU** [comment]
Waiting for https://github.com/Ferlab-Ste-Justine/clin-project/issues/614

**Comment by YanLabCHU** [comment]
L'analyse a été mise à jour
