### ISSUE TITLE
Refaire la page 1 du formulaire (Infos patient)

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#614]
**Tâches**
- Modifier le bouton "+ Patient" pour --> "Créer un patient" avec l'icône également
- Cliquer sur le bouton ouvre maintenant une boite modale au lieu de rediriger sur le formulaire (Voir spécification pour les champs nécessaires ainsi que les règles d'interactions)
- Une fois les informations entrées, cliquer sur "Créer le patient" redirige sur une autre boite modale donnant plusieurs options à l'utilisateur (Voir maquettes et spécification pour les règles d'affaires)

**Connecter avec le service back-end pour la validation des doublons de patients

---

Maquette --> https://www.figma.com/file/IG5yCPj7qamtxsoU8bnl6r/CLIN---Creer-un-patient?node-id=51%3A0

Prototype --> https://www.figma.com/proto/IG5yCPj7qamtxsoU8bnl6r/CLIN---Creer-un-patient?node-id=123%3A31734&viewport=10503%2C14127%2C1&scaling=min-zoom&hide-ui=1

Specs --> https://www.notion.so/ferlab/Nouveau-worflow-de-cr-ation-de-patient-7632abacf23649299322db11a8950f7b

### Defects
- [x] La création du patient fonctionne mais il y a un message d'erreur au lieu de la modale normale nous permettant de continuer avec la création de la prescription

**Comment by YanLabCHU** [comment]
Dépend de #631

**Comment by jmalizia** [comment]
lorsque je mets la RAMQ, CLIN cherche indéfiniment pour un doublon et je ne peux continuer de définir les autres info du nouveau patient
![Screen Shot 2021-02-15 at 9 51 32 AM](https://user-images.githubusercontent.com/73133507/107961219-96fcbc80-6f73-11eb-9d13-a4ac18655a37.png)

**Comment by denis-crsj** [comment]
Nous pouvons maintenant créer le patient. Lorsqu'on cliquer sur soumettre, une boite modale d'erreur apparait mais le patient est créé quand meme. 

Il faut régler le message d'erreur

**Comment by francisprovost** [comment]
Le fix vient d'être mergé, le problème va être reglé dans quelques mintues

**Comment by jmalizia** [comment]
defect réglé
