### ISSUE TITLE
Ajuster le reste du formulaire

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#615]
- Modifier le header `Prescription | [NOM DE FAMILLE] [Prénom]`
- Ajuster les # des étapes en haut du formulaire
- Ajouter un dropdown avec le # D'MRN en haut et permettre de le changer pour sélectionner le bon.

**Maquettes**
https://www.figma.com/file/Hvh1kY1o0rzzO89IuOYITP/CLIN---Creer-une-prescription?node-id=1898%3A2868

**Comment by jmalizia** [comment]
tous les points ont été implantés selon les specs à l'exception du premier (la maquette a changé après la création de la carte). Le détail du point 1 a été mise à jour dans la carte avec la bonne spec.
![Screen Shot 2021-02-15 at 2 18 50 PM](https://user-images.githubusercontent.com/73133507/107985776-bc4ff180-6f98-11eb-9835-eb898fd03f0d.png)

**Comment by francisprovost** [comment]
Selon Figma(https://www.figma.com/file/Hvh1kY1o0rzzO89IuOYITP/CLIN-Creer-une-prescription?node-id=2250%3A50071), l'en-tête en place respect le design

**Comment by jmalizia** [comment]
ce que tu montres oui, mais nous parlons de l'Entête lorsque l'utilisateur est dans une prescription. Je vois qu'une correction a été apportée mais il y a une ligne de trop trop

CLIN
<img width="1437" alt="Screen Shot 2021-02-16 at 3 44 20 PM" src="https://user-images.githubusercontent.com/73133507/108119626-12429900-706e-11eb-9232-d9eb0f1a6616.png">


Maquette
<img width="905" alt="Screen Shot 2021-02-16 at 3 45 19 PM" src="https://user-images.githubusercontent.com/73133507/108119618-0f47a880-706e-11eb-9df6-34b576ee86a3.png">

**Comment by jmalizia** [comment]
La ligne en trop apparait encore.

Note: j'avais fermé la page CLIN hier, et je viens tout juste d'ouvrir un nouvel onglet, me suis connecter et sélectionné 2 patient au hasard pour compléter des prescriptions
![Screen Shot 2021-02-17 at 12 10 52 PM](https://user-images.githubusercontent.com/73133507/108240817-360ee900-7119-11eb-9c6e-13d567b50d86.png)
![Screen Shot 2021-02-17 at 12 10 15 PM](https://user-images.githubusercontent.com/73133507/108240818-36a77f80-7119-11eb-80b5-388731279c3e.png)

**Comment by francisprovost** [comment]
J'avais pas remarqué que le annuler était sur une 2e ligne dans ton screenshot 🤦  Mais très bon choix de patient!

**Comment by jmalizia** [comment]
l'alignement est bon, je ferme la carte
