### ISSUE TITLE
Export Nanuq

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#616]
La personne peut sélectionner des patients et ensuite  les exporter en format Json pour les importer dans Nanuq. Quelques règles d'affaires à respecter, voir les specs plus bas pour les détails.

Voir avec Jason pour toutes questions en lien avec l'analyse.

**Specs**
https://www.notion.so/ferlab/Export-Nanuq-de1217e24fdc4160a54c944ca7c369e4

**Maquette**
https://www.figma.com/file/Re9zQkA3WcCSNu3ZJtbrrM/Clin---donnees-nanuq?node-id=143%3A74692

**Comment by jmalizia** [comment]
Expert est généré avec succès et selon les specs.

**Comment by jmalizia** [comment]
Le champ "sexe" devrait avoir une des valeurs suivantes: "female", "male" ou "unkown".
Le format de la date de naissance devrait être yyyy-mm-dd

**Comment by jmalizia** [comment]
en attente du développement sur le mapping des types de tests en lien avec les nouvelles sélections d'analyses qui ont été définies la semaine passée

**Comment by francisprovost** [comment]
@jmalizia Quand t'as une chance de fermer cette carte. Aucun développement ne peut être fait sur cette carte pour le moment

**Comment by jmalizia** [comment]
nouvelle carte sera créée pour lorsque le développement du bloquant sera fait.
