### ISSUE TITLE
Traduction en EN erronée

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#622]
**Bug description**
erreur de traduction

**Steps To Reproduce**
Steps to reproduce ![Screen Shot 2021-01-15 at 3.03.00 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/9af07af2-ba7e-4443-9a6a-7994b722b8d1)the behavior:
1. Go to page d'un patient avec une prescription en  mode "brouillon"
2. open it and go to page 2 of the prescription
3. first section -> see error

**Expected behavior**
3e choix du traduction du type d'analyse devrait être "Targeted sequencing"

**Screenshots**
![Screen Shot 2021-01-15 at 3.03.00 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/24b1d0ec-3986-4996-bcb3-eed29c32faca)

**Comment by denis-crsj** [comment]
Je ferme pour l’instant, sera ré-ouverte sous peu si nécessaire
