### ISSUE TITLE
Page Variant - Diviser le tableau Conséquences géniques en un tableau par gène rapporté

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#627]
### Spécifications
- Faire un tableau par gène rapporté.
- Par défaut le tableau n'aura qu'une seule rangé par gène. C'est la conséquence pour le transcrit Canonique du gène en question.
- Lorsqu'un gène a plusieurs transcrits, il faut ajouter un lien cliquable en bas à gauche avec le nombre de transcrits pour les affichers (Ex: Ce gène possède _4 autres transcrits_)
- Afficher les gènes de type Protein_coding en premier.
- Chaque tableau aura un titre au dessus. Le lien sur gene Symbol est le même que celui dans le tableau actuel (Ex : https://useast.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000143702).
- La nouvelle colonne VEP affiche l'impact VEP qui est présentement dans la colonne Impact. Afficher sous forme de tag et mettre le tag de la couleur adéquate basé sur les rond de couleurs actuels
- On affiche par défaut seulement les scores et catégories SIFT et Polyphen2 dans la colonne Prédiction(s). On doit cliquer sur Plus pour afficher la liste complète des scores dans la même cellule.
- Modifier le titre de certaines colonnes (voir titre des colonnes dans la maquette)

**Maquette Figma**
https://www.figma.com/file/JOl4AYNyJcJN34tRT7lRjR/CLIN-Page-de-variant?node-id=869%3A10107

**Comment by jmalizia** [comment]
- [ ] Faire un tableau par gène rapporté.
- [ ] Par défaut le tableau n'aura qu'une seule rangé par gène. C'est la conséquence pour le transcrit Canonique du gène en question.
- [ ] Lorsqu'un gène a plusieurs transcrits, il faut ajouter un lien cliquable en bas à gauche avec le nombre de transcrits pour les affichers (Ex: Ce gène possède 4 autres transcrits)
- [X] Afficher les gènes de type Protein_coding en premier.
- [X] Chaque tableau aura un titre au dessus. Le lien sur gene Symbol est le même que celui dans le tableau actuel (Ex : https://useast.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000143702).
- [X] La nouvelle colonne VEP affiche l'impact VEP qui est présentement dans la colonne Impact. Afficher sous forme de tag et mettre le tag de la couleur adéquate basé sur les rond de couleurs actuels
- [ ] On affiche par défaut seulement les scores et catégories SIFT et Polyphen2 dans la colonne Prédiction(s). On doit cliquer sur Plus pour afficher la liste complète des scores dans la même cellule.
- [X] Modifier le titre de certaines colonnes (voir titre des colonnes dans la maquette)

Defect 
tableau dand l'onglet patient du gène ne s'ajuste pas selon la grosseur de l'écran. Je suis à 100% mais le tableau ne prends pas l'espace de l'écran alloué et fait que certains titre de colonnes sont tronqués 
![Screen Shot 2021-02-15 at 4 49 36 PM (2)](https://user-images.githubusercontent.com/73133507/107996269-00012600-6fae-11eb-9dd4-83526d979b95.png)

Autre possible defect (à confirmer si les specs ont changé après la création des maquette)
dans l'onglet fréquence d'un gène, manque la première colonne "LDM" dans CLIN
Maquette
![Screen Shot 2021-02-15 at 4 53 55 PM](https://user-images.githubusercontent.com/73133507/107996438-671eda80-6fae-11eb-8fcc-57e4937313a7.png)
CLIN
![Screen Shot 2021-02-15 at 4 54 11 PM](https://user-images.githubusercontent.com/73133507/107996449-7140d900-6fae-11eb-94d9-462540464aca.png)

**Comment by denis-crsj** [comment]
@claudia1296 À valider si les règles d'affaires ont été modifiées après mais dans les tableaux de gênes, la colonne se nomme `Impact` alors que dans la maquette elle se nomme `Prédiction(s)` et la colonne se nomme `Conservation` dans le portail alors que dans la maquette, elle se nomme `Conservation (PhyloP17Way)`

Tout le reste est beau
