### ISSUE TITLE
Associations cliniques - Ajuster le titre du tableau Clinvar

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#628]
Modifier le titre du tableau actuel pour le titre suivant:

ClinVar (clinvar_id) --> clinvar_id étant un lien, cet ID se trouve déjà dans l'entête

**Maquette**
https://www.figma.com/file/JOl4AYNyJcJN34tRT7lRjR/CLIN-Page-de-variant?node-id=869%3A18978

### DEFECTS
- [x] Enlever les espaces au début et à la fin des parenthèses

**Comment by denis-crsj** [comment]
@claudia1296 mini defect à corriger. Voir plus haut

**Comment by jmalizia** [comment]
bug réglé
