### ISSUE TITLE
N/A est affiché au lieu du nom du médecin responsable

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#630]
**Bug description**
Lorsqu'on assigne un médecin responsable à une requête et qu'on la sauvegarde (sans soumettre), N/A est affiché au lieu des informations du médecin lors de l'édition du formulaire.

**Steps To Reproduce**
1. Ajouter un médecin responsable
2. Cliquer sur Sauvegarder
3. Revenir sur la page de la liste de patient
4. Sélectionner le patient qu'on vient de sauvegarder
5. Ouvrir le formulaire pour éditer les informations de la requête
6. À la page 3, on voit le bug.

**Expected behavior**
Les bonnes informations du médecins responsable doivent être affichées.

**Screenshots**
![bug.png](https://images.zenhubusercontent.com/5f313d03d7df470e8324c4c8/b2f6ac78-22f9-4bd2-a3d5-21cb664fe0a6)

**Comment by denis-crsj** [comment]
Était déjà testé mais la carte n'avait pas été fermé
