### ISSUE TITLE
Variant (ETL) : Ajouter les tables annotations manquantes 

### ISSUE THREAD

**Issue by jecos** [Ferlab-Ste-Justine/clin-project#636]
### Feature

Dans la bd de varian, il manque certaines tables d'annotations, Ces annotations n'ont pas besoin d'etre indexés dans ES. Il suffit simplement de les copier de kids first et de recreer la table, afin de pooiuvoir les utiliser dans les notebook.

**Comment by botekchristophe** [comment]
il manquerait:
- annovar
-cosmic
