### ISSUE TITLE
Associations cliniques - Ajustements au tableau ClinVar

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#640]
Nous voulons afficher toutes les interprétations avec toutes les conditions et la transmission.

**Specs**
- 3 colonnes --> Interpretation, Condition, Transmission
- La transmission sera donnée par la colonne `inheritence`
- 1 ligne seulement pour le tableau. Alors étant donné que chaque colonne peut avoir plusieurs valeures, il faut afficher toutes les valeures d'une même colonne (interprétation, Condition et Transmission) sur la même ligne séparées par des virgules

**Question**
Modification back-end à faire ou bien géré dans la carte d'ETL ??

**Maquette**
https://www.figma.com/file/JOl4AYNyJcJN34tRT7lRjR/CLIN-Page-de-variant?node-id=869%3A18978

**Comment by jmalizia** [comment]
@claudia1296 
ajouter l'Accent sur le 2e e 
interprétation --> interprétation

**Comment by jmalizia** [comment]
fixed
