### ISSUE TITLE
Associations cliniques - Création du tableau Gène - Phénotype

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#641]
Prendre les 3 tableaux existants et les combiner en 1 seul tableau intitulé : "Gène - Phénotype"

- Le tableau aura 4 colonnes (`Source`, `Gène`, `Signe/Condition`, `Transmission`)
- Afficher les sources dans l'ordre suivant : (1. Orphanet - 2. OMIM - 3. HPO)
- Classer ensuite les gènes en ordre pour chaque source

**Pour Orphanet**
- L'information se trouve actuellement dans le tableau intitulé "Association/Condition"
- L'information de la colonne `Gène` ira dans la colonne du même nom
- L'information de la colonne `Orphanet` ira dans la colonne `Signe/Condition`. N'afficher seulement qu'un terme par ligne.
- Afficher maximum 3 termes par défaut et utiliser un mécanisme d'expand/collapse "Voir plus" (Voir maquette)
- Afficher "--" dans la colonne `Transmission` pour le moment

**Pour OMIM**
- N'afficher seulement qu'un terme par ligne. Afficher maximum 3 termes par défaut et utiliser un mécanisme d'expand/collapse "Voir plus" (Voir maquette)
- L'information de la colonne `Gène/Locus` ira dans la colonne `Gène`
- L'information de la colonne `Phénotype` ira dans la colonne `Signe/Condition`
- L'information de la colonne `Transmission` ira dans la colonne du même nom

**Pour HPO**
- N'afficher seulement qu'un terme par ligne. Afficher maximum 3 termes par défaut et utiliser un mécanisme d'expand/collapse "Voir plus" (Voir maquette)
- L'information de la colonne `Gène` ira dans la colonne du même nom
- L'information de la colonne `Signe` ira dans la colonne `Signe/Condition`
- Étant donné qu'il n'y a pas de transmission pour le HPO, seulement afficher "--"

**Maquette**
https://www.figma.com/file/JOl4AYNyJcJN34tRT7lRjR/CLIN-Page-de-variant?node-id=869%3A18978

---

DEFECTS
- [x] Le titre de la 1ère colonne devrait être Source.
- [x] L'information dans les colonnes ne devrait pas être centrée verticalement mais plutôt alignée vers le haut
- [x] La taille de police du bouton `Voir` plus devrait être à 12px au lieu de 14px

**Comment by denis-crsj** [comment]
@claudia1296 3 defects à corriger. Voir section DEFECTS dans la description plus haut.

**Comment by jmalizia** [comment]
3 bugs restants réglés
