### ISSUE TITLE
Fréquences - Ajustements au tableau RQDM

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#642]
- Mettre le tableau pleine largeur
- Modifier l'erreur de frappe du titre actuel. Changer `RDMQ` pour `RQDM`
- Une ligne par laboratoire. Il faut donc ajouter une nouvelle colonne complètement à gauche intitulé `LDM` et y mettre le nom du laboratoire
- La valeur qui doit se trouver dans la colonne `Fréquence` doit donc être la fréquence pour le labo en question
- Modifier le titre de la colonne `Nb Patients` pour seulement `Patients`
- Modifier le titre de la colonne `Nb Allèles ALT` pour `# Allèles ALT`
- Modifier le titre de la colonne `Nb Allèles (ALT + REF)` pour `# Allèles (ALT+REF)`
- Modifier le titre de la colonne `Nb homozygotes` pour `# Homozygotes`
- Ajouter une ligne `Total`, en gras, a la fin du tableau qui totalise l'information de chaques lignes.
- Faire que le nombre de patient dans la colonne `Patients` et dans la ligne de `Total` soit un hyperlien redirigeant vers l'onglet Patients

**Maquette**
https://www.figma.com/file/JOl4AYNyJcJN34tRT7lRjR/CLIN-Page-de-variant?node-id=869%3A16999

**Comment by jmalizia** [comment]
- [X] Mettre le tableau pleine largeur
- [X] Modifier l'erreur de frappe du titre actuel. Changer RDMQ pour RQDM
- [X] Une ligne par laboratoire. Il faut donc ajouter une nouvelle colonne complètement à gauche intitulé LDM et y mettre le nom du laboratoire
- [ ] La valeur qui doit se trouver dans la colonne Fréquence doit donc être la fréquence pour le labo en question --> _**qui peut valider avec les données?**_
- [X] Modifier le titre de la colonne Nb Patients pour seulement Patients --> indiqué "# Patients"
- [X] Modifier le titre de la colonne Nb Allèles ALT pour # Allèles ALT
- [X] Modifier le titre de la colonne Nb Allèles (ALT + REF) pour # Allèles (ALT+REF)
- [X] Modifier le titre de la colonne Nb homozygotes pour # Homozygotes
- [X] Ajouter une ligne Total, en gras, a la fin du tableau qui totalise l'information de chaques lignes.
- [X] Faire que le nombre de patient dans la colonne Patients et dans la ligne de Total soit un hyperlien redirigeant vers l'onglet Patients

**Comment by jmalizia** [comment]
@YanLabCHU 
La valeur qui doit se trouver dans la colonne Fréquence doit donc être la fréquence pour le labo en question --> @yanis tu peux valider que les données sont bels et biens celles par labo?
