### ISSUE TITLE
Page Variant - Ajustement à l'onglet Patients

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#644]
- Retirer le titre du tableau
- Changer la phrase actuelle en haut du tableau pour : "[Nombre de patients] Patients"
- Pour la colonne `LDM`, il faut afficher le nom du laboratoire au lieu de l'ID
- L'hyperlien de l'ID du patient doit être souligné
- Ajouter une nouvelle colonne `Sexe` juste après la colonne `LDM`
- Ajouter une nouvelle colonne `Position` juste après la colonne `Sexe` et y indiquer si le patient est un Proband ou un Parent. Afficher l'information sous forme de tag et utiliser les couleurs adéquates (Voir maquette pour les codes de couleurs)
- Retirer la colonne `Étude`
- La valeur dans la colonne `Famille` doit être un hyperlien redirigeant vers ...
- Renommer le titre de la colonne `Type` par `Test`
- Prendre les 3 colonnes suivantes (`Profondeur allélique`, `Profondeur allélique (ALT+REF)` et `Profondeur allélique (ratio)`) et les remplacer par une seule colonne intitulé `Profondeur allélique (Ratio)`. L'affichage de l'information dans cette colonne sera le suivant : [Profondeur allélique] / [Profondeur allélique (ALT+REF)] ([Profondeur allélique (ratio)])
- Maximum 2 décimales pour le ratio. Ne pas utiliser de notation scientifique
- Renommer la colonne `Qualité du Génotype` par `Qualité génotype`
- Retirer la colonne `Qualité de la profondeur de la lecture`
- Appliquer même fix pour le colonnes que dans la page Patients (Voir Yanis)

**Maquettes**
https://www.figma.com/file/JOl4AYNyJcJN34tRT7lRjR/CLIN-Page-de-variant?node-id=869%3A15020

**Comment by jmalizia** [comment]
- [X] Retirer le titre du tableau
- [X] Changer la phrase actuelle en haut du tableau pour : "[Nombre de patients] Patients"
- [X] Pour la colonne LDM, il faut afficher le nom du laboratoire au lieu de l'ID
- [X] L'hyperlien de l'ID du patient doit être souligné
- [X] Ajouter une nouvelle colonne Sexe juste après la colonne LDM
- [ ] Ajouter une nouvelle colonne Position juste après la colonne Sexe et y indiquer si le patient est un Proband ou un Parent. Afficher l'information sous forme de tag et utiliser les couleurs adéquates (Voir maquette pour les codes de couleurs)
- [X] Retirer la colonne Étude
- [] La valeur dans la colonne Famille doit être un hyperlien redirigeant vers ...
- [X] Renommer le titre de la colonne Type par Test
- [X] Prendre les 3 colonnes suivantes (Profondeur allélique, Profondeur allélique (ALT+REF) et Profondeur allélique (ratio)) et les remplacer par une seule colonne intitulé Profondeur allélique (Ratio). L'affichage de l'information dans cette colonne sera le suivant : [Profondeur allélique] / [Profondeur allélique (ALT+REF)] ([Profondeur allélique (ratio)])
- [ ] Maximum 4 décimales pour le ratio. Ne pas utiliser de notation scientifique
- [ ] Renommer la colonne Qualité du Génotype par Qualité génotype
- [X] Retirer la colonne Qualité de la profondeur de la lecture
- [ ] Appliquer même fix pour le colonnes que dans la page Patients (Voir Yanis)

**Comment by jmalizia** [comment]
bugs réglés
