### ISSUE TITLE
Titre "Liste de patient" est erroné

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#646]
Titre de la liste de patient devrait être "Patients et prescriptions" selon la maquette
https://www.figma.com/file/IG5yCPj7qamtxsoU8bnl6r/CLIN-Creer-un-patient?node-id=442%3A38424

actuellement, nous voyons
![Screen Shot 2021-02-02 at 9.02.42 AM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/8cf5c54f-334b-4d22-b47e-23f103c0d40c)

**Comment by denis-crsj** [comment]
All good
