### ISSUE TITLE
Formulaire - Modifications à la section "Analyses"

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#647]
- [x] Remplacer "Type de test" de la section "Analyses" par "Sélection d'analyses"
- [x] Nous aurons ici une liste de checkbox. La liste de tests à afficher ici nous sera fourni sous peu par le MSSS
- [x] Nous devons être en mesure de sélectionner plusieurs cases

**Maquette**
https://www.figma.com/file/Hvh1kY1o0rzzO89IuOYITP/CLIN-Creer-une-prescription?node-id=2155%3A70

**Comment by denis-crsj** [comment]
All good

**Comment by jmalizia** [comment]
les 3 points ont été implantés correctement
