### ISSUE TITLE
Détails patient - Carte de profil du foetus

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#650]
**Entête**
- [ ] Dans le cas ou la prescription est un foetus, le nom que nous verrons dans l'entête sera différent. Il faut afficher le mot `Foetus` et y mettre ensuite le nom de la mère.
- [ ] Le nom de la mère devra être un hyperlien redirigeant vers le profil de la mère
- [ ] Il doit y avoir 2 tags, un tag `Proband` et un tag `Foetus`

https://www.figma.com/file/Hvh1kY1o0rzzO89IuOYITP/CLIN-Creer-une-prescription?node-id=2250%3A52847

**Carte de profil**
- [ ] Dans la carte de profil, le nom du "Patient" sera `Foetus`
- [ ] Sous le nom, faire afficher le nom de la mère avec le mot `mère` entre parenthèse. Cette ligne doit être un hyperlien vers le profil de la mère
- [ ] Afficher le tag `Proband` et le tag `Foetus`

https://www.figma.com/file/Hvh1kY1o0rzzO89IuOYITP/CLIN-Creer-une-prescription?node-id=2250%3A53946

**Infos Patient**
- [ ] Laisser la date de naissance vide "--"

https://www.figma.com/file/Hvh1kY1o0rzzO89IuOYITP/CLIN-Creer-une-prescription?node-id=2250%3A53480

**Profil de la mère**
- [ ] Pour la fiche de la mère, le tag à utiliser pour l'entête ainsi que la carte de profil est le tag `Parent`

https://www.figma.com/file/Hvh1kY1o0rzzO89IuOYITP/CLIN-Creer-une-prescription?node-id=2250%3A53481

---

### DEFECTS
- [x] Dans l'entête, les tag `Proband` et `Foetus` sont trop distancés (voir maquette)
- [x] Dans l'entête, l'alignement entre le mot Foetus, le nom de la mère et les tags n'est pas correct, les 3 valeurs ne sont pas alignées enters elles (voir maquette)
- [x] Dans l'entête, le nom de la mère devrait avoir un font-weight de 500
- [x] Dans la carte de profil, le nom de la mère devrait avoir un font-weight de 500
- [x] Dans le profil de la mère, le tag `Parent` de la carte de profil n'est pas bien aligné
- [x] Dans l'entête du profil de la mère, l'icône féminin est trop petit
- [x] Dans l'entête du profil de la mère, le tag de la date et le tag `Parent` sont trop éloignés
- [x] Dans la carte de profil de la mère, le nom de famille devrait être en majuscules

**Comment by jmalizia** [comment]
incapable de tester car je ne peux créer un patient (essayer 2x avec foetus et 1x avec patient et toujours le même résultat)
<img width="438" alt="Screen Shot 2021-02-26 at 5 02 26 PM" src="https://user-images.githubusercontent.com/73133507/109359988-6ad71a80-7854-11eb-9f77-ff6b747ef98d.png">

**Comment by denis-crsj** [comment]
@francisprovost Plusieurs petits points à corriger, voir section DEFECTS dans la description.

**Comment by francisprovost** [comment]
> Dans l'entête du profil de la mère, l'icône féminin est trop petit

Après validation, il fait 13.5 px comme celui dans la maquette

**Comment by jmalizia** [comment]
reste 2 defects:
#2 --> les tags ne sont pas centré dans le carré de la fiche
<img width="224" alt="Screen Shot 2021-03-16 at 4 43 38 PM" src="https://user-images.githubusercontent.com/73133507/111377546-28e10d80-8677-11eb-8e4c-2ed3148976b5.png">

#5 --> tag pas bien aligné
<img width="222" alt="Screen Shot 2021-03-16 at 4 47 25 PM" src="https://user-images.githubusercontent.com/73133507/111377716-5e85f680-8677-11eb-8431-2c5096ac320e.png">

**Comment by jmalizia** [comment]
bugs alignments réglés
