### ISSUE TITLE
Combiner les onglets Patient et Clinique

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#651]
L'onglet Patient et l'onglet clinique seront combinés ensemble et l'onglet sera renommé "Prescriptions". Les prescriptions seront donc affiché dans ce nouvel onglet combiné et apparaitront sous les infos du Patient.

- [x] Renommer l'onglet `Prescriptions`
- [x] Remplacer le tableau existant actuellement sous les infos Patient par les informations de la prescription qui se trouvaient dans l'onglet `Clinique`.
- [x] Les information de la prescription doivent être affichés dans un onglet ayant pour titre la date de soumission de la prescription
- [x] Chaque prescription aura son propre onglet (Déjà géré dans le back-end)
- [x] Afficher un cercle avec la couleur du statut dans l'onglet de la prescription

**Aucune prescription de débutée**
S'il n'y a aucune prescription de commencé pour le patient ou le Foetus, faire afficher un message dans un encadré avec un bouton `Créer une prescription`

Texte Patient --> `Aucune prescription pour ce patient`
Texte Foetus --> `Aucune prescription pour ce Foetus`

**Comment by jmalizia** [comment]
voir la #687 pour un bug qui m'empêche de valider le dernier point "texte foetus"

**Comment by jmalizia** [comment]
tous les points ont été implantés correctement.
