### ISSUE TITLE
Modifications au bloc d'infos Patient

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#653]
**MRN**
Il est possible pour un patient d'avoir plusieurs MRN. Dans l'éventualité où cela se produit, nous devons en afficher maximum 2 à la fois dans la section d'infos du patient.

SI jamais il y en a plus que 2, nous devons afficher un lien "Voir plus" / "Voir moins" pour permettre de expand et de collapse la liste des MRN.

https://www.figma.com/file/Hvh1kY1o0rzzO89IuOYITP/CLIN-Creer-une-prescription?node-id=2267%3A45350

---

**Ethnicité et Consanguinité**
Ces informations doivent être retirées de toutes les vues du profil patient car elles sont maintenant demandées dans chaque prescription

---

Autres tâches
- [x] Renommer `MRN` par `Dossier(s)`
- [x] Renommer `Sexe` par `Sexe biologique`
- [x] Ajouter une ligne verticale entre chaque colonne
- [x] Ajouter un bouton `Modifier` en haut à droite

**Comment by jmalizia** [comment]
les 4 items ont été implantés correctement
