### ISSUE TITLE
Ajustements / Création de Patient

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#655]
**Nouveau Patient**
- [x] Enlever le mot "un" de la phrase au début "Prescription pour un"
- [x] Modale de confirmation --> Changer le texte pour `La fiche du patient/fœtus a été créé avec succès. Voir la fiche.`
- [x] Modale de confirmation --> Modifier les textes des boutons pour `Créer une nouvelle prescription` et `Compléter cette prescription` et changer également les icône pour `+` et `->` respectivement
- [x] Modale de confirmation --> Mettre le nom de famille en majuscule

**Patient existant**
- [x] Modale de confirmation --> Changer le texte pour : `Nous avons trouvé une fiche avec les mêmes identifiants.`
- [x] Modale de confirmation --> Changer le texte du bouton pour : `Voir cette fiche`
- [x] Modale de confirmation --> Le bouton/lien "Fermer" doit être souligné

**Bugs**
- [x] Le mouse over sur les boutons "Personne | Foetus" n'est pas correct pour le state "Selected" ce qui fait qu'on ne voit plus le texte
- [x] Si je clique sur le bouton `Voir fiche du patient` et qu'ensuite je reviens à la liste des patients pour créer un nouveau Patient, je retombe sur l'ancienne boite modale de l'ancien patient que je viens de consulter.

**Comment by francisprovost** [comment]
- [] Lors de la création d'un fetus, on doit disable les champs si le profil de la mère existe déjà
- [] Ajouter un "loading state" si la création du patient est longue
- [] Ajouter un "error state" lorsque la création échoue

**Comment by jmalizia** [comment]
tous les ponts listés ont bien été implantés

**Comment by jmalizia** [comment]
j'ai créé un nouveau patient avec succès. J'ai tenté de créé une prescription sans succès (#663 - commentaire de Jason a 10:40pm le 15 fév.). J'étais sur la page du patient que j'ai créé et en appuyant sur "Patients" pour revenir à la page des prescriptions et patients, je suis revenu sur le modal de création du patient que je venais de créer.
<img width="728" alt="Screen Shot 2021-02-15 at 10 41 17 PM" src="https://user-images.githubusercontent.com/73133507/108015913-4de25200-6fdf-11eb-9f4a-cc05d87a6dde.png">

**Comment by francisprovost** [comment]
Le fix pour ce defect à été déployé parmis les bug fixes de ce matin

**Comment by jmalizia** [comment]
Toujours le même problème

CLIN
<img width="583" alt="Screen Shot 2021-02-16 at 2 02 28 PM" src="https://user-images.githubusercontent.com/73133507/108109259-9d686280-705f-11eb-8125-3d353e5c2a7c.png">

Maquette
<img width="502" alt="Screen Shot 2021-02-16 at 2 03 23 PM" src="https://user-images.githubusercontent.com/73133507/108109365-c12ba880-705f-11eb-8ed7-c8cf1dfd0b56.png">

**Comment by jmalizia** [comment]
Ne reste qu'un petit bug pour le texte. Le texte de confirmation est générique que ce soit un patient ou un foetus et donc devrait être 
"La fiche du patient/fœtus a été créée avec succès. Voir la fiche." 
_(j'ai corrigé le texte de la maquette où il manquait un "e" à la fin de créé)_

** faire attention au mot foetus 
- foetus = FR 
- fetus = EN

CLIN
![Screen Shot 2021-02-18 at 11 12 48 AM](https://user-images.githubusercontent.com/73133507/108386107-55ba1600-71da-11eb-833b-403033b84a78.png)

Maquette
![Screen Shot 2021-02-18 at 11 14 08 AM](https://user-images.githubusercontent.com/73133507/108386334-8c902c00-71da-11eb-8d52-a3e8bd912f9c.png)

**Comment by francisprovost** [comment]
On veut vraiment un texte générique qui dit toujours les deux? On sait qu'on a créé un foetus ou un patient, pourquoi ne pas l'écrire? C'est beaucoup plus clair pour l'utilisateur à mon avis

**Comment by jmalizia** [comment]
on avait pensé faire ca pour éviter de créer des conditions d'affichage. Si c'est tout aussi facile ou déjà fait go for it, mais corrige le mot foetus stp

**Comment by francisprovost** [comment]
C'est déjà fait oui (et on a déjà une condition pour le `(foetus)` ) mais oui je vais corriger la typo

**Comment by jmalizia** [comment]
après discussion avec Lucas, dans le tableau des prescriptions/patients, lorsque le patient est un foetus mettre la valeur "Foetus" dans “Prénom” et garder le nom de famille de la mère dans “Nom”

**Comment by jmalizia** [comment]
tout fonctionne bien (patient et foetus) et visuel est tel les maquettes. Exception que les textes de confirmation de création de patient sont maintenant distincts pour les patients et les foetus.
