### ISSUE TITLE
La barre de recherche de patient ne fonctionne plus

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#662]
**Bug description**
On ne peut pas chercher un patient à partir de la barre de recherche.

**Steps To Reproduce**
1. Aller à la page de liste de patient
2. Cliquer sur la barre de recherche et chercher un patient
3. Rien ne se produit et on ne peut pas chercher un patient.

**Expected behavior**
Devrait afficher une liste de patients qui match la recherche

**Comment by denis-crsj** [comment]
la recherche fonctionne maintenant
