### ISSUE TITLE
Implémenter le nouveau flow de création de requête

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#663]
### Feature

Les requirements pour la création de requêtes d'un patient ont changé. Le but de cette tâche est de mettre à jour le flow de création des requêtes dans au frontend et backend.

**Comment by jmalizia** [comment]
Incapable de créer une prescription du début (création du patient) jusqu'à la soumission. 

1) je crée une nouvelle prescription  sur la page des prescription et patient
2) je défini un nouveau patient puis clique "suivant"
3) ensuite je clique sur "Compléter la prescription pour ce patient" --> j'ai une page blanche (essayer avec 2 patients (Louis KJH et André SDF)

![Screen Shot 2021-02-15 at 3 49 25 PM (2)](https://user-images.githubusercontent.com/73133507/107993968-adbe0600-6fa9-11eb-93b9-9e2c9128f10d.png)

**Comment by jmalizia** [comment]
je viens de créer un nouveau patient (foetus) et de créer une prescription pour faire le WF de bout en bout. Tout fonctionne à l'exception lorsque je soumets la prescription où j'ai une erreur (voir screenshot). Même si je soumets, le message d'erreur indique une erreur de sauvegarde (comme si je quitte et sauvegarde). Je suis incapable de sauvegarder peu importe l'option (soumettre, compléter plus tard ou quittez et sauvegarder) et la prescription ne se crée pas.
<img width="1440" alt="Screen Shot 2021-02-15 at 10 35 44 PM" src="https://user-images.githubusercontent.com/73133507/108015581-80d81600-6fde-11eb-8889-8428231e9dcc.png">
<img width="1179" alt="Screen Shot 2021-02-15 at 10 38 42 PM" src="https://user-images.githubusercontent.com/73133507/108015616-964d4000-6fde-11eb-9151-8389a22aeded.png">

**Comment by jmalizia** [comment]
Après avoir créé un patient et une prescription, je tombe sur une page semi-blanche; patient créé = Adam Lavoie (je ne vois pas le tableau des prescriptions/patients)
<img width="1409" alt="Screen Shot 2021-02-16 at 2 06 28 PM" src="https://user-images.githubusercontent.com/73133507/108109636-2bdce400-7060-11eb-9a97-3e6fe20924e0.png">

**Comment by YanLabCHU** [comment]
@jmalizia C'est pas en lien avec cette carte, celle ci est pour le formulaire de perscription. La page patient c'est https://github.com/Ferlab-Ste-Justine/clin-project/issues/614
