### ISSUE TITLE
Prescription - Section Histoire Familiale

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#665]
Voir les maquette pour voir les champs à afficher ainsi que l'ordre
https://www.figma.com/file/Hvh1kY1o0rzzO89IuOYITP/CLIN-Creer-une-prescription?node-id=2255%3A46236

**Remarque**
- L'affichage diffèrera si jamais il n'y a aucun historique familiale. À ce moment, le sous-titre `Condition(s) de santé chez un membre de famille` ainsi que sa sous-section (tableau) ne seront pas présent. Le tout sera remplacé par un label `Condition de santé chez  un membre de famille` avec la valeur `Aucune`. (Voir maquette)
- Si vraiment aucun champs de la section n'ont été remplis, ne montrer aucun champs et simplement afficher le message `Aucun renseignement saisie`. Par contre, dès qu'au moins un champs est rempli, montrer tous les champs et mettre "--" pour les champs vide

### DEFECTS
- [x] La couleur du texte `Aucune information saisie` devrait être #A7B4C3 (ajuster pour toutes les autres sections similaires aussi svp)

**Comment by jmalizia** [comment]
Les sections apparaissent avec des infos. Par contre lorsque je rentre dans cette prescription (en brouillon), les champs ne sont qui sont supposés être rempli ne sont pas rempli. Je me souviens qu'hier avant le dev de cette carte, les champs n'étaient pas remplis pour cette prescriptions. Alors je ne sais pas pour d'où les valeurs proviennent lorsqu'on affichage en mode résumé.

Ex: analyses en résumé --> valeur "PCA"
analyses dnas la prescription ouvert --> aucune sélectionné

Affichage en mode résumé
![Screen Shot 2021-02-19 at 4 03 32 PM](https://user-images.githubusercontent.com/73133507/108561630-95612a80-72cc-11eb-83dd-52288d22fc5c.png)
![Screen Shot 2021-02-19 at 4 03 44 PM](https://user-images.githubusercontent.com/73133507/108561637-97c38480-72cc-11eb-9f4f-c9ee6abc4968.png)

prescription ouverte
![Screen Shot 2021-02-19 at 4 03 44 PM](https://user-images.githubusercontent.com/73133507/108561637-97c38480-72cc-11eb-9f4f-c9ee6abc4968.png)

**Comment by francisprovost** [comment]
Ce ticket consiste seulement de la section `Histoire familiale` donc le bug que tu rapportes devrait être dans sa propre carte ou dans la carte pour la section des détails (mais elle est déjà fermée)

@YanLabCHU  travail, par contre, présentement dans cette section du côté formulaire. J'attendrais qu'il ait fini avant de faire le QA

**Comment by jmalizia** [comment]
je l'ai mis ici puisque histoire familiale afficher en mode preview vs la prescription ouverte différait en plus du reste.

**Comment by jmalizia** [comment]
Par contre, le fait que ce soit des petits morceaux reliés fait que tu as finis mais ce n'est réellement pas prêt pour le QA puisque Yanis travaille également dans cette section du côté formulaire. Nous devrions avoir des cartes de use case plutôt plus complet que des petis bout par ci, d'autres par là mais qui sont reliés/dépendants (@denis-crsj )

**Comment by denis-crsj** [comment]
@francisprovost mini defect en lien avec la couleur du texte, voir description et section DEFECT plus haut.

**Comment by denis-crsj** [comment]
All good
