### ISSUE TITLE
Prescription - Section Signes cliniques

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#666]
Cette section reste pas mal inchangée excepté qu'il faut ajouter une colonne `Catégorie` entre les colonnes `Observé` et `Terme`

https://www.figma.com/file/Hvh1kY1o0rzzO89IuOYITP/CLIN-Creer-une-prescription?node-id=1843%3A2051

**Remarque**
- Si vraiment aucun champs de la section n'ont été remplis, ne montrer aucun champs et simplement afficher le message `Aucun renseignement saisie`. Par contre, dès qu'au moins un champs est rempli, montrer tous les champs et mettre "--" pour les champs vide

### DEFECTS
- [ ] L'icône d'oeil doit être centré dans la colonne
- [ ] Le gris du background de la barre d'en-tête du tableau n'est pas le bon. La couleur devrait être #F1F5F9
![image](https://user-images.githubusercontent.com/64538118/110481118-37e32100-80b5-11eb-9a6d-f1c36a6a96a6.png)

**Comment by francisprovost** [comment]
La colonne terme est un lien dans figma mais ne l'est pas présentement dans l'app. Vers où ce lien doit aller?

CC: @jmalizia

**Comment by jmalizia** [comment]
@francisprovost Est-ce normal que la catégorie est toujours "Laboratory"? semble être hardcodé, est-ce qu'il te manque de l'info?

**Comment by francisprovost** [comment]
Je n'ai peut-être pas utilisé la bonne propriété. 

@YanLabCHU j'ai utilisé `get(hpo, 'category[0].coding[0].display', '')` est-ce que c'est la bonne chose ou jsuis dans le champs?

**Comment by denis-crsj** [comment]
@francisprovost mini defect ajouté à la description plus haut.

**Comment by denis-crsj** [comment]
@luclemo Dans les maquettes, les en-têtes de colonnes ne sont pas alignés avec le texte contrairement aux autres tableau. Est-ce normal ? Ou s'agit-il seulement d'une petite erreur d'alignement dans la maquette ?
