### ISSUE TITLE
Stabilisation création de prescription

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#674]
- [x] Boutton sauvegarder n'est pas disabled même si les informations sont incomplètes
- [x] On n'a pas de feedback visuel si la sauvegarde a été bien faite ou pas.
- [x] Ne retourne pas à la page du patient après avoir cliquer sur le boutton de sauvegarde
- [x] On ne peut ajouter un nouveau dossier médical
- [x] Ajouter une prescription. La section Signes cliniques du formulaire est déjà remplie par des valeurs sans qu’on ne l’ait ajoutées. Ce sont des valeurs qui étaient dans la prescription précédente affichées. Autrement dit, la section Signes cliniques ne se rafraichit pas à l’ouverture de la page.
- [x] On ne peut soumettre une nouvelle prescription pour un patient qui existe déjà. Quand on clique sur soumettre, rien ne se passe
- [x] Page Prescription. Mettre le nom ou l’acronyme de l'hôpital
- [x] Sélection du médecin responsable ne fonctionne pas

**Comment by jmalizia** [comment]
Defect
- incapable d'ajouter un nouveau dossier médical à une prescription --> plusieurs point
   - si je clique sur ajouter, le # du dossier et hôpital du dossier existant restent afficher et le bouton pour ajouter est nommé "Modifier". Si je clique sur X, à ce moment le dossier devient vide et choisi à nouveau dans le drop-down "Ajouter un dossier". Et rendu à ce point, lorsque je rentre le nouveau dossier et définit l'hôpital, je clique sur Ajouter et rien ne se passe.
   <img width="439" alt="Screen Shot 2021-02-16 at 2 17 35 PM" src="https://user-images.githubusercontent.com/73133507/108111011-1e285e00-7062-11eb-8d10-080eff226512.png">
<img width="469" alt="Screen Shot 2021-02-16 at 2 17 14 PM" src="https://user-images.githubusercontent.com/73133507/108111063-2da7a700-7062-11eb-8df1-f321ab2fb59d.png">
<img width="453" alt="Screen Shot 2021-02-16 at 2 24 26 PM" src="https://user-images.githubusercontent.com/73133507/108111452-b0306680-7062-11eb-9644-d28bd0a6936b.png">
<img width="397" alt="Screen Shot 2021-02-16 at 2 26 25 PM" src="https://user-images.githubusercontent.com/73133507/108111637-f685c580-7062-11eb-8a24-29e942d26b8f.png">
<img width="621" alt="Screen Shot 2021-02-16 at 2 18 43 PM" src="https://user-images.githubusercontent.com/73133507/108111249-70697f00-7062-11eb-9661-4193683a58d7.png">


   -

**Comment by YanLabCHU** [comment]
@jmalizia Le feature n'a pas encore été ajouté, en dehors du scope ici.
