### ISSUE TITLE
Impossible de créer un patient - Load à l'infini

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#675]
Impossible de créer un patient. Quand on rentre un nouveau RAMQ pour créer un patient, cela cherche sans fin

![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/90c74bd6-0e8f-4a59-bff1-a39c80a54851)

**Comment by jmalizia** [comment]
fixed
