### ISSUE TITLE
Prescription - Afficher le MRN par défaut lorsqu'il n'y en a qu'un seul

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#677]
Lorsqu’il y a un seul dossier médical (95% du temps), afficher le numéro par défaut.

**Comment by jmalizia** [comment]
bug réglé

**Comment by jmalizia** [comment]
feature semble avoir été supprimée à nouveau --> Si un seul, afficher le MRN automatiquement dans la section dossier médical
![Screen Shot 2021-04-08 at 8 16 33 AM](https://user-images.githubusercontent.com/73133507/114025087-bf51ba80-9842-11eb-9657-d1ddb2f64871.png)
![Screen Shot 2021-04-08 at 8 11 05 AM](https://user-images.githubusercontent.com/73133507/114024971-9f21fb80-9842-11eb-9a79-e921adfc0653.png)
![Screen Shot 2021-04-08 at 8 15 30 AM](https://user-images.githubusercontent.com/73133507/114024968-9f21fb80-9842-11eb-8de9-01bbf863bea4.png)

**Comment by jmalizia** [comment]
requête annulé, on avait décidé que l'utilisateur le choisisse en tout temps
