### ISSUE TITLE
Prescription - MRN - Supporter l'ajout d'un nouveau dossier médical

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#678]
![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/53232153-ce26-4b13-be53-84df39fdec4c)

### DEFECTS
- [x] Le nouveau numéro n'apparait pas dans la liste et le dropdown reste vide. Il faut que le nouveau numéro MRN qu'on vient d'ajouter soit affiché dans la liste et soit également celui sélectionné automatiquement dans le dropdown. Par contre le back-end fonctionne car si on quitte le formulaire et reviens, le nouveau MRN s'y trouve.
- [x] Il manque les placeholders dans les champs aussi
- [x] Aucun MRN ne doit être sélectionné par défaut lors de la création de la prescription

**Comment by denis-crsj** [comment]
@YanLabCHU Nouveau defect ajouté, voir section DEFECTS dans la description. Je remet donc la carte en "In progress"

**Comment by jmalizia** [comment]
bugs réglés
