### ISSUE TITLE
Impossible de soumettre une nouvelle prescription pour un patient qui existe déjà

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#679]
On ne peut soumettre une nouvelle prescription pour un patient qui existe déjà. Quand on clique sur soumettre, rien ne se passe.

![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/39fb9b1c-ee5c-406f-9302-dc6af676a1ac)

**Comment by jmalizia** [comment]
incapable de soumettre une nouvelle prescription pour un patient existant (essayé avec 2 prescriptions différentes pour Louis KJH)
![Screen Shot 2021-02-15 at 4 24 58 PM](https://user-images.githubusercontent.com/73133507/107994373-80258c80-6faa-11eb-9194-367f7cda6517.png)

**Comment by jmalizia** [comment]
bug réglé
