### ISSUE TITLE
Page Patient - Nouvelle prescription - Section signes clinique déjà rempli avec des valeurs

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#680]
1. Aller dans un patient qui n’a pas de prescription
2. Ajouter une prescription. 
3. La section Signes cliniques du formulaire est déjà remplie par des valeurs sans qu’on ne l’ait ajoutées. Ce sont des valeurs qui étaient dans la prescription précédente affichées. Autrement dit, la section `Signes cliniques` ne se rafraichie pas à l’ouverture de la page. 

![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/334459da-9fa6-448c-b2dd-6f6250e74aef)

![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/6858a8d7-1933-4bc6-9700-5a86360af030)

**Comment by jmalizia** [comment]
bug réglé
