### ISSUE TITLE
incapable de sauvegarder une prescription qui est débutée

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#688]
J'ai défini plusieurs valeurs mais incapable de la sauvegarder pour la compléter plus tard

![Screen Shot 2021-02-15 at 12.20.12 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/7b2fa711-903c-4c2b-9ac4-b9d481f81382)
![Screen Shot 2021-02-15 at 12.20.17 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/2801e38c-a344-4491-b6cc-8af451e89073)

**Comment by YanLabCHU** [comment]
Cannot reproduce

**Comment by jmalizia** [comment]
@YanLabCHU 
Incapable de soumettre ou sauvegarder et compléter une prescription en brouillon

![Screen Shot 2021-05-04 at 4 40 29 PM](https://user-images.githubusercontent.com/73133507/117067104-99132380-acf7-11eb-84b4-75fe1396d394.png)
![Screen Shot 2021-05-04 at 4 40 18 PM](https://user-images.githubusercontent.com/73133507/117067113-9b757d80-acf7-11eb-9f1d-207c01e7b636.png)

**Comment by YanLabCHU** [comment]
@jmalizia J'arrive pas à reproduire.
