### ISSUE TITLE
Prescription: Scroll dans la page est désactivé après avoir ouvert la dialog pour créer un Patient

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#690]
**Bug description**
On ne peut pas scroller dans la page de prescription après avoir ouvert la dialog de création de patient

**Steps To Reproduce**
1. Clique sur nouvelle prescription
2. Fermes la dialog
3. Clique sur n'importe lequel patient
4. Cliquer sur créer une prescription
5. On ne peut pas scroller verticalement

**Expected behavior**
On peut scroller

**Desktop (please complete the following information):**
 - Browser: Firefox

**Comment by jmalizia** [comment]
bug résole (testé dans Firefox et Chrome for mac)

**Comment by YanLabCHU** [comment]
C'est un bug qui se produit en local, pas en QA. 
Je l'ai toujours en local

**Comment by jmalizia** [comment]
je n'ai toujours pas ce problème, @YanLabCHU je te laisse tester de ton bord voir si tu l'as en local

**Comment by francisprovost** [comment]
Oui on l'a toujours en local. Rien n'a été fait pour le moment
