### ISSUE TITLE
Patient list: Pagination s'arrête la page 2

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#693]

**Comment by jmalizia** [comment]
la quantité de prescriptions varie selon la quantité d'affichage par page. 
si j'affiche 25 ou 50 --> 51 lignes
si j'affiche 100 ou 200 --> 52 lignes.
<img width="428" alt="Screen Shot 2021-02-16 at 2 28 22 PM" src="https://user-images.githubusercontent.com/73133507/108113423-7dd43880-7065-11eb-9c77-ed86ebfec146.png">
<img width="323" alt="Screen Shot 2021-02-16 at 2 28 41 PM" src="https://user-images.githubusercontent.com/73133507/108113421-7d3ba200-7065-11eb-8bbf-3abfc16262a2.png">
<img width="289" alt="Screen Shot 2021-02-16 at 2 28 29 PM" src="https://user-images.githubusercontent.com/73133507/108113422-7d3ba200-7065-11eb-9b30-0d360adfe93f.png">

**Comment by YanLabCHU** [comment]
C'est un autre problème.
