### ISSUE TITLE
incapable d'ouvrir une fiche d'un patient ou foetus sans prescription 

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#708]
J'ai essayé d'ouvrir 3 patients qui n'avait aucune prescription (statut = --), mais j'obtiens une page blanche dans les 3 cas. Si j'ouvre le profil d'un patient avec au moins une prescription, tout est beau.
- Pierre-Paul UISSE (22688)
- Sophie Maloie (23913 et 23914, un est le foetus et l'autre la mère)

Patient sans prescriptions
![Screen Shot 2021-02-18 at 1.54.12 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/84c79b38-ad49-4575-b737-267fd6b11903)

Patient avec prescriptions
![Screen Shot 2021-02-18 at 2.02.21 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/7cc8817d-9315-4783-bbdb-48db55f96730)

**Comment by francisprovost** [comment]
Les patients en example ont été effacé mais on semble pouvoir ouvrir la fiche d'un patient sans prescription présentement

**Comment by jmalizia** [comment]
bug réglé
