### ISSUE TITLE
Prescription: Invalid family link

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#709]
**Bug description**

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jmalizia** [comment]
@YanLabCHU besoin de plus de détail sur cette carte. De plus, je ne n'arrive pas à trouver 2 patients avec la même famille (j'en ai ouvert 5-6)
