### ISSUE TITLE
Ajuster nom du foetus dans tableaux des prescriptions

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#710]
Après discussion avec Lucas, dans le tableau des prescriptions/patients, lorsque le patient est un foetus, le terme foetus devrait apparaitre dans le nom

après discussion avec Lucas, le nom de famille du foetus resterait le même que celui de la mère, mais le prénom aurait plutôt la valeur "Foetus"

**Comment by denis-crsj** [comment]
All good
