### ISSUE TITLE
Erreur de frappe

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#714]
le terme "Organizer" devrait être "Organiser"  avec un s
-  dans le tableau prescription contient une erreur
- dans l'onglet Variant du parient au dessus du tableau des variants

![Screen Shot 2021-02-19 at 12 34 51 PM](https://user-images.githubusercontent.com/73133507/108540897-c54e0500-72af-11eb-81ad-8b1910e94d0e.png)

**Comment by denis-crsj** [comment]
Je ferme pour l’instant, sera ré-ouverte sous peu si nécessaire
