### ISSUE TITLE
autre prescription qui ouvre que celle sélectionnée

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#715]
**Bug description**
When clicking on a prescription of a patient that has many, I don't go into the prescription I selected it from the prescription table.

**Steps To Reproduce**
1. Select one prescritpion for a patient that has many in the prescription table
2. click on any. I clicked on the first in the list which was in "draft"
3. see error --> you always get to the first prescription tab which in this case is a prescription that was already approved.

**Expected behavior**
shoud open the prescription tab that I selected

**Screenshots**
I selected the one that is highlighted
![Screen Shot 2021-02-19 at 2.38.47 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/85fccc88-2618-4df7-930e-68d5c6f0a79a)

it opened this one instead
![Screen Shot 2021-02-19 at 2.38.56 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/cd3b6046-d106-4d89-9085-6c68da019112)

**Desktop (please complete the following information):**
 - OS: 11.2.1
 - Browser Chrome
 - Version 88.0.4324.182 (up-to-date)

**Comment by denis-crsj** [comment]
Je ferme pour l’instant, sera ré-ouverte sous peu si nécessaire
