### ISSUE TITLE
mauvaise ordre des onglets de prescriptions dans la page patient

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#716]
**Bug description**
mauvaise ordre des onglets de prescriptions dans la page patient. Les prescriptions sont en ordre de date chronologiques alors qu'elles devraient être dans l'ordre inverse (plus récentes avant et les plus vieilles à la fin)

**Steps To Reproduce**
1. Ouvrir la fiche d'un patient qui a plusieurs prescriptions
2. voir erreur --> les prescriptions sont en ordre de date chronologiques

**Expected behavior**
Les prescriptions devraient être dans l'ordre inverse (plus récentes avant et les plus vieilles à la fin)

**Screenshots**
CLIN
![Screen Shot 2021-02-19 at 2.38.55 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/7a71dc8c-7aa3-440b-b6ff-a6d5353818c5)

Maquette
![Screen Shot 2021-02-19 at 2.41.00 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/d8cfad11-941f-4a2a-aed1-caea84e9a9f7)

**Comment by denis-crsj** [comment]
Je ferme pour l’instant, sera ré-ouverte sous peu si nécessaire

**Comment by jmalizia** [comment]
bug réglé, dernière prescription créé est la première
