### ISSUE TITLE
Prescriptions: Les boutton 'Supprimer' 'Modifier' sont de couleur bleu même lorsqu'ils sont désactivé

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#718]
**Bug description**
Prescriptions: Les boutton 'Supprimer' 'Modifier' sont de couleur bleu même lorsqu'ils sont désactivé

**Steps To Reproduce**
1. Go to 'Prescription List'
2. Chose a submitted prescription
3. Hover over the  'Supprimer' or 'Modifier' button
4. See error!

**Expected behavior**
La couleur des boutton désactivés devrait être gris

**Screenshots**
https://images.zenhubusercontent.com/5f313d03d7df470e8324c4c8/ba5c4a0c-9c79-43ab-9a8c-fd770f72b562

**Comment by jmalizia** [comment]
bug still present
![Screen Shot 2021-02-25 at 11 13 40 PM](https://user-images.githubusercontent.com/73133507/109254027-22215200-77bf-11eb-9d3a-56bf4e8c597b.png)
![Screen Shot 2021-02-25 at 11 14 22 PM](https://user-images.githubusercontent.com/73133507/109254053-382f1280-77bf-11eb-94f2-f754f7c9320d.png)

**Comment by YanLabCHU** [comment]
Regression introduced with https://github.com/Ferlab-Ste-Justine/clin-frontend/pull/514

**Comment by jmalizia** [comment]
bug réglé
