### ISSUE TITLE
Prescription status: La note qu'on affiche devrait être la dernière

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#719]
Afficher la dernière note du changement de status au lieu de la première.

Présentement:
![Screenshot_2021-02-22 CLIN(1).png](https://images.zenhubusercontent.com/5f313d03d7df470e8324c4c8/f24fc22d-1a48-496c-a774-5b89d974917f)

**Comment by jmalizia** [comment]
incapable de tester. Je n'arrive pas à resoumettre une prescription que j'ai retournée comme incomplète et dont je modifie quelques champs
