### ISSUE TITLE
Modifier les relations familliale d'une prescription

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#720]

**Comment by jmalizia** [comment]
@YanLabCHU tu veux dire quoi plus précisément par "modifier les relations familiale d'une prescription"?

**Comment by YanLabCHU** [comment]
@jmalizia On peut mettre à jour la note et/ou changer le lien d'un FMH

**Comment by jmalizia** [comment]
bug réglé
