### ISSUE TITLE
Déplacer Ethnicité et Consanguinité de la ressource Patient --> à Observation

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#722]
Déplacer Ethnicité et Consanguinité de la ressource Patient --> vers la ressource Observation (TBD laquelle spécifiquement avec YM)

Règles d'affaires
- est définie à la première sauvegarde ou soumission de la première prescription
- si une nouvelle prescription est créée --> dupliquer ce qui est définie dans la première prescription
     - par contre, il est de modifier l'ethnicité ou la consanguinité d'une prescription à l'autre.

**Comment by denis-crsj** [comment]
@YanLabCHU Je vais fermer la carte mais comme on a mentionné plusieurs fois, j'aurais aimé voir un screenshot du code ou un peu de détails en commentaire pour confirmer que c'est fait. Essayons de ne pas oublier de l'ajouter la prochaine fois svp.
