### ISSUE TITLE
Modification des champs d'une prescription selon le statut

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#726]
Définition des champs d'une prescription pouvant être définis/modifiés selon le statut de celle-ci.

STATUT = SOUMISE/APPROUVÉE/REFUSÉE/COMPLÉTÉE
- aucun champs ne peut être modifié

- Champs ne pouvant être modifiables (Read-Only) pour éviter de complexifier le workflow d'une prescription (notamment, changer de médecin approbateur ou cocher d'autres analyses et devoir créer en créer des nouvelles).
     - Sélections d'analyses (seulement la sélection d'analyses) **INCOMPLÈTE** ou **BROUILLON**
     - médecin responsable **INCOMPLÈTE**

**Comment by denis-crsj** [comment]
Chaque statut a été testé et la modification en fonctionne bel et bien pas pour les cas mentionnés plus haut
