### ISSUE TITLE
Prescriptions: Les informations du CGH, investigation et indications sont manquantes dans certaines prescriptions

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#729]
**Bug description**
Lorsqu'on crée plusieurs prescriptions (plusieurs tests) en même temps. Seulement la première prescription affiche les informations des CGH, investigation et indications.
Voici le screen shot
![Screenshot_2021-02-24 CLIN(1).png](https://images.zenhubusercontent.com/5f313d03d7df470e8324c4c8/9c87de1c-a6e8-41fa-94e8-7171ba9d03d1)
![Screenshot_2021-02-24 CLIN.png](https://images.zenhubusercontent.com/5f313d03d7df470e8324c4c8/9ab8fd7f-6f74-4666-af80-cd00e8a2b66a)

**Steps To Reproduce**
1. Créer plusieurs prescriptions en même temps avec un CGH
2. Comparer les données dans la liste des prescriptions

**Comment by denis-crsj** [comment]
Chaque prescription affiche maintenant les sections CGH, Investigations et Indications : https://qa.clin.ferlab.bio/patient/33693
