### ISSUE TITLE
Prescriptions: Le résumé de l'investigation ne s'affiche pas pour les prescriptions

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#730]
**Bug description**
Le résumé ne s'affiche pas pour les prescriptions
![Screenshot_2021-02-24 CLIN.png](https://images.zenhubusercontent.com/5f313d03d7df470e8324c4c8/a3c8fda3-8514-4549-91d3-df953f36d199)
Problème lié à https://github.com/Ferlab-Ste-Justine/clin-project/issues/729

**Comment by jmalizia** [comment]
résumé de l'investigation apparaît maintenant correctement
