### ISSUE TITLE
Statut de la prescription "brouillon" mais aucune existe

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#731]
**Bug description**
Statut de la prescription est "brouillon" mais le patient n'a aucune prescription

**Steps To Reproduce**
1. Sélectionner un patient avec une prescription en brouillon (j'ai regardé PA0001-2-3-4-27-28, les 6 seuls avec une prescription en statut "brouillon"
2. Ouvrir la fiche du patient
3. See error

**Expected behavior**
statut devrait être "--"

**Screenshots**
Tableau des prescriptions
![Screen Shot 2021-02-25 at 10.58.07 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/fc37a735-2d1b-4cc6-b71d-02872a8da93f)

Fiche patient
![Screen Shot 2021-02-25 at 10.58.15 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/d25a3b88-243c-4b68-a10f-1801729b24d6)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 88.0.4324.182

**Comment by denis-crsj** [comment]
Je ferme pour l’instant, sera ré-ouverte sous peu si nécessaire
