### ISSUE TITLE
Fix multiple sur la création de patient et changement de status

### ISSUE THREAD

**Issue by francisprovost** [Ferlab-Ste-Justine/clin-project#733]
## Création de patient
- [x] rename hospital for organization (in the form)
- [x]  validation de la RAMQ, `invalide` et non `invalid`
- [x]  "Mask" pour la RAMQ (espace + caps)
- [x]  Maj pour les noms
- [x]  Calendrier selon la langue (FR ou EN) et placeholder pour le format
- [x]  Bloquer le copy/paste pour les champs de RAMQ

## Changement de status
- Incomplète: Cette prescription est incomplète. Veuillez préciser la nature des informations manquantes qui devront être soumises par le médecin prescripteur.
- Refusée: Cette prescription est refusée Veuillez préciser les raisons de ce refus.
- Approuvée: cette prescription est approuvée et prête à être exécutée. Les données cliniques de cette prescription ne pourront plus être modifiées.
- Complétée: Cette prescription a été exécutée et les résultats sont maintenant disponibles.

**Comment by jmalizia** [comment]
tous les bugs ont été réglés
