### ISSUE TITLE
pas toutes les prescriptions ne s"affichent dans le tableau des prescriptions

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#735]
**Bug description**
vu par défaut de 25/page --> 48 prescriptions (25+23). 
Si je change la vue à 50/page --> 50 prescriptions (50).
Si je change la vu à 100 ou 200/page --> 51 prescriptions 

**Screenshots**
25/page
![Screen Shot 2021-02-26 at 4.55.21 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/2bb6366d-ea48-46fe-9f59-96a760c81e63)
![Screen Shot 2021-02-26 at 4.58.07 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/0f4921cb-6a5d-421c-b11f-c75db3ed7ed0)

50/page
![Screen Shot 2021-02-26 at 4.58.14 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/09dfa624-0c6b-4995-8c85-02fac7e1e5e2)

100 ou 200/page
![Screen Shot 2021-02-26 at 4.58.37 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/59309978-cbcd-4670-852a-c3cd0f79ca77)

**Comment by denis-crsj** [comment]
Je ferme pour l’instant, sera ré-ouverte sous peu si nécessaire

**Comment by jmalizia** [comment]
problème récurrent à nouveau

**Comment by jmalizia** [comment]
74 prescriptions lorsque j'affiche 25 ou 50 lignes par page et je tombe a 87 lorsque j'affiche 100 ou 200 lignes par page
![Screen Shot 2021-04-16 at 12 14 11 PM](https://user-images.githubusercontent.com/73133507/115053661-5f47bd80-9ead-11eb-991a-23d284f8b653.png)
![Screen Shot 2021-04-16 at 12 14 16 PM](https://user-images.githubusercontent.com/73133507/115053668-61118100-9ead-11eb-9f02-68653e9c772d.png)
![Screen Shot 2021-04-16 at 12 14 22 PM](https://user-images.githubusercontent.com/73133507/115053679-640c7180-9ead-11eb-8164-5b95bacc0186.png)
![Screen Shot 2021-04-16 at 12 14 28 PM](https://user-images.githubusercontent.com/73133507/115053687-666ecb80-9ead-11eb-932c-a4c1ce7e0c69.png)

**Comment by jmalizia** [comment]
bug encore présent. J'ai un patient qui a 11 prescriptions mais seulement 4 apparaissent dans le tableau des prescriptions. En fait, seulement 10 prescriptions au complet apparaissent dans CLIN et seulement 4 pour ce patient spécifiquement

Patient ID = 9073
![Screen Shot 2021-04-22 at 4 36 09 PM](https://user-images.githubusercontent.com/73133507/115782031-30d45180-a389-11eb-934a-236300cf2273.png)

tableau des prescriptions
![Screen Shot 2021-04-22 at 4 40 26 PM](https://user-images.githubusercontent.com/73133507/115782249-73962980-a389-11eb-8101-4a04e6f71be4.png)

**Comment by YanLabCHU** [comment]
@jmalizia  C'est normal, c'était des patients qui existaient avant le cleanup ES et qui avaient des prescriptions. Après le cleanup, seulement les nouvelles prescriptions de ce patients sont affiché dans la liste.
Tu peux tester en créant avec un nouveau patient. C'est presque toujours mieux de tester en créant un nouveau patient.
