### ISSUE TITLE
Incapable de créer une fiche patient avec RAMQ

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#736]
**Bug description**
lorsque je veux créer un patient avec un RAMQ, je définis et fais suivant mais j'ai un message d'erreur. --> erreur semble être lié au fait qu'il y a des espaces dans le front end.

J'ai tenté 2x avec un patient de type foetus et 1x avec un patient de type patient. Je me suis déconnecté, fermé mon onglet, en ai ouvert un autre et me suis reconnecté toujours avec le même résultat.

![Screen Shot 2021-02-26 at 5.05.36 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/601344ac-c738-4150-93a5-5617dedf081c)

**Comment by denis-crsj** [comment]
Problème résolu. J'ai été en mesure de créer un patient correctement.

![image](https://user-images.githubusercontent.com/64538118/110474662-f13df880-80ad-11eb-9c38-55a5789376df.png)
