### ISSUE TITLE
Créer index ES de prescriptions

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#737]
Pour la MVP, Créer l'index ES de les prescriptions et la "plugger" sur la liste des prescriptions.

Actuellement, c'est un index ES de patient qui est utilisé pour la liste des prescriptions. Cet index (patient) ne sera pas supprimé mais sera mis de côté pour après la MVP --> lorsque nous aurons un tableau contenant les 2 onglets où nous en aurons de nouveau besoin (un pour les Patients, et l'autre pour les prescriptions).

**Comment by denis-crsj** [comment]
Je ferme pour l’instant, sera ré-ouverte sous peu si nécessaire

**Comment by jmalizia** [comment]
Bogues trouvés:
- barre de recherche ne fonctionne pas en 2 points
   - si je cherche un patient via son ID ou son nom, rien n'est filtré --> ne fonctionne pas dans les 2 onglets
   - dès que je rentre le chiffre 1 --> blank page
![Screen Shot 2021-04-21 at 4 20 02 PM](https://user-images.githubusercontent.com/73133507/115616284-08335580-a2be-11eb-9109-8a3765c4d1dd.png)
![Screen Shot 2021-04-21 at 4 20 07 PM](https://user-images.githubusercontent.com/73133507/115616309-108b9080-a2be-11eb-9092-1251c4d7a873.png)
![Screen Shot 2021-04-21 at 4 23 21 PM](https://user-images.githubusercontent.com/73133507/115616327-15504480-a2be-11eb-9124-b3596f132778.png)

- blank page mais seulement pour le patient 1163

**Comment by jmalizia** [comment]
bug 1-2-3-6 sont réglés, les 4 et 5 ont été mis dans la carte 846. Donc je ferme cette carte-ci
