### ISSUE TITLE
Prescription: Afficher l'éthnicité et la consanguinité

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#739]
Afficher l'éthnicité ou la consangunité si elle est présente dans une prescription, sinon juste `--`

![Screenshot_2021-03-04 CLIN.png](https://images.zenhubusercontent.com/5f313d03d7df470e8324c4c8/148eb008-fae2-4bff-8961-dd1177f07d5c)

**Comment by denis-crsj** [comment]
All good
