### ISSUE TITLE
Formulaire Prescription: L'histoire familliale est doublée lorsqu'on modifie une prescrition

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#742]
Lorsqu'on modifie une prescription avec une histoire familliale, les membres de la familles sont doublés
Exemple: 
![Screenshot_2021-03-04 CLIN(1).png](https://images.zenhubusercontent.com/5f313d03d7df470e8324c4c8/266a6776-1368-4d75-9958-9a3b0fe042dc)

### DEFECTS
- [x] L'historique n'est plus doublé mais il y a quand même une 2e barre vide qui apparait par défaut. Il faudrait l'enlever.
- [x] Le "X" pour enlever une ligne est très loin à droite
- [x] Cliquer sur le bouton Ajouter" fait planter et donne une page blanche.
- [x] Le design et le placement des champs avec le bouton ajouter ne respecte pas la maquette. Voir les maquettes dans Figma
![image](https://user-images.githubusercontent.com/64538118/110531448-90341600-80e9-11eb-80b5-107b1f8c5da5.png)

**Comment by denis-crsj** [comment]
@francisprovost Mini defect, voir description avec section DEFECTS. Je remet la carte en "In progress"

**Comment by denis-crsj** [comment]
@francisprovost 2 régressions en lien avec le fix du defect original

**Comment by jmalizia** [comment]
ne reste que le dernier defect, remplacer le terme dur drop-down du lien parental lorsque non défini
"Relation parentale" --> devrait être "Lien parental"

![Screen Shot 2021-03-18 at 4 22 31 PM](https://user-images.githubusercontent.com/73133507/111692826-3f699f00-8806-11eb-8747-4f743ad4d7b0.png)

**Comment by jmalizia** [comment]
@francisprovost 
petite erreur de grammaire qu'il reste tant qu'à être dedans --> enlever le "e" à la fin de parental 

Label attendu --> Lien parental

![Screen Shot 2021-03-19 at 9 54 12 AM](https://user-images.githubusercontent.com/73133507/111790989-2958ee80-8899-11eb-8588-f850db71c995.png)

**Comment by jmalizia** [comment]
réglé
