### ISSUE TITLE
HPO: L'age at onset devrait être optionel

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#748]
- L'Age d'apparition d'un phenotoype devient optionel, et seulement l'interprétation du phenotype devient nécessaire.
- Enlever la hpo-category

![Screenshot_2021-03-12 CLIN](https://user-images.githubusercontent.com/69463110/110936776-694f2d00-82ff-11eb-9efa-14f390d3e190.png)

**Comment by jmalizia** [comment]
fixed
