### ISSUE TITLE
Ajout info pour page Variant

### ISSUE THREAD

**Issue by claudia1296** [Ferlab-Ste-Justine/clin-project#749]
Ajouter l'information du sexe et de la position pour les donors de variantDetails

- [x] Ajouter un endpoint au backend pour récupérer les information du sexe et proband de patients.

**Comment by YanLabCHU** [comment]
@claudia1296 Peux tu QA et fermer la carte?

**Comment by jmalizia** [comment]
@claudia1296 est-ce que le QA a été fait?

**Comment by claudia1296** [comment]
tout fonctionne c'est bon !
