### ISSUE TITLE
Quitter une prescription Incomplète sans l'éditer la remet en statut Brouillon

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#752]
Si une prescription qui est en statut `Incomplète` est reprise par un médecin mais qu'il la quitte sans sauvegarder en cliquant sur le bouton `Annuler`, la prescription change pour le statut Brouillon.

La valeur pour les champs suivants changent également 
- Soumise par
- Date de soumission

**Comportement attendu**
Si le médecin annule ses changements, la prescription ne doit pas changer, ni son statut, ni aucune valeur car rien n'a été changé.

**Comment by jmalizia** [comment]
bug réglé
