### ISSUE TITLE
Infos générales de Prescription - Page blanche et erreurs d'affichages

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#753]
La section générale de la prescription dans la page Patient a quelque defects :
- Le `i` à côté du mot statut n'est pas de la bonne couleur
- Retirer le `i` à côté du nom du médecin pour le champs `Soumise par`
- Le `i` à côté du Médecin responsable fait planter l'app avec une page blanche sur le mouse over

**Comment by jmalizia** [comment]
@YanLabCHU 
Defects restants:
- [ ] Le i à côté du mot statut n'est pas de la bonne couleur --> devrait être bleu et non gris
- [ ] Retirer le i à côté du nom du médecin pour le champs Soumise par --> toujours présent

CLIN
![Screen Shot 2021-03-18 at 4 05 24 PM](https://user-images.githubusercontent.com/73133507/111690814-0a5c4d00-8804-11eb-973d-c332ae707e06.png)

SPEC
![Screen Shot 2021-03-18 at 4 06 23 PM](https://user-images.githubusercontent.com/73133507/111690808-08928980-8804-11eb-906b-fbb84d4fcb47.png)

**Comment by jmalizia** [comment]
3 bugs réglés
