### ISSUE TITLE
Bannières de Succès et d'Erreur manquantes

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#757]
https://www.figma.com/file/Hvh1kY1o0rzzO89IuOYITP/CLIN-Creer-une-prescription?node-id=2255%3A44501

**Comment by denis-crsj** [comment]
@luclemo Lucas, pourrais-tu juste ajouter un peu de détails en lien avec els règles d'affaires UX pour l'affichage des bannières `Success` et `Error` svp ?

**Comment by luclemo** [comment]
C'est dans les post-it juste à coté de chaque bannière.
Est-ce qu'il y a des questions précises?

<img width="300" alt="Pasted_Image_2021-03-15__2_13_PM" src="https://user-images.githubusercontent.com/1451515/111201038-bdc10980-8598-11eb-9046-a8e73d0b69b6.png">

**Comment by francisprovost** [comment]
@luclemo @denis-crsj Pour un errur on affiche présentement le petit "popup" qu'on utilise à plusieurs endroit. On reste sur la page du formulaire ce qui permet à l'utilisateur de re-soumettre si c'est temporaire ou modifier ses valeurs si c'est relié à ceci. Si on met la bannière dans la page patient, l'utilisateur va perdre ses changements.

Voulons-nous rester avec le flow courant ou on ajoute la bannière d'erreur?

Pour la bannière de succès je vais faire les modifications en lien avec ça

**Comment by luclemo** [comment]
Oui @francisprovost tu as raison il faut garder le user dans son flow actuel lors d'une erreur.

Le pop-up en question... est-ce un modal qui affiche un message + bouton de confirmation? Si oui 👍. Si non, je pense qu'il serait mieux d'afficher ce genre de modal car les petit "slide in" ne sont pas très visible et le user risque de ne pas le voir. 

De plus cela nous permet, lorsque possible, d'afficher un message plus explicite (genre, c'est quoi l'erreur au juste).

**Comment by francisprovost** [comment]
Oui présentement il s'agit seulement du slide in (https://ant.design/components/message/) 

Je suggère de remplacer l'erreur par https://ant.design/components/modal/#components-modal-demo-info

**Comment by jmalizia** [comment]
bug réglé
