### ISSUE TITLE
Espacement trop grand entre les numéros d'MRN

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#758]
L'espacement actuel semble respecter les maquettes mais il faudrait le réduire un peu quand même.

![image](https://user-images.githubusercontent.com/64538118/111153933-f21cd180-8568-11eb-9b1f-5bf737b20ec9.png)

Je suggère de retirer le `margin bottom: 8px`, ca semble être mieux après

![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/239d27ca-42a4-4e80-ba8e-5238f7dabdeb)

**Comment by jmalizia** [comment]
problème réglé
