### ISSUE TITLE
Implémenter un endpoint permettant de savoir si la modification d'un profil patient est possible

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#759]
La modification d'un profile patient est possible si: 
- [x] Aucune prescription n'a été soumise pour un patient
- [x] Dans le cas d'une fiche patient mère/fetus, puisque les fiches sont étroitement liés, aucune precription soumise dans un des deux profil (peu importe lequel)

**Comment by jmalizia** [comment]
2 points implantés avec succès
