### ISSUE TITLE
Affichage du dropdown d'interprétation dans la section des signes clinique

### ISSUE THREAD

**Issue by denis-crsj** [Ferlab-Ste-Justine/clin-project#760]
- Insérer un espace entre le symbole et l'interprétation
- Centré l'icône verticalement avec le texte
- Les icônes doivent être de couleur dans le dropdown également

![image.png](https://images.zenhubusercontent.com/5ea980d6189dd52c91ddddfa/febf5322-2cd9-4f1c-8763-a26df6f868b9)

**Comment by jmalizia** [comment]
3 bugs réglés
