### ISSUE TITLE
Prescriptions manquantes pour les patients importés de Google Sheet

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#766]
Backend: Certaines ServiceRequest sont manquantes
Frontend: On ne voit pasles prescriptions
Screenshot: 
![prescription](https://user-images.githubusercontent.com/69463110/111358279-8a49b200-8660-11eb-874a-d0c2ee2ef644.png)

**Comment by YanLabCHU** [comment]
@jecos Peux tu QA ça?

**Comment by jmalizia** [comment]
@jecos est-ce que tu as fais le QA?
