### ISSUE TITLE
Sauvegarder et quitter ne fonctionne pas si patient n'a aucun RAMQ

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#769]
Lorsque je crée une prescription pour un patient qui n'a pas de RAMQ, un modal spécifiant que la RAMQ est manquante et que je dois sauvegarder et quitter. Par contre, le bouton sauvegarder et quitter ne fonctionne pas --> rien ne se passe et je reste coincer là.
![Screen Shot 2021-03-16 at 4.20.00 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/b6d7c20d-4836-4069-84e5-ec77dd71279a)

De plus, si retourne à la page patients (en réappuyant sur mon favori CLIN) et que j'ouvre une prescription en brouillon d'autre patient (qui a un RAMQ) le modal revient ou que je crée une nouvelle prescription pour un patient qui a déjà au moins une autre prescription à son dossier

Patient avec prescription BROUILLON
<img width="1079" alt="Screen Shot 2021-03-16 at 4 31 10 PM" src="https://user-images.githubusercontent.com/73133507/111376054-5fb62400-8675-11eb-86c9-50c7d518c257.png">
<img width="540" alt="Screen Shot 2021-03-16 at 4 34 11 PM" src="https://user-images.githubusercontent.com/73133507/111376146-765c7b00-8675-11eb-95ca-92bb5113bc3b.png">

Patient nouvelle prescription mais au moins 1 existe déjà
<img width="944" alt="Screen Shot 2021-03-16 at 4 36 02 PM" src="https://user-images.githubusercontent.com/73133507/111376469-dbb06c00-8675-11eb-8a5f-3c177dd2f2bc.png">
<img width="701" alt="Screen Shot 2021-03-16 at 4 35 56 PM" src="https://user-images.githubusercontent.com/73133507/111376470-dc490280-8675-11eb-881f-9dcc68fe8799.png">

**Comment by francisprovost** [comment]
J'ai ramené le ticket dans le backlog. La branche ouverte par @YanLabCHU ne règle pas le problème pour la spec demandé, il ne fait que retiré le message complètement le temps de régler le problème complètement

**Comment by YanLabCHU** [comment]
Mes changements enlèvent le 'feature'. (J'ai laissé le react component, par contre, pour que justement tu détermines si on le garde ou le supprime). Mais les spécifications de cette tâche sont à revoir @francisprovost @jmalizia @vferretti 
@francisprovost Il vaut que tu travilles sur autre chose pour l'instant

**Comment by francisprovost** [comment]
@jmalizia je t'assigne la tâche pour le moment afin de déterminer ce qui se passe avec la spec concernant ce ticket
