### ISSUE TITLE
Formulaire Prescription: Boutton 'Suivant' est activé même si l'intérprétation du phenotype est manquante

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#770]
![Formulaire prescription.png](https://images.zenhubusercontent.com/5f313d03d7df470e8324c4c8/47e810fe-51a7-470c-a145-e9fb2658486d)

**Comment by jmalizia** [comment]
bug réglé, si je supprime l'interp., le bouton suivant se désactive puis se réactive si je rajoute
