### ISSUE TITLE
Page prescription: Sauvegarder une prescription brouillon affiche le message 'Cette prescription soumise avec succès'

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#773]
Lorsqu'on sauvegarde une prescription brouillon, un message 'Prescription soumise' apprait comme dans cet exemple: 
![prescription](https://images.zenhubusercontent.com/5f313d03d7df470e8324c4c8/59552ce7-f2e9-458f-b1b3-55c442e13f37)

**Comment by jmalizia** [comment]
bug fixed
