### ISSUE TITLE
Modification info patient ne fonctionne pas

### ISSUE THREAD

**Issue by luclemo** [Ferlab-Ste-Justine/clin-project#776]
## Prototype

https://www.figma.com/proto/IG5yCPj7qamtxsoU8bnl6r/CLIN-Creer-un-patient?node-id=454%3A55451&viewport=2913%2C-98%2C0.3894442915916443&scaling=min-zoom

## Bugs
- [x] Bouton soumettre de marche pas
   - Impossible d'apporter un changement car le bouton soumettre ne semble pas fonctionner (👉 https://recordit.co/VMgxms1T4f)
- [x] Modification persistantes quand on clique sur "annuler"
   - Si j'apporte une modification (ex: nom, supprimer un MRN etc) et que je clique sur annuler, lorsque j'ouvre le formulaire de nouveau les changements sont persistants (incluant des MRN supprimés). (👉  https://recordit.co/3zq93QVczb)

## UI
- [x] Ajouter le pop-confirm pour la suppression d'un MRN
- [x] Ajouter les placeholders pour les champs MRN 
- [x] Laisser le bouton soumettre en mode enabled en tout temps (pour simplifier)
   - Actuellement il y a une incohérence pour le state du bouton soumettre: il est enabled pour tout changement sauf lorsque
on active l'ajout d'un MRN. Le laisser en mode active en tout temps pour réduire la confusion

---

![Pasted_Image_2021-03-23__3_40_PM.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/e20cd6c7-045e-4c18-bf63-ef5edf61fc8a)

![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/8959c781-9113-444b-8ace-b6801ead0129)

**Comment by francisprovost** [comment]
@luclemo Pour le bouton qui est disable, il réagit présentement comme le formulaire de création de patient. Si on supprime complètement le prénom, par example, le bouton sera disable (dans le fond dès que le formulaire passe pas la validation).

À mon avis on devrait le laisser comme ça pour une question de constance entre les deux mais sinon, comment voulons-nous affiché l'état invalide du formulaire? Message sous l'input ?

**Comment by francisprovost** [comment]
Je n'ai pas fait l'histoire de disable étant donné que ça match ce qu'on a dans la création présentement. À voir qu'est-ce qu'on fait.

**Comment by jmalizia** [comment]
reste les 3 bugs qui n'ont pas été cochés

voir vidéos pour mes tests

Modification persistantes quand on clique sur "annuler"
https://user-images.githubusercontent.com/73133507/113336189-fe888480-92f3-11eb-90a2-093d0468b0a8.mov



Placeholders + pop confirmation pour supprimer
https://user-images.githubusercontent.com/73133507/113336167-f7fa0d00-92f3-11eb-9cee-fe91f5493285.mov

**Comment by jmalizia** [comment]
Les 3 derniers bugs ont été réglés
