### ISSUE TITLE
Détails patient: Affiche le mrn au lieu de la RAMQ dans certains cas

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#778]
Lorsqu'un patient n'a pas de RAMQ, mais a deux ou plus MRN, le deuxième MRN est affiché au lieu de la RAMQ.

Exemple: 
![ramq.png](https://images.zenhubusercontent.com/5f313d03d7df470e8324c4c8/b5ac728a-de15-4eac-9eff-0b98a614d7ab)

**Comment by jmalizia** [comment]
bug réglé
