### ISSUE TITLE
Prescription: Dans certains cas, le changement des signes cliniques dans une prescription se reflètent dans une autre

### ISSUE THREAD

**Issue by YanLabCHU** [Ferlab-Ste-Justine/clin-project#785]
Dans certains cas, le changement des signes cliniques dans une prescription se reflètent dans une autre, sans qu'on ait sauvegarder l'autre prescription.

Exemple: 
![Premiere prescription.png](https://images.zenhubusercontent.com/5f313d03d7df470e8324c4c8/6ab6f872-e6c8-4d99-b728-59750a30557f)

![Deuxieme Prescription.png](https://images.zenhubusercontent.com/5f313d03d7df470e8324c4c8/3c8c1e59-048f-4b8b-a568-c3ae5e0d3ca3)

**Comment by jmalizia** [comment]
une autre d'un même patient ou peu importe le patient?

**Comment by jmalizia** [comment]
bug réglé
