### ISSUE TITLE
Validation sur RAMQ disparait si champs RAMQ sont préremplis

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#789]
Si on entre un RAMQ d'un patient existant, au modal de patient trouvé, on ferme et qu'on crée un nouveau patient, les champs RAMQ sont préremplis, et je peux créer un nouveau patient avec le RAMQ existant sans erreur

**Comment by francisprovost** [comment]
Je close ce ticket étant donné que c'est un problème qui arrive parce qu'on peut avoir une situation où les champs sont pré-remplis ou pas reset. En fixant les 2 tickets liés à celui-ci, ce n'est pas un "vrai" problème
