### ISSUE TITLE
Impossible de créer foetus pour mère déjà existante 

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#791]
Impossible de créer un patient de type foetus avec un RAMQ déjà existant

dès que l'on choisit le sexe --> erreur 
+
Hôpital n'est pas défini si on crée un foetus pour un patient (mère) déjà existant
- si on choisit même hôpital = erreur doublon MRN
- si choisit hôpital = erreur après soumission

Puisque nous avons l'info, nous devrions être capable de populé l'hôpital du MRN de la mère

**Comment by francisprovost** [comment]
L'erreur à la création a été réglé en fesant #786. Reste du billet à faire

**Comment by jmalizia** [comment]
bug réglé
