### ISSUE TITLE
bouton compléter plus tard ne fonctionne pas

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#796]
Je crée une une nouvelle prescription et rempli la page 1 du formulaire de prescription puis clique sur "Compléter plus tard" --> rien ne se passe

**Comment by YanLabCHU** [comment]
@jmalizia J'arrive pas à reproduire. Il manque peut être de l'information.

**Comment by jmalizia** [comment]
incapable de reproduire aujourd'hui. Réouvrera si on arrive à reproduire à nouveau
