### ISSUE TITLE
Incapable de modifier l'analyse d'une prescription brouillon

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#797]
Lorsque je retourne dans une prescription en brouillon (qui n'a jamais été soumise), je ne peux modifier l'analyse.

--> Tant que la prescription n'est pas soumise, nous pouvons modifier l'analyse. Par contre, lorsqu'elle est soumise ou à un statut ultérieur où elle est retournée en "incomplète", il n'est plus possible de modifier l'analyse de la prescription

**Comment by YanLabCHU** [comment]
Ce n'était pas dans les requirements, c'est un feature

**Comment by jmalizia** [comment]
n'était pas écrit, mais nous avions parlé avec Vincent, Lucas, Denis, toi et moi à notre rencontre du 22 février et nous ne bloquions que les changements à l'analyse sélectionnée (et également du médecin responsable) que si la prescription était retournée comme incomplète.

**Comment by YanLabCHU** [comment]
Où est la carte pour ça?

**Comment by YanLabCHU** [comment]
Y a tu une carte qui a été créee pour ça? Avant que celle ci soit remontée comme defect?

**Comment by jmalizia** [comment]
feature -> j'ai retrouvé une carte (726) que j'ai créé en février qui spécifie ce que tu as codé (correctement) où je spécifie que nous ne pouvons modifier l'analyse une fois sélectionnée, si en mode brouillon ou incomplète

**Comment by jmalizia** [comment]
bien implanté
