### ISSUE TITLE
mauvais modal de modif patient qui ouvre pour un foetus

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#803]
C'est le modal de modification de la mère qui apparait lorsque je veux modifier la fiche d'un foetus
![Screen Shot 2021-03-30 at 9.32.56 AM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/731837d9-e51a-45f0-a31b-011e9debe579)

**Comment by jmalizia** [comment]
@YanLabCHU 
le modal de modification devrait afficher les infos du foetus plutôt que de la mère

**Comment by YanLabCHU** [comment]
@jmalizia QA

**Comment by jmalizia** [comment]
@YanLabCHU pas complètement résolu.

1) quand je clique sur le bouton modifier de la fiche du **_foetus_** -> nom n'est pas bien affiché, semble être la mère, mais c'est bel et bien le foetus (je le vois selon le sexe que j'avais défini)
![Screen Shot 2021-04-06 at 3 23 09 PM](https://user-images.githubusercontent.com/73133507/113771756-cc12c900-96f1-11eb-8ff4-9cbefbd48533.png)

2) quand je clique sur modifier de la page de la **_mère_**, c'est le modal du foetus qui ouvre (on le voit via le sexe)
![Screen Shot 2021-04-06 at 3 23 23 PM](https://user-images.githubusercontent.com/73133507/113772063-2d3a9c80-96f2-11eb-9ce9-4606c98ce7ca.png)
![Screen Shot 2021-04-06 at 3 23 28 PM](https://user-images.githubusercontent.com/73133507/113772062-2d3a9c80-96f2-11eb-851c-4769e7b3eab0.png)

**Comment by jmalizia** [comment]
le nom dans le modal d'édition du patient n'est pas conforme selon les specs --> devrait être POROSHTICA Axa
- sans virgule
- NOM en majuscule
- Prénom, seulement la première lettre en majuscule

**Comment by YanLabCHU** [comment]
@jmalizia Crée une nouvelle carte avec ces précision, ça sort du scope de cette carte.

**Comment by jmalizia** [comment]
ben n
