### ISSUE TITLE
connexion 

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#805]
Nous restons connectés à CLIN lorsque l'on ferme l'onglet ou fenêtre où CLIN est ouvert.

Connectez-vous à CLIN. Fermer la fenêtre browser. Ouvrez une nouvelle fenêtre et allez à CLIN. On est encore connecté à CLIN.

https://user-images.githubusercontent.com/73133507/113196043-07645200-9231-11eb-8172-e93884b66475.mov

**Comment by jmalizia** [comment]
@vferretti @luclemo  si nous faisons ainsi, un user qui a plusieurs onglets d'ouverts, s'il en ferme un, déconnectera automatiquement les autres. 

Au niveau du UX, est-ce quelque chose que nous voulons faire ou bien laissons-nous le cookie d'1h actif et si l'utilisateur ferme la fenêtre par erreur, il peut réouvrir sans reconnecter tout simplement.

**Comment by luclemo** [comment]
On laisse comme ça— le user reste connecté tant et aussi longtemps que sont cookie le permet, même s'il ferme ses fenêtres.

> un user qui a plusieurs onglets d'ouverts, s'il en ferme un, déconnectera automatiquement les autres

Je n'arrive pas à reproduire ce problème. Actuellement je peux avoir trois onglets clin d'ouverts. Je peux les fermer un par un sans que cela n'ai un impact sur les autres. Et c'est le comportement désiré.

**Comment by jmalizia** [comment]
le behavior que tu as est celui qui est voulu et implanté
