### ISSUE TITLE
Hover sur le MRN dans la prescription ne fonctionne pas

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#810]
Hover sur le MRN ne fonctionne pas lorsqu'on est par dessus

CLIN
![Screen Shot 2021-03-31 at 10.55.04 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/d09420b8-eda4-4cd2-80a6-0c78e590fd86)

Maquette
![Screen Shot 2021-03-31 at 10.58.37 PM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/731e28f1-c73c-42aa-a012-f2f00ce8f58c)

**Comment by jmalizia** [comment]
j'ai d'autres à cartes à créer en lien aussi avec ce problème je les ferai demain matin

**Comment by francisprovost** [comment]
Tel que discuter par le passé, on ne peut pas éditer un MRN donc ce feature ne peut pas être fait

**Comment by jmalizia** [comment]
Impact sur les prescriptions en cours --> on doit refléter toutes les modifs dans les ressources qui l"utilisent

**Comment by jmalizia** [comment]
Vincent: on ne modifie que dans le profil patient, et non dans la prescription. Donc on ferme cette carte
