### ISSUE TITLE
validation du sexe + DoB sur champs RAMQ ne semble pas fonctionner

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#812]
Lorsque je rentre un RAMQ pour un patient de type "patient" (ne s'applique pas sur les foetus), le sexe ainsi que la date de naissance ne sont pas générés automatiquement. 

Sexe → si la 2e pair de chiffre (3e et 4e chiffre) de la RAMQ (RAMQ12**34**5678) 
        - a une valeur entre 1 et 12 → masculin
        - a une valeur entre 51 et 62 → féminin

DoB → pour la date de naissance → prendre les 6 premiers chiffres suivant les 4 lettres
        - Si le mois (3e et 4e chiffres) a une valeur entre 51 et 62 → déduire la valeur de 50 pour obtenir le bon mois

Doit s'appliquer 
- à la création d'un profil patient 
- validation sur le RAMQ défini pour un foetus pour que le mois ne puissent être entre 1 et 12 --> devra toujours être entre 51 et 62)

            Spécifications du # de la RAMQ
            1 -  3 premières lettres du nom de famille
            2 - 1 lettre du prénom
            3 - 2 derniers chiffres de l’année de naissance
            4 - 2 chiffres du mois de naissance (auquel on additionne 50 pour indiquer le sexe féminin)
            5 - 2 chiffres du jour de naissance
            6 - Code administratif à l’usage de la RAMQ

**Comment by francisprovost** [comment]
Ce requirement là avait été retiré quand on a fait la tâche pour simplifier/accélérer le développement. (Si je me souviens bien c'est @denis-crsj ou @luclemo qui avait fait le call) 

Si on veut le faire je le taguerais plutôt comme une feature

**Comment by luclemo** [comment]
@francisprovost @jmalizia Oui on avait bien dit que cela serait pour plus tard: une fois que toutes les autres fonctionnalité existantes du formulaire soient bug-free. Donc en effet, c'est un "feature" et à @denis-crsj de voir où ça tombe dans le priorités actuelles :)

**Comment by jmalizia** [comment]
fonctionne à merveille
