### ISSUE TITLE
Ne pas permettre de changer le statut d'une prescription lorsque celle-ci est en mode brouillon

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#819]
En ce moment, on peut même changer le status d'une prescription brouillon qui est incomplète à Complétée

**Comment by jmalizia** [comment]
bug initial réglé, mais je rajoute des règles, si prescription est en mode:
@luclemo peux-tu valider que c'est correct avec toi pour le UX

**_Brouillon_** ou **_Incomplète_**
- impossible de pouvoir changer son statut pour tout utilisateur 
- statut est seulement changé si la prescription est soumise

**_Soumise_**
- on ne peut changer que pour les 3 statuts suivants: Approuvée, Incomplète, Refusée

**_Approuvée_**
- on ne peut changer que pour le statut suivant: Complétée

**_Refusée_**
- impossible de pouvoir changer son statut pour tout utilisateur 

**_Complétée_**
- impossible de pouvoir changer son statut pour tout utilisateur

**Comment by YanLabCHU** [comment]
Pour l'instant on laisse ça simple comme ça, plus tard on peut ajouter ces changements si on a le temps @jmalizia

**Comment by jmalizia** [comment]
Bug est réglé, autre carte sera créée avec les autres additions de règles si l'équipe approuvent
