### ISSUE TITLE
Permettre modification de tous les champs de la fiche patient incluant RAMQ

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#832]
- permettre la modification de tous les champs incluant la RAMQ

**Comment by jmalizia** [comment]
@YanLabCHU @claudia1296 @francisprovost 
cette carte semble faite. Je suis capable de modifier.

**Comment by francisprovost** [comment]
Je pense que c'est un duplicate. J'ai effectivement déjà fait ces changements

**Comment by jmalizia** [comment]
ok je la ferme
