### ISSUE TITLE
Permettre la modification de la fiche patient jusqu'à ce qu'une prescription est approuvée

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#840]
- permettre la modification de la fiche patient jusqu'à ce qu'une prescription est approuvée (excluant l'onglet famille)
   - Ceci veut dire que tant qu’une prescription est en statut brouillon, soumise, incomplète ou refusée, le profil patient peut être modifié. Dans toute autre statut, non

**Comment by jmalizia** [comment]
fail -> J'ai créé une nouvelle prescription pour un nouveau patient. J'ai sauvegardé la prescriptoin avant de la soumettre et je pouvais modifier le profil du patient (bouton actif). J'ai ensuite soumise la prescription et le bouton "Modifier" dans la section fiche patient s'est désactivé.
![Screen Shot 2021-04-21 at 9 42 35 AM](https://user-images.githubusercontent.com/73133507/115563824-eae29500-a285-11eb-86b6-1d6465bfeef9.png)

**Comment by jmalizia** [comment]
fail, je peux modifier une fiche patient alors qu'une prescription est approuvée

**Comment by jmalizia** [comment]
@YanLabCHU 
Je peux encore modifier la fiche du patient une fois que la prescription est approuvée. Le bouton devient seulement inactif lorsque je quitte la fiche patient et y revient

![Screen Shot 2021-04-21 at 12 35 20 PM](https://user-images.githubusercontent.com/73133507/115590203-b4fdda80-a29e-11eb-8834-5813bc967d94.png)
![Screen Shot 2021-04-21 at 12 35 29 PM](https://user-images.githubusercontent.com/73133507/115590216-b7f8cb00-a29e-11eb-85c1-1c24485565c5.png)
![Screen Shot 2021-04-21 at 12 35 46 PM](https://user-images.githubusercontent.com/73133507/115590228-ba5b2500-a29e-11eb-9250-768c89aa1faa.png)

**Comment by YanLabCHU** [comment]
@jmalizia Je n'arrive pas à reproduire.

**Comment by jmalizia** [comment]
avec ton cleanup des prescriptipons en QA, ca ne se produit plus, je ferme la carte
