### ISSUE TITLE
Nouveaux components pour les tables de Prescriptions et de Patients

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#846]
Nouveaux components pour les tables de Prescriptions et de Patients

- filtrage --> si je chercher un patient en rentrant son nom dans la barre de recherche (mais sans sélectionner dans les résultat) et que je fais enter --> aucun résultat

- lorsque je change de page, le changement de focus sur le # de page ne se fait pas, même si les données du tableau changent
![Screen Shot 2021-04-21 at 4 36 34 PM](https://user-images.githubusercontent.com/73133507/115617726-bf7c9c00-a2bf-11eb-8a19-a1b65f2f6ad5.png)

- je ne peux modifier le nombre de ligne du tableau par page, si je choisi 100, le tableau est reset mais je suis encore sur la vue 25/page --> peu importe celui que je choisi, rafraichit et reste toujours sur 25/page

**Comment by denis-crsj** [comment]
Tout est beau
