### ISSUE TITLE
Modifier Page 2 du formulaire de prescription (+Médecin et -Consentement)

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#847]
Modifier la page 2 du formulaire de prescription pour supprimer la section Consentement ainsi que sa validation comme champs obligatoire pour pouvoir soumettre. De plus, renommer la section "Approbation" par "Médecins prescripteurs"

**à faire pour la section Consentements**
- supprimer la section
- supprimer validation de champs obligatoire (comme quoi au moins une clause doit être cochée)

**à faire pour la section Approbation**
- remplace le titre "Approbation" de la section par "Médecins prescripteurs" 
- ajouter un radio-button avec 2 choix:
   - Résident(e)
   - Médecin prescripteur
- Si résident sélectionné --> affiche 2 labels avec boîte de recherche dynamique** pour chacun des labels (Résident(e) et Médecin responsable)
   - que les practitioner role ayant le rôle "resident" ne peuvent être chercher dans la boîte
   - peut chercher via le prénom, nom de famille ou numéro de licence
- Si Médecin responsable sélectionné --> affiche seulement que le label (et sa boîte de recherche dynamique**) du médecin responsable
   - que les practitioner role ayant le rôle "médecin prescripteur" ne peuvent être chercher dans la boîte
   - peut chercher via le prénom, nom de famille ou numéro de licence
- pour la MVP, il **n'y aura pas** d'auto-définition du résident ou médecin prescripteur selon l'utilisateur connecté --> doit être absolument défini par le user en y mettant une valeur pour filter
- Résident sera ajouté dans la resource FHIR ServiceRequest via une extension en y définissant le practionerRole du résident
   - élément -> requester
   - cardinalité 0..1 
   - exemple...
     },
  "note": [
    {
         "reference": "Practitioner/pr-001",
         "authorString": "Joe Smith",
         "time": "2019-05-09T11:00:00+00:00",
         "text": "**Statut**: *Incomplète*. **Commentaire** : Manque d'information"
    },
    {
         "reference": "Practitioner/pr-001",
         "authorString": "Joe blo",
         "time": "2019-05-09T11:00:00+00:00",
         "text": "**Statut**: *Approuvée*"
    }
 "resident": {
           "reference": "PractitionerRole/prr-001"
    }
    ]
}

** boîte de recherche dynamique est aussi appelé par certain "la boîte autocomplete" et c'est la même que nous utilisons actuellement pour rechercher le médecin responsable --> l'implanter 2x pour chacun des labels

Maquette
https://www.figma.com/file/Hvh1kY1o0rzzO89IuOYITP/CLIN-Creer-une-prescription?node-id=2155%3A70

**Comment by francisprovost** [comment]
Les changements sont là mais @YanLabCHU doit faire une partie backend pour faire fonctionner la sauvegarde avec un résident

**Comment by jmalizia** [comment]
Yanis doit terminer en backend les modifs

**Comment by YanLabCHU** [comment]
@jmalizia Comme discuté, il faut une carte à part pour le backend, celle là m'était pas assigné et il faut que je priorise avec les autres tâches.
