### ISSUE TITLE
alignements boutons d'actions dans haut de tableau des prescriptions/patients

### ISSUE THREAD

**Issue by jmalizia** [Ferlab-Ste-Justine/clin-project#852]
Aligner les 3 boutons d'actions (Organizer, Afficher, Exporter) en les descendant au même niveau que les onglets du tableau ainsi que le bouton "NANUQ"

![Screen Shot 2021-04-23 at 9.44.02 AM.png](https://images.zenhubusercontent.com/5f8dd5ee86fbfd4e44207bd0/1722866e-3321-4927-abd5-7a8dab9c25e7)

**Comment by denis-crsj** [comment]
tout est beau
